### ISSUE TITLE
Option to toggle enable/disable

### ISSUE THREAD

**Issue by inputjoker** [timmyrs/Universal-Bypass#1]
There are some links that just get exited while using the app. eg: Links from psarips  which uses linkshare

A toggle option would be useful here.

**Comment by timmyrs** [comment]
Can you send an example link?

**Comment by inputjoker** [comment]
This is the issue i am having

https://streamable.com/6nbqf

**Comment by timmyrs** [comment]
I've disabled all extensions except for Universal Bypass like you did, but I'm still not seeing the issue.

I did plan to add an option to enable/disable bypasses in the newest version, however, it didn't work because checking if a bypass is enabled or disabled takes too long.
