### ISSUE TITLE
Block IPLogger settings not load.

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#100]
I turned off "Block IPLogger if they can't be bypassed." option.
I restarted Chrome and visited https://grabify.link.
Website got blocked.
I checked the Universal-Bypass setting page, but that option was unchecked.
I re-checked and unchecked the option and visited https://grabify.link again, I can access normally now.

**Comment by timmyrs** [comment]
I got your pull request, and I already fixed the issue in Universal Bypass 6.8.2.
