### ISSUE TITLE
This site detect universal bypass

### ISSUE THREAD

**Issue by fairyenzy** [timmyRS/Universal-Bypass#1001]
url.topadnetworks.net/fEx6
![Screenshot_Kiwi_Browser_20200305-090129](https://user-images.githubusercontent.com/61671678/75940792-e262ab80-5e85-11ea-85a8-c968e1ce3af0.png)

**Comment by timmyRS** [comment]
That's a faucet. Of course they're gonna have some basic measures to ensure you don't cheat. I recommend waiting about 10 seconds before clicking the destination, or configuring Universal Bypass as such:
![image](https://user-images.githubusercontent.com/11009697/76151676-b9296180-60b7-11ea-9ce4-d1a7c42d6f8b.png)
