### ISSUE TITLE
Is that possible to redirect?

### ISSUE THREAD

**Issue by Dhanamerdeka** [timmyRS/Universal-Bypass#1002]
Can this script make a redirect without opening the link on new tab?
i think that annoying because when the  link is broken like 
Site > OUO.IO > Open in new tab [Zippyshare] and the zippyshare link down... we can't back to prev link...
is anyone have a idea how to do that? i want to open the destination link with redirect automatically without open that in new tab

**Comment by timmyRS** [comment]
Is it possible that you have accidentally configured Universal Bypass like this?
![image](https://user-images.githubusercontent.com/11009697/76004632-1a133700-5f0a-11ea-95d1-70e11365d68c.png)
