### ISSUE TITLE
http://www.cloudgallery.net

### ISSUE THREAD

**Issue by sanGtH** [timmyRS/Universal-Bypass#1006]
Example link of this domain : http://www.cloudgallery.net/ebm0dsgky
There is a timer. Moreover it redirects to some improper domains. Please bypass it. Thanks :)

**Comment by timmyRS** [comment]
That link always automatically redirects me to `https://fiyar.live/data_server_2/3703/big/aabhapaul16.jpg`

**Comment by sanGtH** [comment]
Nope bro i have checked so many times. Ok this time i shall disable other extensions and check if
it works. I shall update

**Comment by timmyRS** [comment]
Seems like uBlock Origin was at fault, but now that I have it disabled, that website doesn't work at all.
