### ISSUE TITLE
https://icutlink.com/

### ISSUE THREAD

**Issue by sanGtH** [timmyRS/Universal-Bypass#1008]
Example link of this domain : https://icutlink.com/y31ps89zR9
There is a timer of 10 secs. Please bypass it bro
Thanks :)
Chrome : v80.xx
Firefox : 72.xx
Both 64 Bit
OS : Win 7 64

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by sanGtH** [comment]
But the timer is still present

**Comment by sanGtH** [comment]
Yep now it's working as you said. Thanks bro :)

**Comment by sanGtH** [comment]
Update : The extension is woking for the domain only if i directly open the link in the brower.
But..WHEN I am redirected from another site -------> as in my case : https://exe.io/zC2IG
It redirects to ----> https://icutlink.com/iDkCUXdXw   Now the extension does not work.
You can check for yourself.
