### ISSUE TITLE
https://adsrt.org/

### ISSUE THREAD

**Issue by sanGtH** [timmyRS/Universal-Bypass#1009]
Example link of the doamin : https://adsrt.org/fQNW
Screen : 
![image](https://user-images.githubusercontent.com/13797193/76143102-48278100-609a-11ea-9735-aea4407b1a0e.png)

Please bypass it bro. Thanks :)
Chrome : v80.xx
FF : v72.x
Both 64bit
OS : Win 7 64bit

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by sanGtH** [comment]
Yes bro, i checked it's working now as you said. Thanks bro. :100:

**Comment by timmyRS** [comment]
> This is already bypassed by crowd bypass, which means **you don't have to wait if someone has already waited on it**.

**Comment by sanGtH** [comment]
Update : The extension is woking for the domain only if i directly open the link in the brower.
But..WHEN I am redirected from another site -------> as in my case : https://pingit.im/dyC9XNir
It redirects to ----> https://adsrt.org/rhS1HEs       Now the extension does not work.
You can check for yourself.

**Comment by timmyRS** [comment]
Is it really that hard for you to grasp the concept of crowd bypass?

**Comment by sanGtH** [comment]
Please read my reply bro..the extension works only when i open the link directly.
But if  i get directed to the link from another link then the extension is not working. You can check for
yourself..

**Comment by timmyRS** [comment]
It works for me in Chrome and Firefox.

**Comment by sanGtH** [comment]
Just go to  https://pingit.im/dyC9XNir and when it re-directs to https://adsrt.org/rhS1HEs
then check whether the extension is working or not.

**Comment by timmyRS** [comment]
It does.

**Comment by sanGtH** [comment]
Now i checked another adsrt link : https://adsrt.org/webDUbUW Here the extension is not working.
Maybe the extesnion is working for individual links not the complete domain.

**Comment by timmyRS** [comment]
Yes, that is what crowd bypass is. Some websites (like adsrt.org) can't be bypassed by traditional means, but when someone else has already waited for a particular link, then you will no longer have to wait. Make sense?

**Comment by sanGtH** [comment]
> 
> 
> Make sense?
Little actually. So i have to wait to wait for others to pass through that link before i can proceed.
Can't be done everytime. Here i guess adsbypasser comes handy.

**Comment by sanGtH** [comment]
> 
> 
> Yes, that is what crowd bypass is. Some websites (like adsrt.org) can't be bypassed by traditional means, but when someone else has already waited for a particular link, then you will no longer have to wait. Make sense?

**Comment by sanGtH** [comment]
> 
> 
> Make sense?

Little actually. So i have to wait to wait for others to pass through that link before i can proceed.
Can't be done everytime. Here i guess adsbypasser comes handy.

**Comment by timmyRS** [comment]
AdsBypasser will also not be able to bypass it.
