### ISSUE TITLE
Problem with cuio.io

### ISSUE THREAD

**Issue by collest** [timmyrs/Universal-Bypass#101]
Last week on this site  (http://cuio.io) the bypass was working correctly, but now bypasses no longer work.

**Comment by timmyrs** [comment]
Can you provide an example link?

**Comment by timmyrs** [comment]
Nevermind, I just realized it's not a private shortener. Working on a fix now...

**Comment by timmyrs** [comment]
Fixed in Universal Bypass 6.9.1.

**Comment by oleedd** [comment]
It stopped to work.
