### ISSUE TITLE
Add bypass semawur.com

### ISSUE THREAD

**Issue by sachiko27** [timmyRS/Universal-Bypass#1014]
pls add fully bypass for semawur.com, because this site not fully bypassed
this is can bypassed https://semawur.com/hXtYwaR
this is can't bypass https://semawur.com/fOJOf9ZZyB6d

thanks before

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by LGLTeam** [comment]
How do i do when it's the first time? I don't see download or countdown anywhere

https://semawur.com/5NFoT
https://semawur.com/i6B2p
