### ISSUE TITLE
"Instantly take me to destinations of trackers." not working

### ISSUE THREAD

**Issue by katchy3132** [timmyRS/Universal-Bypass#1016]
The option "Instantly take me to destinations of trackers." is checked but the extension screen shows up and I am not redirected instantly or at all- it looks like I need to click the link to proceed.
 If I check "take me to destination after x seconds" that shows up on the screen as expected and then redirects after x seconds .

My options : 
![image](https://user-images.githubusercontent.com/3707138/76164752-04944c00-615a-11ea-828f-5ce1b16d262c.png)

results in : 

![image](https://user-images.githubusercontent.com/3707138/76164756-0e1db400-615a-11ea-955e-ff2ef1ddf6fc.png)

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by katchy3132** [comment]
Its usually from TweetDeck.
both the picture (https://t.co/OtMjiqNTOP)  and the link (https://reut.rs/2PYu4No)  in this tweet. https://twitter.com/Reuters/status/1236673204007165954

**Comment by timmyRS** [comment]
reut.rs is not bypassed by the tracker bypass, and the t.co link seems to work as intended

**Comment by timmyRS** [comment]
Ah, it's another one of those wonderful things you only have in a browser where Google applied its "logic."

**Comment by katchy3132** [comment]
strange. it seems to be something with TweetDeck. The reuters link is now not stopping at the extension screen. it was before. but if I go to the tweet in TweetDeck, then click on the picture and then click on "View Original" then I get the extension screen. If I click on the t.co link in my comment above it goes through as it should. Why would that be ?

**Comment by timmyRS** [comment]
As I said, reut.rs is not bypassed by the tracker bypass, so Universal Bypass never sees that request, and the t.co link in your comment is malformatted, so Google is probably doing some magic, which happens to ignore any extensions.

**Comment by katchy3132** [comment]
It turns out I had 13.4 installed but the extension was reporting that I was up to date. Uninstalling and reinstalling  13.6.2-c44e08f has fixed this.
