### ISSUE TITLE
Edge Support

### ISSUE THREAD

**Issue by masnoob** [timmyrs/Universal-Bypass#102]
Hi I am highly interested in this amazing bypass.
May I know if there are any plans to port it to EDGE browser?
Thanks

**Comment by timmyrs** [comment]
I've just released Universal Bypass 7.0, which is compatible with Edge, but I still haven't received a reply from Microsoft yet to get it on the Windows Store. So, we'll just have to wait.

**Comment by masnoob** [comment]
Glad to hear that Thanks !
