### ISSUE TITLE
123allstatus.com

### ISSUE THREAD

**Issue by ghajini** [timmyRS/Universal-Bypass#1024]
this link
https://123allstatus.com/verify.php?n=aHR0cHM6Ly9tZWdhdXAubmV0L1BzOXYvRXh0cmFNb3ZpZXMuY2FzYV9URzIwRk1FNzJCUkVTRC5ta3Y=https://123allstatus.com/verify.php?n=aHR0cHM6Ly9tZWdhdXAubmV0L1BzOXYvRXh0cmFNb3ZpZXMuY2FzYV9URzIwRk1FNzJCUkVTRC5ta3Y=

from here

http://extramovies.casa/download.php?name=The+Grudge+%282020%29+Full+Movie+%5BEnglish-DD5.1%5D+720p+BluRay+ESubs+Download&link=aHR0cHM6Ly9tZWdhdXAubmV0L1BzOXYvRXh0cmFNb3ZpZXMuY2FzYV9URzIwRk1FNzJCUkVTRC5ta3Y=

Or from here file hosters
http://extramovies.casa/the-grudge-2020-full-movie-english-dd5-1-720p-bluray-esubs-download/

**Comment by timmyRS** [comment]
This will unfortunately require an extension update (13.8).
