### ISSUE TITLE
Universal bypass is being removed automatically by chrome based browsers

### ISSUE THREAD

**Issue by serial02** [timmyRS/Universal-Bypass#1027]
Hello

Every day I need to reinstall the universal bypass on chrome-based browsers.If I update manually unzipped or by dragging the zipped file, it works normally, but after restarting the machine they are automatically removed.
The only browser that remains up to date is Firefox, as the installation is done by the store.I believe that you should put this app back in the chrome web store again.

![Brave](https://user-images.githubusercontent.com/32621790/76626920-cb245d80-6518-11ea-9b58-4969166c9d93.png)

![Opera](https://user-images.githubusercontent.com/32621790/76626895-bc3dab00-6518-11ea-94f4-148b268c6659.png)

![Captura de Tela_20200313101944](https://user-images.githubusercontent.com/32621790/76626911-c8296d00-6518-11ea-9613-874f23544a6d.png)

![Chromium](https://user-images.githubusercontent.com/32621790/76626914-c9f33080-6518-11ea-8048-7865978a6630.png)

Your considerations

Edson Santos

**Comment by timmyRS** [comment]
Tell that to Google.
