### ISSUE TITLE
bc.vc redirecting to random site

### ISSUE THREAD

**Issue by collest** [timmyrs/Universal-Bypass#103]
The redirection of bc.vc does not work well, since after 5 seconds of waiting, it is routed to a random site like "https://rotumal.com/afu.php". Sometimes works 5 or 6 attempts opening the same link in 5 or 6 tabs.

Example: http://bc.vc/CddPf8j

Can it be fixed?

**Comment by timmyrs** [comment]
I'm experiencing that with Universal Bypass disabled, so bc.vc is probably broken.
