### ISSUE TITLE
Doesn't work well with "http://cinebo.net/" brings a 404 "looks like you found a dead link"

### ISSUE THREAD

**Issue by Leifman27** [timmyrs/Universal-Bypass#104]
when while disabling universal bypass it works fine...
example for a link : http://q.gs/EeIcd

**Comment by timmyrs** [comment]
Universal Bypass bypasses the example link perfectly fine for me. Make sure you disable other extensions which may interfere.

**Comment by Leifman27** [comment]
i literally have no other extensions that might interfere... and it always
worked fine for me before too.
but when i go to this link for example : http://q.gs/EeIch
i end up in this url :
https://universal-bypass.org/before-navigate?target=https%3A%2F%2Fclk.ink%2FWQtP
which then shows me the "404

Whoopsy Daisy! It looks like you've found a

Dead Link" page

**Comment by timmyrs** [comment]
You shouldn't end up there, as the background script will intercept that request. Try reinstalling Universal Bypass and restarting your browser.

**Comment by Leifman27** [comment]
Firefox, version 50.0, maybe that's the cause?

**Comment by Leifman27** [comment]
but yeah now i no longer end up there (so whatever the issue was with
firefox 50.0 you fixed it)
now i get redirected to the clicksfly page (which btw, i think universal
bypass doesn't work well with "buyitonline.store" , at least in the past it
used to skip the "im not a robot" + the countdown, but now it doesn't. i am
referring to the link above)
but regardless, thank you for fixing this issue! as the main issue was that
i didn't wanna have to disable the addon to prevent that 404 thingy

**Comment by timmyrs** [comment]
buyitonline.store uses the Adlinkfly template, and the bypass for that uses crowd bypass, so other people will have to have already waited on that for it to be bypassed, which is a bit hit or miss, but it works.

**Comment by Leifman27** [comment]
ah interesting, thanks for the clarification! and for the help. much
appreciated.

**Comment by Leifman27** [comment]
btw, i decided to test it out and see how it is in a newer version, and i
upgraded my firefox from 50.0 to 52.9.0esr (well it is the latest
available/supported version on xp)
funny enough, universal bypass actually completely does not work on firefox
52.9.0esr. it was quite a surprise for me i guess hehe, seeing that on 50.0
it works fine (and post that fix you did with the redirect that fixed it)
on 52.90esr however, if we take that same link i used for example (
http://q.gs/EeIch) and i click it, i end up at a "blank page" (literally
looks like about:blank) with the "bee icon" up top saying "Shrink your url
and get paid!" which the url of is :
http://cinebo.net/-20LUXG/EeIch?rndad=1833124135-1546429228

Just thought ill report this to you... it's easy for me to fix and just
revert to firefox 50.0 i was using thus far, but figured you'd like to know
this happens and makes universal bypass broken on 52.9.0esr

**Comment by timmyrs** [comment]
Consider upgrading to at least Windows 7. XP doesn't get updates anymore and is an extreme risk to your computer's security.

**Comment by Leifman27** [comment]
Don't let that worry you. i'm quite aware of that and have been for quite a
while now

**Comment by timmyrs** [comment]
Yeah, but this is probably just an edge case with your older OS, which I can't reproduce.

**Comment by Leifman27** [comment]
I honestly don't think so. it's just something odd that is a "present
problem" with Firefox 52.9.0 ESR and not with Firefox 50.0 , that said on
windows xp.
I just found it kinda funny and weird that it happens. like, doesn't common
sense dictate that an older version is more likely to not work/have issues
rather than the "later/latest" one (which it really is the latest one for
XP)
anyways all good :) i just thought ill report it. ill probably revert to
50.0 anyway, and then will still be able to use universal bypass to due to
the redirection issue you fixed yesterday
