### ISSUE TITLE
i cant download the spoofer

### ISSUE THREAD

**Issue by BrokeQuadrix** [timmyRS/Universal-Bypass#1041]
i cant download the spoofer i get on this site : https://universal-bypass.org/navigate?target=http%3A%2F%2Foverhaxweebloader.tk%2FOVERHAX%2520SPOOFER%2520UPDATER.exe&referer=https%3A%2F%2Ftii.ai%2Foffical_overhax_spoofer if i klick this link : https://universal-bypass.org/navigate?target=http%3A%2F%2Foverhaxweebloader.tk%2FOVERHAX%2520SPOOFER%2520UPDATER.exe&referer=https%3A%2F%2Ftii.ai%2Foffical_overhax_spoofer

**Comment by timmyRS** [comment]
What?
