### ISSUE TITLE
Universal Bypass Not on Chrome Web Store

### ISSUE THREAD

**Issue by zkisaboss** [timmyRS/Universal-Bypass#1042]
I'm trying to download Universal Bypass on my other computer and I couldn't find it on the web store. Did it get deleted or something?

**Comment by timmyRS** [comment]
#961

**Comment by timmyRS** [comment]
Also, I just noticed it is available in the Chrome store again now: chrome.google.com/webstore/detail/aihomhdbhpnpmcnnbckjjcebjoikpihj

**Comment by LightGrey** [comment]
> Also, I just noticed it is available in the Chrome store again now: https://chrome.google.com/webstore/detail/universal-bypass/aihomhdbhpnpmcnnbckjjcebjoikpihj

btw it's not the latest version, could you do somthig about it?

**Comment by timmyRS** [comment]
I've submitted 13.8.1 for Google to "review," it's going to be the usual 10 million year release schedule on Google's shitty browser. I'm just I could talk to an actual human at Google to get it back on the store.

**Comment by ghajini** [comment]
>  I'm just glad I could talk to an actual human at Google to get it back on the store.
@dotproto

**Comment by timmyRS** [comment]
> Developer Advocate for Chrome Extensions

Aka. "sadist"
