### ISSUE TITLE
linkvertise.com

### ISSUE THREAD

**Issue by GameOverYoutuber** [timmyRS/Universal-Bypass#1043]
Linkvertise is Not Working on Universall Bypass

**Comment by timmyRS** [comment]
@ikancupang ping if you wanna look at this

**Comment by ghajini** [comment]
UB Ver 13.8, firefox stable bypass not work

https://linkvertise.com/72583/697.083171537096/dynamic?r=aHR0cDovL3RvdGFsZGVicmlkLm9yZy8xRi9mOTEyYzU5OWI2L0FFVy5EQVJLLkVQSVNPREVfJTI1MjAzXzExXzIwLkxRLm1wNA%3D%3D

**Comment by timmyRS** [comment]
That'll be fixed in the next release.
