### ISSUE TITLE
Can't this bypass 3dm forum download link lock mechanism?

### ISSUE THREAD

**Issue by AsteryRan** [timmyRS/Universal-Bypass#1044]
It doesn't seems to work then again i doubt it will, but if you do found a way i believe there're a lot of people who will be thankful.
https://bbs.3dmgame.com/thread-5989147-1-1.html

**Comment by timmyRS** [comment]
If you mean the "please reply if you want to view the hidden content of this post" part, then that can unfortunately not be bypassed, but if you don't wanna create an account you can use bugmenot: http://bugmenot.com/view/bbs.3dmgame.com
