### ISSUE TITLE
Can't Downloading Bypass Definitions

### ISSUE THREAD

**Issue by fairyenzy** [timmyRS/Universal-Bypass#1045]
Stuck At Downloading Bypass Definitions
![Screenshot_Kiwi_Browser_20200318-092033](https://user-images.githubusercontent.com/61671678/76918961-69207b00-68bf-11ea-9e72-7b1afc47632f.png)

**Comment by timmyRS** [comment]
The kiwi browser is not officially supported.

**Comment by timmyRS** [comment]
13.8.1 is available on the Chrome web store now, and a lot has changed since 13.5, including a bug fix where older Chromium-based browsers wouldn't work, maybe that includes your kiwi browser.

**Comment by FireMasterK** [comment]
I can confirm that it works.

**Comment by fairyenzy** [comment]
Now is worked, thx
![Screenshot_Kiwi_Browser_20200319-132841](https://user-images.githubusercontent.com/61671678/77038288-571c0680-69ab-11ea-8d61-d5411171f677.png)
