### ISSUE TITLE
tii.ai not work

### ISSUE THREAD

**Issue by EtianAM** [timmyRS/Universal-Bypass#1048]
Only a link shorter from Shrinkearn, thanks.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by Mahmoudmohamedtg7** [comment]
These are the sites sir engineer
This links:
shortearn.eu
shortlink360.com
shorten.sh
ex-foary.com
cutearn.net
shotly.io
shrink.pe
shortlink180.com
s-short.co
kekolink.com
adshrinks.com
https://exe.io/CBqplbg5sns
bitlinks.pw/sh
birdurls.com
oneurls.org
owlink.net
https://fc.lc/CBnrm3uhzkl
https://shortbitsfree.net/CB9lbonw5ra
shlinko.com
skip.az
bitcoinly.in
boxlink.us
topshort.net
dogemanager.com
bigb0ss.net
bit-url.com
dutchycorp.ovh/sl


  In the future, I will donate for your support
Thank you for the excellent work. I appreciate that

Op Do. 19 Mrt. 2020 om 20:29 het Tim Speckhals <notifications@github.com>
geskryf:

**Comment by EtianAM** [comment]
> Could you provide an example link?

https://tii.ai/79kq6f

I do not know if it works now....

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by Mahmoudmohamedtg7** [comment]
Well sir this is the links

https://cash4.link/how-would-you-plan-a-world-trip-if-you-had-1000-per-day-to-spend/
https://shotly.io/CBav2mbifz1
https://aii.sh/CB9zw81aq51
https://fullytech24.com/CBmuf5zxa7c
https://s-short.co/CBu0hq8mgqn
https://kekolink.com/CB9u9vnrecj
https://adshr.ink/CB0t5fdtfsx
https://exe.io/CBe3juvdfci
https://faupto.com/sh/CB47jnw20f6
https://birdurls.com/CBqehilevlm
https://oneurls.org/CBb6zknr62v
https://owllink.net/CB3gpuqw4vi
https://fc.lc/CBfbbz0u9al
https://shortbitsfree.net/CBsjmq00prc
https://shlinko.com/CBsia9wnnnq
https://skip.az/CB6p8mxrrct
https://bitcoinly.in/CB90sewj207
https://boxlink.us/CBsmw7dz3xm
https://url.topadnetworks.net/CBfbzd4xfx2
https://dogemanager.com/CB5mir8izq5
https://bigb0ss.net/CBcsrlrmdgu/1/b7e7651d962428c99cdf0d080c86041e
https://bit-url.com/CBg3p7gk2e2
https://dutchycorp.ovh/sl/CBqn474lp4n
https://dutchycorp.ovh/sl/CBqn474lp4n?verif=JkO4Zn2I

Op Vr. 20 Mrt. 2020 om 02:55 het Etian Daniel Alavardo Mtz. <
notifications@github.com> geskryf:
