### ISSUE TITLE
Dear Sir, This message always appears to me when I visit any link to this website

### ISSUE THREAD

**Issue by Mahmoudmohamedtg7** [timmyRS/Universal-Bypass#1053]
Sir please solve this same problem clipping screen show me in all these sites
Please see what happens
![2020-03-19_212730](https://user-images.githubusercontent.com/62382189/77139002-48a21d80-6a85-11ea-858e-0d8dc785a113.jpg)

**Comment by Mahmoudmohamedtg7** [comment]
This problem applies to all of these sites

https://cash4.link/how-would-you-plan-a-world-trip-if-you-had-1000-per-day-to-spend/
https://shotly.io/CBav2mbifz1
https://aii.sh/CB9zw81aq51
https://fullytech24.com/CBmuf5zxa7c
https://s-short.co/CBu0hq8mgqn
https://kekolink.com/CB9u9vnrecj
https://adshr.ink/CB0t5fdtfsx
https://exe.io/CBe3juvdfci
https://faupto.com/sh/CB47jnw20f6
https://birdurls.com/CBqehilevlm
https://oneurls.org/CBb6zknr62v
https://owllink.net/CB3gpuqw4vi
https://fc.lc/CBfbbz0u9al
https://shortbitsfree.net/CBsjmq00prc
https://shlinko.com/CBsia9wnnnq
https://skip.az/CB6p8mxrrct
https://bitcoinly.in/CB90sewj207
https://boxlink.us/CBsmw7dz3xm
https://url.topadnetworks.net/CBfbzd4xfx2
https://dogemanager.com/CB5mir8izq5
https://bigb0ss.net/CBcsrlrmdgu/1/b7e7651d962428c99cdf0d080c86041e
https://bit-url.com/CBg3p7gk2e2
https://dutchycorp.ovh/sl/CBqn474lp4n
https://dutchycorp.ovh/sl/CBqn474lp4n?verif=JkO4Zn2I

**Comment by timmyRS** [comment]
Unfortunately, these sites can only be bypassed by crowd bypass, and if you are the first to encounter them, you have to wait, and now please stop spamming me.

**Comment by Mahmoudmohamedtg7** [comment]
I didn't understand, sir. Can you please explain?

Op Vr. 20 Mrt. 2020 om 08:36 het Tim Speckhals <notifications@github.com>
geskryf:

**Comment by timmyRS** [comment]
There is no way to bypass these sites, so Universal Bypass uses a crowd-sourcing system so that when you wait on a link, other users won't need to wait any more.
