### ISSUE TITLE
bypass not working on cuio.io

### ISSUE THREAD

**Issue by TontyTon** [timmyrs/Universal-Bypass#106]
Example link from examplelinks - http://cuio.io/OtS6xdc

**Comment by timmyrs** [comment]
Works fine for me, make sure you have "Give and take the destinations of unbypassable shorteners." enabled.

**Comment by TontyTon** [comment]
Its enabled. page redirects me to cuee.io/OtS6xdc.

**Comment by timmyrs** [comment]
Yes, and cuee.io ist bypassed, so what's the issue?

**Comment by TontyTon** [comment]
no it is not bypassed

**Comment by timmyrs** [comment]
It is bypassed if you have crowd bypass enabled.

**Comment by TontyTon** [comment]
is it needed to be enabled seperately?

**Comment by timmyrs** [comment]
The default options looks like this and the highlighted option should be enabled:
![image](https://user-images.githubusercontent.com/11009697/50702419-30490d00-1051-11e9-8650-0ffd3dd222db.png)

**Comment by TontyTon** [comment]
yes its already enabled

**Comment by timmyrs** [comment]
Which browser and which version of Universal Bypass are you using?

**Comment by TontyTon** [comment]
My browser is latest chromium based. All other bypasses working fine except crowd bypass(from example links).

Its is working for you, then there is problem at my end somewhere. So, there is no problem in extension. I will sort it out.
Thanks for really quick replies.

**Comment by timmyrs** [comment]
It might be an issue on my part. Let me know if you find out what the issue is.

**Comment by TontyTon** [comment]
definitely
I am trying to reinstall and other basic things.
Will let you know if I find something

Thanks for quick replies and for this wonderful program

**Comment by TontyTon** [comment]
maybe i figure it out all links with reCAPTCHA are not working. Maybe because it don't believes my IP.

**Comment by timmyrs** [comment]
No problem. It can't be recaptcha because the crowd bypass asks my server if it already knows the destination.

**Comment by TontyTon** [comment]
oops, really great coincidence, I tried all sites in example sites and all sites which weren't bypassed had reCAPTCHA. **Each and every one**.

**Comment by timmyrs** [comment]
That's weird. Is it possible that you have some other extension or script installed which tries to bypass captchas?

**Comment by timmyrs** [comment]
I like problems. Could you give me more details on which browser you are exactly using? You said chromium; do you mean google chrome or a variant?

**Comment by timmyrs** [comment]
Just got a fresh install of brave and as soon as I disable the built-in "Shields" on the site, it's bypassed. So, I might have to get in touch with Brave to update their Ad Block thingy, so my extension won't break.

**Comment by timmyrs** [comment]
Opened an issue at https://github.com/brave/brave-browser/issues/2826

**Comment by salman43206** [comment]
sir universal bypass not working to two day ago
