### ISSUE TITLE
Explanation of features/options

### ISSUE THREAD

**Issue by SonOfDiablo** [timmyRS/Universal-Bypass#1060]
I just installed Universal Bypass, and while looking over the options I noticed that there isn't a great explanation of what each feature actually do.

I then looking at the FAQ, which wasn't to much help either.
Thus I'm here, making a request for for actually describing the features of this extension.

While one can take a guess at what these does, it would be great with a definite explanation. example being "Open crowd-sourced destinations", my guess would be it looks for the short/redirect link in some sort of database that has been collected by users and redirect to the resulting page. But in the end that's just a guess.

**Comment by timmyRS** [comment]
I've updated the FAQ: https://universal-bypass.org/faq#crowd
