### ISSUE TITLE
autofaucet.org is detecting Universal Bypass

### ISSUE THREAD

**Issue by greatwolf** [timmyRS/Universal-Bypass#1065]
> Before you report a website that detects Universal Bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/timmyRS/Universal-Bypass/issues?utf8=%E2%9C%93&q=autofaucet.org
> I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.
> 
> If that is not the case, please **provide an example link.** We need to be able to see what has gone wrong in order to fix it.
> 

To reproduce, go to any of the shortlinks here: https://autofaucet.org/dashboard/shortlinks

For me after doing the shortlink and seeing the Universal Bypass page, clicking on the next link gives an error msg on autofaucet.org:

> Your action is marked as suspicious! Please turn off the Shortlink Bypass extension which is installed on your browser. Error code: 1051

**Comment by timmyRS** [comment]
Alright, I've excluded autofaucet.org from the crowd bypass backend.
