### ISSUE TITLE
Having issues with a faucet service? Read this first!

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#1068]
Universal Bypass was not meant for faucet services, and I've now strictly removed and disallowed any faucet services from the crowd bypass backend, simply because they don't fall into Universal Bypass' scope, and crowd bypass is not a solid solution for them, anyway. I know that the sites that faucet services use are what Universal Bypass would normally bypass, but in combination with a faucet service, they're an ad wall **that you asked for**. That being said, if a faucet service is breaking because of Universal Bypass, I will make sure that it works, but that's it.

**Comment by Ciccio90x** [comment]
Is it possible to remove these limitations?

I don't understand why disabling the plugin for faucets but bypassing all the other links is allowed. I don't see coherence

**Comment by timmyRS** [comment]
I've decided to allow faucets in crowd bypass, but for no more than 2 days, as not to waste those resources.
