### ISSUE TITLE
XFINITY my account site won't load 

### ISSUE THREAD

**Issue by keisoko** [timmyrs/Universal-Bypass#107]
When I try to load XFINITY My Account site at https://customer.xfinity.com/#/, the site won't load past the initial page with progress circle on it. When I disable Universal Bypass extension, the site will load normally. Below is the image of the page I can't pass by.

![image](https://user-images.githubusercontent.com/12021975/50704413-44771500-1025-11e9-9e1c-0ae5980c17e2.png)

**Comment by timmyrs** [comment]
When I visit, it redirects me to log in. I don't have an account there, so I can't verify what will happen when you are logged in. Is there anything in the developer console (F12)?

**Comment by keisoko** [comment]
It says  Content Security Policy: The page’s settings blocked the 
loading of a resource at inline (“default-src”) at 
customer.xfinity.com:100:1
------ Original Message ------

**Comment by timmyrs** [comment]
I blame Mozilla and Xfinity for this problem...

**Comment by timmyrs** [comment]
The new version is already available on AMO, so just update your add-ons, and the issue should be resolved.
