### ISSUE TITLE
screamsploit key system

### ISSUE THREAD

**Issue by Uranite** [timmyRS/Universal-Bypass#1072]
another lego hack, the link is https://linkvertise.com/60994/ScreamSploitkey

**Comment by timmyRS** [comment]
Is there any link before that?

**Comment by Uranite** [comment]
> Is there any link before that?

just that

**Comment by timmyRS** [comment]
Then their detection is broken, since there is no toneden bypass.

**Comment by Uranite** [comment]
> Then their detection is broken, since there is no toneden bypass.

but theres a link after that: https://ihaxu.ml/KeySystem/Checkpoint1/
