### ISSUE TITLE
Soralink bantusebarkan.blogspot.com

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#1079]
https://bantusebarkan.blogspot.com/2020/02/the-best-travel-credit-cards-for-work.html

**Comment by ikancupang** [comment]
It's not soralink, the example link is wrong, it should be 
https://bantusebarkan.blogspot.com/2020/02/the-best-travel-credit-cards-for-work.html?url=aHR0cHM6Ly9naXRodWIuY29tL3RpbW15UlMvVW5pdmVyc2FsLUJ5cGFzcy9pc3N1ZXMvMTA3OQ==
