### ISSUE TITLE
Is there an PHP Api for Universal Bypass?

### ISSUE THREAD

**Issue by FabiCrafter** [timmyRS/Universal-Bypass#1101]
Example : http://127.0.0.1/api.php?url=[YOURURL]

Output : [OUTPUTFROMUNIVERSALBAPASS]

**Comment by Uranite** [comment]
seems interesting, i wonder how this will work

**Comment by timmyRS** [comment]
No. In theory you could probably do something with Chromium and a custom build of Universal Bypass to see what it does, but this project is JavaScript, and many bypasses need to be run as an extension to truly work.

**Comment by FabiCrafter** [comment]
timmyRS könntest du mir vllt. dein Discord Namen schicken? will bissel schreiben und testen

**Comment by timmyRS** [comment]
Sai#2020
