### ISSUE TITLE
PEZZI I PULLA

### ISSUE THREAD

**Issue by VyperJC** [timmyRS/Universal-Bypass#1103]
U SAI CA TO MATRI é NA PULLAZZA 

COMU MINCHIA INDENTI VA PIGGHIA FUOCU COMU GIOVANNA D'ARCO

TU E DA BUTTANA I TO MATRI

PS. TO MA è MIA

**Comment by timmyRS** [comment]
What?

**Comment by VyperJC** [comment]
O MA SI VERU PULLA UN AVIEVA TUAITU

PULLAAAAAAAAAAAA E ARRUSAAAAAAAAAAAAAAAA

**Comment by timmyRS** [comment]
Do you speak English?
