### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by VyperJC** [timmyRS/Universal-Bypass#1104]
how the code for stayonline.pro work? i've tried to do a reply and this did error to me for with the 'Access-Control-Allow-Origin', can you help me?

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by VyperJC** [comment]
https://stayonline.pro/l/wLZnY/

**Comment by timmyRS** [comment]
Seems to be working for me in Chrome and Firefox. What's your setup?

**Comment by VyperJC** [comment]
perhaps there was a misunderstanding in the question. The extension works perfectly, I just wanted to know how the code that bypasses 'stayonline.com' worked, because if I try to replicate the code it gives me the error: 'Access-Control-Allow-Origin', also trying different solutions through the PHP easily foundable on stackoverflow, that's all

**Comment by timmyRS** [comment]
I think those warnings could be ignored, but in Chromium, extensions have privileges to inject a script, and in Firefox some hole-punching is done to avoid access control.
