### ISSUE TITLE
nitroflare.com

### ISSUE THREAD

**Issue by Sopor-** [timmyrs/Universal-Bypass#111]
This [site](https://nitroflare.com/view/D019BE4D328EA82/Stratovarius_-_Enigma_Intermission_II-%280213397EMU%29-Digipak-2018-MCA_int.rar) has a 2 minute countdown.

**Comment by timmyrs** [comment]
As much as I hate to say it, there's nothing I can do to bypass that. They make sure you've actually waited 2 minutes in the backend. :/

**Comment by Sopor-** [comment]
Sad to hear :(
