### ISSUE TITLE
www.busyfinance.site

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#1111]
https://www.busyfinance.site/2020/04/business-finance-source-and-business.html

from: http://144.217.211.162/red-shoes-and-the-seven-dwarfs-2019/

**Comment by ikancupang** [comment]
Looks like the link is incomplete, the link should be like this
https://www.busyfinance.site/2020/04/modern-financial-advising-for-beginners.html?safe=d66cc53a3e1397c5488a05c572ae5b0f2c612a9c9697b355a7c8bbe05e73df39fdbc252dcf5530f8e32b1d884ddaea4ba1adb55eba0811ed33f1333d19d5820516b7fa4a06c9c90ecd386a719555bd7b5adbc03610d2de75f74a66593462f67af55f165c8a090584
