### ISSUE TITLE
Universal Bypass No longer bypasses Ad.Fly

### ISSUE THREAD

**Issue by LimitlessGamingmelon** [timmyRS/Universal-Bypass#1115]
Started today. all adfly links are now unable to be bypassed.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by greatwolf** [comment]
I'm getting similar issue except it's on adsy.pw. For example: https://adsy.pw/link/G4dOBIbn

**Comment by timmyRS** [comment]
Check for updates in the options.

**Comment by greatwolf** [comment]
Thanks, I just did the update. Definitions now at `f853411`. Seems to be working again for me.

Thanks
