### ISSUE TITLE
Linkvertise website no longer working

### ISSUE THREAD

**Issue by Oki22** [timmyRS/Universal-Bypass#1117]
hey ive gotten a few friends to also check if the website linkvertise is working and it is not can you check it out?

**Comment by timmyRS** [comment]
Check for updates in the options.

**Comment by Diorize** [comment]
linkvertise isnt working for me aswell.

**Comment by ghajini** [comment]
Hello during bypass of ads (from linkvertise)
http://totaldebrid.org/lien/?file=aaaff64540547df

Bypass occurs then error occurs =

`Oups ! Il semblerait que quelque chose ne vas pas...
Passez-vous correctement les pubs ?
(ceci est une erreur liée au fait que les pubs ont été sautées, si vous avez une extension qui bypass les pubs, merci de la désactiver.)

Essayez de retourner sur le lien précédent , si le problème persiste, contacter nous via le chat .`

***Which translates to***
`Oops! Something seems to be wrong ...
Are you advertising correctly?
(this is an error related to the fact that the ads have been skipped, if you have an extension that bypasses the ads, please deactivate it.)

Try to return to the previous link, if the problem persists, contact us via chat.`
