### ISSUE TITLE
AMO vs. self-hosted solution thoughts

### ISSUE THREAD

**Issue by matijakovacevic** [timmyRS/Universal-Bypass#1120]
By looking at the reason why you ditched AMO, from
[https://universal-bypass.org/faq#self-hosting](https://universal-bypass.org/faq#self-hosting)

I must say, I understand why a self-updating feat would raise a RED flag with the AMO team.

Basically, even though open-source, your self-hosting solution does not incline me to use it, as it opens a huge security issue:
- upon installation user is required to give permission to "Access your data for all the websites", which is a huge deal by itself.

Inside AMO I am at least by some degree protected addon dev's aren't going to use my data for non-agreed purposes.
Outside I'd (or anyone else) have to constantly check github repo if some 'bad' changes were introduced.

Just to point out, kudoz for doing this add-on, and I'm not pointing at you having
bad intentions with this, just providing my point of view on security issues with this.

Thx!

**Comment by timmyRS** [comment]
It was disabled for having auto-updating 4 months after auto-updating was added. If you trust any extension store to review any capacity, you are sadly mistaken. I created a non-auto-updated version, which would have been more updates and effort to ultimately just being on AMO, which is no difference to self-hosting, other than having reviews, in my opinion.

**Comment by AveYo** [comment]
> I created a non-auto-updated version, which would have been more updates and effort to ultimately just being on AMO, which is no difference to self-hosting, other than having reviews, in my opinion.

But AMO was good to gain a user base, right?

> so I thought "Fuck Mozilla, we're keeping auto-updating." and here we are  

This might be more relevant in the news popup about self-hosted.. so users can make an informed decision.
