### ISSUE TITLE
Universal Bypass notification isn't going away

### ISSUE THREAD

**Issue by Yakov5776** [timmyRS/Universal-Bypass#1122]
![firefox_8iItOJUijj](https://user-images.githubusercontent.com/28637006/78725130-d347a100-78fc-11ea-8968-4626df5c9375.png)
It keep's showing up, it'll disappear after I click it but once i reload it pops up again

I'm using firefox by the way.

**Comment by timmyRS** [comment]
Uninstall Universal Bypass. Get it from https://universal-bypass.org/

**Comment by ahnafnafee** [comment]
That's not really solving the issue. An option should be provided to users to stop notifying this message instead of pestering users with the message again and again. Furthermore, I installed the local version and still getting the pop up.

**Comment by timmyRS** [comment]
The message appears if:
1. You're using Firefox.
2. Universal Bypass is not at version 13.9.

**Comment by ahnafnafee** [comment]
I checked and saw both versions were installed which was causing the pop-up, thank you.

**Comment by timmyRS** [comment]
If you're having a "connection failure," go to about:config then click "I'll be careful I promise", right-click and select New > String, name it xpinstall.enabled and set the value to true.

**Comment by Yakov5776** [comment]
It's fixed I had to reinstall from site
