### ISSUE TITLE
Some Link Shortners Aren't Bypassed

### ISSUE THREAD

**Issue by DjDiddles2000** [timmyrs/Universal-Bypass#117]
I have found a number of ad shortner links, that aren't getting bypassed. Most of them are from " https://shorte.st/" cuz it will change its URL to things like " http://corneey.com/ "

**Comment by timmyrs** [comment]
There is no bypassing required for shorte.st, as you are automatically redirected to noriskdomain.com, which Universal Bypass does bypass.
