### ISSUE TITLE
Clicksfly site is not bypassing captcha and later the timer too

### ISSUE THREAD

**Issue by rokibhasansagar** [timmyrs/Universal-Bypass#119]
in the _clicksfly_ alias site https://clk.ink/ the captcha is showing now instead of auto-bypass.
And when I manually pass the captcha challenge, the timer of 10 second is also not auto-bypassing.

A week ago, there were no issue with this site.
But now it is not working for me.

`Using on Mozilla Firefox for Ubuntu 18.04 LTS along with uBlock Origin and Nano Defender`

**Comment by timmyrs** [comment]
This site is bypassed using a crowd bypass, which means that you don't have to wait when another person has already waited unless you've disabled this in the options.
