### ISSUE TITLE
It is not available in Spanish on Google Chrome

### ISSUE THREAD

**Issue by jcvr1994** [timmyrs/Universal-Bypass#121]
It is not available in Spanish on Google Chrome
No está disponible en español en Google Chrome

**Comment by timmyrs** [comment]
What do you mean "not available?" Is Chrome set to Spanish but Universal Bypass is English?

**Comment by jcvr1994** [comment]
Universal Bypass is in English

**Comment by jcvr1994** [comment]
Universal Bypass is in English
Universal Bypass está en inglés
