### ISSUE TITLE
SHORTE.ST (or maybe more) bypass fixing suggestion

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#122]
I recently found Universal-Bypass and thought of trying it out but I found that it doesn't work on SHORTE.ST . The previous bypasser I used before this one works perfectly there, so I thought I should suggest you take a look at this bypasser so that you could add those features in Universal-Bypass.

<a href="https://adsbypasser.github.io/">AdsBypasser</a> is a userscript so you'll need <a href="https://tampermonkey.net/">Tampermonkey</a> to use this. Hope you'll find more features there that you haven't added here yet than just SHORTE.ST's.

Example link : http://festyy.com/wHoMTI

**Comment by timmyrs** [comment]
I'm surprised they're still doing that, I thought they had switched entirely to their noriskdomain.com scheme. As it seems, it's not possible to bypass that though. Even AdsBypasser is just trying its luck to get a good response. What I can do is cut the waiting time, like AdsBypasser, which I have done.

**Comment by Cyberavater** [comment]
> What I can do is cut the waiting time, like AdsBypasser, which I have done.
You sure AdsBypasser is not working on example link? I tried again just to be sure and it worked (and was working all these time for me).

**Comment by timmyrs** [comment]
Just installed AdsBypasser, and it didn't even work, but I'll make Universal Bypass automatically redirect you in the next version.

**Comment by Cyberavater** [comment]
> I'll make Universal Bypass automatically redirect you in the next version.

It still doesn't click on "Skip This Ad" automatically.
