### ISSUE TITLE
Request: Adding a auto take to the page feature

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#124]
Example link: https://safelink.kadal.club/full/?api=3de2c74522de32d3ba9ba13640b84439a45294da&url=aHR0cDovL3RtZWFybi5jb20vYWxENkplRw==&type=2

Universal-Bypass says, 

> You might not have to wait!
Other Universal Bypass users have already waited for you and reported that this leads to http://tmearn.com/alD6JeG
Was this not correct?

Now, It would be nice if Universal-Bypass would directly take to the page instead of just suggesting it. Or, at least have an option by enabling which it would do that (or auto click on the link).

**Comment by timmyrs** [comment]
Sorry, I won't do that, because that's based on what users report and the users might be wrong, so that "Was this not correct?" link is essential for this feature.

**Comment by Cyberavater** [comment]
Oh, I see. then perhaps add an (experimental) option by enabling which it would do that (but will be disabled by default)?

**Comment by timmyrs** [comment]
Sorry, no, if you get taken to the wrong destination, you will not be able to correct this, which is why you get that page.
