### ISSUE TITLE
it does not work in https://wicr.me

### ISSUE THREAD

**Issue by jcvr1994** [timmyrs/Universal-Bypass#125]
it does not work at https://wicr.me it takes me to a blank page https://wicr.me/st?api=6a9fd0f7cb7d6edf48cb11a72e840245c73f0154

**Comment by timmyrs** [comment]
The link you provided takes me to a blank page with and without Universal Bypass enabled.

**Comment by jcvr1994** [comment]
here is the correct link take me to a blank page  http://mwpaste.com/u?u=http://mwpaste.com/?v=RQ

**Comment by timmyrs** [comment]
I just had to wait 22 seconds to verify it all works when Universal Bypass is disabled. Man the internet sucks.
