### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by tebriz159** [timmyrs/Universal-Bypass#127]
Hi, I am a logo designer and I can make a free logo for yor project if you want. Btw I'm using universal bypass for months, I think your proeject is awesome! So, what do you think about a new logo?

**Comment by timmyrs** [comment]
I like the current logo, but if you can give me something that I think looks good I might change it.

**Comment by tebriz159** [comment]
Sure, I have some logo design works after I'm done, I will desin a logo.

**Comment by timmyrs** [comment]
Any updates on this yet?
