### ISSUE TITLE
[Regression] Long snip.li redirect time

### ISSUE THREAD

**Issue by Aidolii** [timmyrs/Universal-Bypass#128]
Related to #97 & #123, a separate issue was unnecessary before, since the first time it was fixed, this was fixed along with it.

While it is redirecting to the MEGA link, it takes an unusually long time to get to that point, up to 10 seconds. 'Waiting for Universal Bypass...' is in the status bar during this.

**Comment by timmyrs** [comment]
That's just because snip.li takes a long time to respond.
