### ISSUE TITLE
Countdown bypass is not working.

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#131]
I remember many sites that force you to wait long time can be bypassed by Universal-Bypass. Now those sites have to wait like before, seems after last Universal Bypass update.
Example link:
https://douploads.com/rgt7w48ttoxw
https://rapidgator.net/file/9a384e03825948ef49fc0a3a5ad3c76d/

**Comment by timmyrs** [comment]
Also, I can't bypass rapidgator.net because they make sure you've waited 90 seconds.

**Comment by vungsung** [comment]
Is there any possibility to add them back and set them off on default, but add another option to toggle them? Because I found them useful. For example: Sites require you wait 90 secs, you can bypass waiting, and wait 15 secs, then press download, it works.

**Comment by vungsung** [comment]
Got it. rapidgator is totally unbypassable.

**Comment by vungsung** [comment]
The server-side doesn't really count that long. They just make sure you wait for first few seconds. That's why I think the bypass is useful.

**Comment by timmyrs** [comment]
I've added a bypass for douploads.com in Universal Bypass 9.4 though, so I'd instead like to add bypasses per-domain than to break too many sites. Also, I tried to fool rapidgator, but waiting ~45 seconds seems to be not enough, so I'm pretty sure they want you to wait the full 90 seconds, maybe 89 seconds if they're nice.
