### ISSUE TITLE
raidcall.com bypass is not working for some strange reasons.

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#134]
That's weird. The following codes should work:
```
brws.webRequest.onBeforeRequest.addListener(details=>{
	if(enabled)
	{
		return getRedirect(details.url.substr(details.url.indexOf("url=")+4))
	}
},{types:["main_frame"],urls:[
"*://*/st?api=*&url=*",
"*://*.zxro.com/u/*?url=*",
"*://*.raidcall.com.tw/direct.php?url=*",
"*://*.raidcall.com.tw/direct.tips.php?url=*"
]},["blocking"])
```

But when I access the following links:

http://www.raidcall.com.tw/direct.php?url=https%3a%2f%2funiversal-bypass.org%2f&uid=10589307&param=PzcKro1oqLiOkn9zL5ohphOvf6w5z%2b44fXnMYdHihDA7D7jzVf92dPWSFoN1l%2fRvq5Twez%2bxkOg%3d

https://raidcall.com.tw/direct.tips.php?url=https%3A%2F%2Funiversal-bypass.org%2F

It doesn't work. Is the regex comes with a wrong format or somewhere went wrong? I'll keep debuging but I think I should share it whit you first. Thanks!

**Comment by timmyrs** [comment]
The issue is that I had adjusted it for poorly encoded URLs, but raidcall.com.tw seems to be encoding URLs properly, so I'll have to separate it.
