### ISSUE TITLE
AutoHotkey Documentation 404

### ISSUE THREAD

**Issue by Aidolii** [timmyrs/Universal-Bypass#139]
This is a strange issue. The documentation website for AutoHotkey reports a 404 error in certain circumstances when Universal Bypass is enabled.

It doesn't always happen in pre-existing tabs, so to reliably replicate the bug, open a new tab and paste this in the URL bar: `https://autohotkey.com/docs/AutoHotkey.htm`

**Comment by timmyrs** [comment]
I'm not able to reliably replicate the bug, but it seems to be that the issue sometimes occurs when Universal Bypass & caching are enabled, so if it happens, pressing Ctrl.+F5 should resolve it. It might be another extension interfering with Universal Bypass.

**Comment by Aidolii** [comment]
This should more reliably replicate the bug https://lexikos.github.io/v2/docs/AutoHotkey.htm

**Comment by timmyrs** [comment]
I can't reproduce using only Universal Bypass. It could be due to another extension. Anyway, pressing Ctrl+F5 fixes the 404.

**Comment by Aidolii** [comment]
My apologies, it's a strange interaction Universal Bypass is having with ScriptSafe.
