### ISSUE TITLE
Fix Cpmlink.net Bypass

### ISSUE THREAD

**Issue by anonusers** [timmyrs/Universal-Bypass#140]
Example: http://cpmlink.net/glc_AA

**Comment by timmyrs** [comment]
I see no issues. What issue do you see?

**Comment by anonusers** [comment]
No redirect/bypass requiring manual input. Using Firefox Nightly with uBlock Origin/Nano Defender.
Tested with only bypass extension enabled and same thing.  What can I provide to help you resolve this? console log?

**Comment by timmyrs** [comment]
Yeah, I can't bypass a captcha for you.

**Comment by anonusers** [comment]
Sorry I'm not following. That link is from https://universal-bypass.org/example-links

**Comment by timmyrs** [comment]
Okay, I've replaced it with a new example link.

**Comment by anonusers** [comment]
Ah ok, weird because I tested this on another machine a few days ago using the same link and it redirected back to universal-bypass.org with captcha briefly showing . anyways thanks for your quick  response!
