### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by pipboy96** [timmyrs/Universal-Bypass#141]
Currently the code doesn't seem to be clearly written and have a uniform style. I will attempt to refactor it in a fork and then the authors are free to merge the code partially or completely.

**Comment by timmyrs** [comment]
Don't do that to yourself.

**Comment by pipboy96** [comment]
@timmyrs what?

**Comment by timmyrs** [comment]
The code is readable, and I don't have any consistent Javascript coding rules,; I what I feel looks best, which changes like every couple of weeks, so your efforts wouldn't be worth it.

**Comment by pipboy96** [comment]
@timmyrs https://www.youtube.com/watch?v=yO4myLCfN-Y
__And you don't seem to understand...__

**Comment by timmyrs** [comment]
If you're a masochist, go right ahead to refactoring, but understand that I might not accept your PR.

**Comment by pipboy96** [comment]
@timmyrs Haha, I love a challenge!

**Comment by timmyrs** [comment]
Code refactoring is not a challenge; it's just a tedious task.

**Comment by pipboy96** [comment]
@timmyrs It depends.
