### ISSUE TITLE
NoScript

### ISSUE THREAD

**Issue by sphh** [timmyrs/Universal-Bypass#142]
What settings do I need in NoScript to work together with Universal Bypass?

Could this be added to the FAQ?

**Comment by timmyrs** [comment]
I have no idea about NoScript configuration. Is it possible to whitelist an element with a given class on every website?

**Comment by pipboy96** [comment]
@timmyrs That would defeat NoScript's usefulness since any malicious script could use the same class.

**Comment by timmyrs** [comment]
Then Universal Bypass will stay incompatible.
