### ISSUE TITLE
Is there any protection against malicious contributions to crowd system?

### ISSUE THREAD

**Issue by pipboy96** [timmyrs/Universal-Bypass#143]
E.g. if I contribute https://g.co/kubecon with target url of http://goatse.cc/ **(NSFW!)**, will everyone be redirected to it?

**Comment by timmyrs** [comment]
The protection is that you are not automatically sent to the destination, and you can click "Was this not correct?" so you can yourself contribute the correct destination to the system.

**Comment by pipboy96** [comment]
@timmyrs How is an average user supposed to know if this destination is correct?

**Comment by timmyrs** [comment]
I assume the average user doesn't just click on links if they don't at least have some idea what lies at the other end of it.

**Comment by pipboy96** [comment]
@timmyrs They do that constantly.

**Comment by timmyrs** [comment]
If someone says "Download my software at shitty.link/bla" and crowd bypass says your destination is some site which doesn't look like a download site, then you know you're not in the right place.

**Comment by pipboy96** [comment]
@timmyrs Logical, but for most users logic is something they never heard of.

**Comment by timmyrs** [comment]
Well, the crowd bypass system has been in place for quite some time now, and I've heard no complaints so far.

**Comment by pipboy96** [comment]
@timmyrs This seems to be a variant of [appeal to tradition](https://en.wikipedia.org/wiki/Appeal_to_tradition).

**Comment by timmyrs** [comment]
It is not right because we've always done it that way, it's right because I've tested it, it works, and got no negative feedback.
