### ISSUE TITLE
Not work on shorte st

### ISSUE THREAD

**Issue by 3xploiton3** [timmyrs/Universal-Bypass#144]
http://viid.me/qcJTQz

**Comment by 3xploiton3** [comment]
use this instead https://chrome.google.com/webstore/detail/skip-shortest-ads/bhgkdnnlhmefhnkfilcaaibapeepkfok

if you can put script on that addon make more powerful,

**Comment by 3xploiton3** [comment]
more website

> http://linkpoi.in/G9wB1

**Comment by timmyrs** [comment]
The extension you've linked is long dead.
I don't see anything that needs to be bypassed on linkpoi.in.

**Comment by 3xploiton3** [comment]
its not dead

https://i.imgur.com/0FBGgb6.png

**Comment by timmyrs** [comment]
It's not working for me.
Also, do I understand correctly you just want Universal Bypass to press a button for you?

**Comment by 3xploiton3** [comment]
yes, i want universal bypass to press a button, 

extension in above work only viid.me,

**Comment by WaferNabati** [comment]
Bug linkpoi
https://linkpoi.in/JZlpm
https://linkpoi.in/TPzC0
https://linkpoi.in/3SaWx

**Comment by timmyRS** [comment]
@WaferNabati Do you really feel that Universal Bypass has to bypass a site where you have to press just a button? If so, please open a new issue.

**Comment by WaferNabati** [comment]
@timmyRS yes because many Universal Bypass users access that link
