### ISSUE TITLE
viid.me

### ISSUE THREAD

**Issue by 3xploiton3** [timmyrs/Universal-Bypass#146]
http://viid.me/qcJTQz

![image](https://user-images.githubusercontent.com/19517680/52959110-0b71e480-33c8-11e9-8b29-52306dfff99f.png)

**Comment by timmyrs** [comment]
Can't bypass browser verification.

**Comment by 3xploiton3** [comment]
http://viid.me/qriZTb
![image](https://user-images.githubusercontent.com/19517680/52960834-33634700-33cc-11e9-8aef-0b12a563e3b8.png)

**Comment by timmyrs** [comment]
?

**Comment by 3xploiton3** [comment]
when tried again its 
![image](https://user-images.githubusercontent.com/19517680/52962703-8a6b1b00-33d0-11e9-9ad0-b49fdd50c1bb.png)

next i verified recaptcha

then
![image](https://user-images.githubusercontent.com/19517680/52962864-f3eb2980-33d0-11e9-88d6-5b9f2af5a8f8.png)

can you bypass after recaptcha?

**Comment by timmyrs** [comment]
It should be bypassed. Are you using the latest version?

**Comment by 3xploiton3** [comment]
yes, version 9.6.5

**Comment by timmyrs** [comment]
What are your Universal Bypass options and which chrome version are you using?

**Comment by 3xploiton3** [comment]
https://i.imgur.com/HNLdG4V.png
https://i.imgur.com/QeuH8ZL.png

All check
latest version chrome

**Comment by timmyrs** [comment]
Shorte.st is weird. I can't reliably do anything.
