### ISSUE TITLE
Request http://gestyy.com

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#148]
http://gestyy.com/wBROoh
http://gestyy.com/wBROtV
http://gestyy.com/wBROsO

**Comment by timmyrs** [comment]
Shorte.st is already bypassed whenever possible.

**Comment by falfan2018** [comment]
@timmyrs 
stuck like this
(https://user-images.githubusercontent.com/9379770/53084082-b43c5300-3532-11e9-8057-3d58d010a8fb.png)

**Comment by timmyrs** [comment]
I can't bypass browser verification.
