### ISSUE TITLE
gsurl.in

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#158]
Example link: https://gsurl.in/capatcha/?i=yIq3

**Comment by timmyrs** [comment]
That link's giving me a 404

**Comment by Cyberavater** [comment]
Sorry, it was working when I posted it here. Anyway, New link: http://gsul.me/f3X6

**Comment by timmyrs** [comment]
The captcha is (obviously) not bypassed, but the timer is.

**Comment by Cyberavater** [comment]
My bad, it's working as it should be. Sorry for wasting your time. (Not sure why, but for me in chrome captcha was done automatically and I posted it here for adding click on continue automatically. But trying that link on firefox made me realize that captcha needs to be completed before clicking on continue. Anyway, thanks for the quick response.
