### ISSUE TITLE
Bypass Request cpmlink.net

### ISSUE THREAD

**Issue by ptorrejonbs2** [timmyrs/Universal-Bypass#159]
hey! 

First of all, thanks for an amazing extension! you guys are the best!.
So i was wonder if you could bypass cpmlink.net. here is an example link.

https://cpmlink.net/I4bdAA

If you guys can do it, it would be great.

Thanks!

**Comment by timmyrs** [comment]
The captcha is (obviously) not bypassed, but the timer is.
