### ISSUE TITLE
Fix https://bagilagi.com (anti bypass universal bypass)

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#160]
https://api.rurafs.me/v1/rurasafe/WWkzb1BIdHM4MHVzR1dOQnhVdHJMdVdqajhBU2R3OVc0cEsrNkQ5cUNIZTBYNmRCM3ZCNFB0Q0hXV29rTXlhczZrVFpOdTFiT2kra2ovV3RpbEs1dmc9PQ==?Key=09bac30e-fbb8-44b5-8dd6-f57f1461a8bc

https://api.rurafs.me/v1/rurasafe/WWkzb1BIdHM4MHVzR1dOQnhVdHJMdVdqajhBU2R3OVc0cEsrNkQ5cUNIY0p5ZkNKMDRKV3c3YWNRZnlVVFo4Y2ZZQXZ0dlZmSVhpbDFNenBlUkpMZ0E9PQ==?Key=09bac30e-fbb8-44b5-8dd6-f57f1461a8bc

https://api.rurafs.me/v1/rurasafe/WWkzb1BIdHM4MHVzR1dOQnhVdHJMdVdqajhBU2R3OVc0cEsrNkQ5cUNIZk1QamVQckVoQk1odXpMTmdBdmtVeEpSWGhsczlYdW5zTkNPMlhqNllocHBTM09oTmlHTGZrM3dXeDJoc09vWVk9?Key=09bac30e-fbb8-44b5-8dd6-f57f1461a8bc

example link : https://drivenime.com/non-non-biyori-movie-vacation-bd-subtitle-indonesia/ 
link googledrive
thanks

**Comment by falfan2018** [comment]
@timmyrs bagilagi.com still error and can't be bypassed please fix it thanks
![screenshot_2019-03-06 solusi biar kulit leher tidak belang-belang dan kusam - bagi lagi](https://user-images.githubusercontent.com/9379770/53878121-9e07ba00-403d-11e9-847e-2aaca811fc6c.png)
![screenshot_2019-03-06 solusi biar kulit leher tidak belang-belang dan kusam - bagi lagi 1](https://user-images.githubusercontent.com/9379770/53878145-b11a8a00-403d-11e9-83ee-677e67012aa6.png)
![screenshot_2019-03-06 non non biyori movie vacation bd subtitle indonesia - drivenime](https://user-images.githubusercontent.com/9379770/53878164-bf68a600-403d-11e9-9f12-46825365e8f2.png)

and please add bypass for https://api.rurafs.me/

**Comment by timmyrs** [comment]
What pathetic kids. For the time being, I'll prevent Universal Bypass from doing anything there, but I'll check back in a few days, to see if I can't bypass it anyway.

**Comment by timmyrs** [comment]
I just checked in with the site, and it seems dead/broken.
