### ISSUE TITLE
http://binbox.io

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#163]
Example Link: http://binbox.io/a09jK

Adsbypasser can bypass this; https://adsbypasser.github.io/

**Comment by timmyrs** [comment]
No, it can not.

**Comment by Cyberavater** [comment]
Have you actually tried it or are you just assuming it?
https://streamable.com/nuc9p

**Comment by timmyrs** [comment]
I looked at the site, and at the source code of Adsbypasser. Besides, how is anyone supposed to bypass a captcha? Captchas are meant for humans to prove they're human...

**Comment by Cyberavater** [comment]
Check here,
https://streamable.com/nuc9p
Or, actually try it maybe?

**Comment by Cyberavater** [comment]
Since Adsbypasser is open source, maybe add the "whole" Adsbypasser to Universal Bypasser as a sub-tool in that way It'll have all it's feature without knowing about them. Plus if U can make an automatic sub-tool update feature, Universal Bypasser will get every update that Adsbypasser will get.

**Comment by timmyrs** [comment]
I won't add adsbypasser into Universal Bypass.

**Comment by Cyberavater** [comment]
Understandable. Then if I'm to use both of them anyway, I guess this Issue doesn't need to solve.
