### ISSUE TITLE
Help to 100% bypass

### ISSUE THREAD

**Issue by nekudah** [timmyrs/Universal-Bypass#164]
enewstalk.com
$rtFly is the name I guess

https://punchsubs.net/download-openload/98549 example, go on this link and click in "baixar pelo openload" sometimes bypass it, other times don't

Thanks <3, I love this app !

**Comment by timmyrs** [comment]
I'm getting a 404 on the example link

**Comment by PoorPocketsMcNewHold** [comment]
Same goes for me. _(I do use some scripts and extensions that are present in the console errors)_ 
![image](https://user-images.githubusercontent.com/13170204/54082722-68ebb800-431a-11e9-92c5-3acabe5a4612.png)

**Comment by timmyrs** [comment]
That's great, but I was just asking @nekudah to provide a new link, or maybe where he got that link from.

**Comment by PoorPocketsMcNewHold** [comment]
Sorry then, I´ve wanted to show him maybe what was with this 404 error if if i never had that issue in the first place. 
The https://punchsubs.net domains is entirely dead right now anyway and all three saved pages in the Wayback Machine seems to show it the same,[ the fairest being from the beginning of 2018.](https://web.archive.org/web/*/https://punchsubs.net/)

**Comment by nekudah** [comment]
@timmyrs https://punchsubs.net/home is the site, from Brazil, maybe you guys get 404 error cz of some region block ?

https://enewstalk.com/YcqD14J this is the ad link to download, like I said earlier some episodes on the site (theres tons) pass others don't

sorry for the bad english =/

**Comment by PoorPocketsMcNewHold** [comment]
I can confirm about the possible region block. I´ve tested with different bridges, VPN servers, and proxies.

> Germany = Blocked.
> Russia = Blocked.
> United States = Blocked.
> France = Blocked.
> Austria = Blocked.
> Netherlands = Blocked.
> Canada = Blocked.

Until i try it with a Brazil proxy server : 
[https://iconious.com/pro/index2.php?u=85aabeb0a74eczovL3B1bmNoc3Vicy5uZXQvaG9tZQ%3D%3D&b=13&f=norefer](https://iconious.com/pro/) Works.
[https://brasilspeedhost.dtenhost.com/browse.php?u=https%3A%2F%2Fpunchsubs.net%2Fhome&b=24&f=norefer](https://brasilspeedhost.dtenhost.com/ ) Works
[http://www.testesuainternet.com.br/tsi/proxy/index.php?q=aHR0cHM6Ly9wdW5jaHN1YnMubmV0L2hvbWU%3D&hl=3ed](http://www.testesuainternet.com.br/tsi/proxy/) Timed out (But has correctly showed the html page title)

**Comment by nekudah** [comment]
@PoorPocketsMcNewHold  thanks, now let's wait and see what @timmyrs can do :godmode:

**Comment by timmyrs** [comment]
Bypassing the timer is easy, and that enewstalk.com site that comes after it is bypassed by crowd bypass, it's just that the server is currently running a RAID check, so it's taking ages to respond. .-.
