### ISSUE TITLE
Fix https://bagilagi.com (anti bypass universal bypass) #2

### ISSUE THREAD

**Issue by aiga0** [timmyrs/Universal-Bypass#166]
https://api.rurafs.me/v1/rurasafe/WWkzb1BIdHM4MHVzR1dOQnhVdHJMdVdqajhBU2R3OVc0cEsrNkQ5cUNIY3dKWmUzanNGUnc1WE1TWS9wLy82RkFVNGtJNUFGenJnS09ReERSKzhiWWc9PQ==?Key=09bac30e-fbb8-44b5-8dd6-f57f1461a8bc

https://api.rurafs.me/v1/rurasafe/WWkzb1BIdHM4MHVzR1dOQnhVdHJMdVdqajhBU2R3OVc0cEsrNkQ5cUNIZGJSTlBJa2ZqdjFwVUlSbWVFalpoS1dNZGxJeklRcTE5UktlSklVSlpQcFE9PQ==?Key=09bac30e-fbb8-44b5-8dd6-f57f1461a8bc

example link : https://drivenime.com/occulticnine-subtitle-indonesia-batch-3/
link googledrive
thanks

**Comment by timmyrs** [comment]
Site's broken with or without Universal Bypass.
