### ISSUE TITLE
pixiv.net

### ISSUE THREAD

**Issue by crse** [timmyrs/Universal-Bypass#169]
Example link: https://www.pixiv.net/jump.php?url=https%3A%2F%2Fcreseca.tumblr.com%2F

The link only available via Pixiv profile: https://www.pixiv.net/member.php?id=19557969

**Comment by timmyrs** [comment]
pixiv implements that as a security measure so you know you're leaving the site, to prevent possible phishing attacks. Besides, having Universal Bypass simply click a link would be a really benign bypass.
