### ISSUE TITLE
[Site Request] mykinggo.com

### ISSUE THREAD

**Issue by dnlzzxz** [timmyrs/Universal-Bypass#174]
Hello, that's my first time here and I'd like to give you a huge thanks for the extension, it is super useful and saves me a lot of time! 

Also, I'd like to ask, if possible, to add support for http://mykinggo.com.

Sample link: http://mykinggo.com/DB8wTsY7

**Comment by timmyrs** [comment]
That site is bypassed using crowd bypass, which means you don't have to wait if someone else already has.
