### ISSUE TITLE
Add support for https://getfreshcloud.xyz

### ISSUE THREAD

**Issue by fakhar149** [timmyrs/Universal-Bypass#176]
When visiting https://getfreshcloud.xyz site shows a countdown, after countdown ends a button to go further disappears due to website bypass option in  this extension.Please add blacklist this site option or bypass this site.
![Screenshot (6)](https://user-images.githubusercontent.com/23151542/55215963-ad9b9e00-51b8-11e9-8a45-dda015da1797.png)
![Screenshot (5)](https://user-images.githubusercontent.com/23151542/55215965-ad9b9e00-51b8-11e9-8763-11e9815c0d40.png)

**Comment by timmyrs** [comment]
This website works fine for me. You're probably using another extension which could be causing issues.

**Comment by fakhar149** [comment]
Let me send you some screenshots, you can check them.with green button pic when I disabled website bypass in extension and without green button pic when I enabled website bypass.

Sent from Mail for Windows 10
