### ISSUE TITLE
[Bug] shrink.vip

### ISSUE THREAD

**Issue by surya27895** [timmyrs/Universal-Bypass#178]
it bring to wrong destination
[https://www.shrink.vip/0yNm2J](https://www.shrink.vip/0yNm2J)

**Comment by timmyrs** [comment]
What is the correct destination?

**Comment by surya27895** [comment]
here
[https://mirrorace.com/m/4Ts8z](https://mirrorace.com/m/4Ts8z)

**Comment by timmyrs** [comment]
I just fixed an issue introduced in Chrome 63, and it looks like this link is now also bypassed again.
