### ISSUE TITLE
Support https://outgoing.prod.mozaws.net/

### ISSUE THREAD

**Issue by XCanG** [timmyrs/Universal-Bypass#180]
For example any URL on https://addons.mozilla.org/ addon's page followed through this website

Even on this addon's page:
`https://outgoing.prod.mozaws.net/v1/0425c7205a5d150cb23629b572bf4238916a841388eebd48baa88dfdfd49d864/https%3A//universal-bypass.org/`

**Comment by timmyrs** [comment]
There is nothing to be bypassed here, and Mozilla does this for security.
