### ISSUE TITLE
Open new tab instead of new window after installing

### ISSUE THREAD

**Issue by csalles1** [timmyrs/Universal-Bypass#183]
After installing the extension it opens a new browser window. And it's kinda annoying.

Could you open a new tab instead?

**Comment by timmyrs** [comment]
I think there was some issue with opening a tab instead of a window, and every browser handles it kind of differently. I'll check if anything's changed since then when I have the time.

**Comment by timmyrs** [comment]
So, I've just checked it out, and Firefox doesn't allow opening a new tab, so opening a window is the only thing I can do to make the firstrun page work there unless I'm missing something.

**Comment by 3xploitzer0** [comment]
can u make option to instanly redirect to page?

without left over new tab
