### ISSUE TITLE
Safelinku not working

### ISSUE THREAD

**Issue by pYbiz** [timmyrs/Universal-Bypass#186]
http://miui.space/hH8uK

**Comment by timmyrs** [comment]
This site is bypassed using crowd bypass, which means you don't have to wait if someone else has already waited.

**Comment by pYbiz** [comment]
> This site is bypassed using crowd bypass, which means you don't have to wait if someone else has already waited.

What do you mean?

**Comment by timmyrs** [comment]
![image](https://user-images.githubusercontent.com/11009697/56736482-88269380-6768-11e9-82b3-0ce930a2fdc0.png)
