### ISSUE TITLE
[Site Request] dunyanews.xyz

### ISSUE THREAD

**Issue by hjyoung1** [timmyrs/Universal-Bypass#187]
Thanks for making this amazing tool.
I want to request this clickfly clone website for bypass. 
Sample link :- http://dunyanews.xyz/hiLllY
Link destination :- example.com

Main website behind this is 
http://voxc.org

**Comment by timmyrs** [comment]
This is bypassed by crowd bypass, which means you don't have to wait if someone else has already waited.
