### ISSUE TITLE
Allow user to verify destination before loading it

### ISSUE THREAD

**Issue by Gitoffthelawn** [timmyrs/Universal-Bypass#189]
One of the big problems with link shorteners is that they can send you anywhere, including malicious sites.

Can you add an option to Universal-Bypass so that the user can see the destination before it is loaded, and only go to the destination upon user approval?

**Comment by timmyrs** [comment]
That's the default behaviour:
![image](https://user-images.githubusercontent.com/11009697/56847802-b7601080-68e0-11e9-9630-7a05872b9760.png)

**Comment by Gitoffthelawn** [comment]
I have that unchecked, but it still instantly takes me to destinations.

Firefox 63.0.3.

**Comment by timmyrs** [comment]
It could be that if you have uBlock Origin it bypasses adf.ly faster than Universal Bypass. Otherwise, it works for me in Firefox.

**Comment by Gitoffthelawn** [comment]
Strange.  I tested Universal Bypass in a new Firefox 63.0.3 profile, with no other extensions installed, by going to https://universal-bypass.org/example-links and clicking on the bit.ly link.  It immediately goes to https://universal-bypass.org/ without any user interaction.  Note that I tested with bit.ly and not adf.ly (your response mentioned adf.ly).

BTW, I looked at uBlock Origin in a different test profile, and I don't see any options to call short-url resolvers to bypass short urls.  Can you elaborate on how uBlock Origin bypasses short urls?  I could see it completely blocking short url's, but then the user would receive a page indicating that the page was blocked.

**Comment by timmyrs** [comment]
Well, since bit.ly is _only_ a tracker, I thought it would be asinine to make this visit take longer than if you wouldn't use Universal Bypass. Although, since the option is called "instantly take me to destinations" you would assume it would also affect trackers.
