### ISSUE TITLE
clicksfly is not workin

### ISSUE THREAD

**Issue by manofsteel2017** [timmyrs/Universal-Bypass#191]
can you guys have a loook?
one annoying site

**Comment by timmyrs** [comment]
Could you provide an example link?

**Comment by PBJF** [comment]
It is semi-working. You have to solve the captcha, but then it goes auto.

**Comment by timmyRS** [comment]
1. Universal Bypass can't bypass CAPTCHAs, because it's not a human.
2. fc.lc is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
