### ISSUE TITLE
Soralink Template

### ISSUE THREAD

**Issue by alvahn** [timmyRS/Universal-Bypass#193]
`https://movieku.org/replicas-subtitle-indonesia/`

**Comment by timmyrs** [comment]
That `api.rurafs.me` family of sites has some weird detection with a lot of backend components, which detects Universal Bypass and other extensions and userscripts even if they don't bypass the site. I'll keep this open but I don't expect to be able to bypass it anytime soon.

**Comment by timmyrs** [comment]
I'm still trying to find out which cipher they're using to encrypt the destination. Here's some data I've gathered for anyone that wants to have a try:

```
Lyc9B7LME2J2ZsmebZUPYUQJ3Z4zLzrgs/RIq1/dGeNToCx8RSfB3FXTlQHMyLblBZwqOTBZQe8bCbTaWuzvRxHr7de7TkqLDrzBSlVVrQAZGL141wFvWB105XrG6nSv
https://drive.google.com/file/d/1OWBEOLuiNIMnlhare_bR0DPtxMXaGfoE/view?usp=drive_web

Lyc9B7LME2J2ZsmebZUPYUQJ3Z4zLzrgs/RIq1/dGeP0eAJ/7OcQgCXjTDAWgg1beLNX/INjyUA/WskD13OnEZu/Qff/nh+bQB9VTYLZ808ZGL141wFvWB105XrG6nSv
https://drive.google.com/file/d/16rgofBM9v5ygJy3Cd-0J37y__F6J6g_q/view?usp=drive_web

pGs370rypkraYzzHv5yAcQSmAcwyvILY9ZG4fup9JNyVAfibjNFHB3Bbio1WPx1X
https://sharer.pw/file/qDD-UiB8NVU

pGs370rypkraYzzHv5yAcWHJTiS89HbST/arZgaaZgskXkqH+2U4nttQzynj73Z/
https://sharer.pw/file/M66QINfZXoc
```

Potential encryption key: d81834a3-cfa7-424b-bdd9-e6f13ac39900

**Comment by timmyrs** [comment]
technlab.com (from #196)
```
b1A3MnFWOHI1eEZtT1U2L1NoaVJ5cGF2UWtlUUlHTjRhVnlucEtOT2hQYTNYOXcrY3FkNUllTk5WOEduUXNldld0Zm1nZjNvVUNJdnpyL09LRVpKcnRuc2ErdUxYQTZqMmMxU1lROTdHU2c9 
https://drive.google.com/file/d/1VJqT-d5XcTNmc067zff911UXJdChu4Eh/view?usp=drive_web
```

**Comment by timmyrs** [comment]
apasih.pw (from #230)
```
a1NobVhjdlBzd2lucDN3OTN0V2l5dUJ5UlVaUzNFZ1V2Zk9NODNtS3JzTFdQMklSY1A0bXpwdkdKZ1hzU2dNYndtOXVzeVhveEsrNGo1WHc3NkJiUEFBMXFLcmxwODVqYnFpN3JlZENoZk5kWllkUm9HNXZXVDhsMTRzNVAxOHQ=
https://drive.google.com/file/d/1F9wQsU2a1AGOy3bcof_e-BtLQih-54Nx/view?usp=drive_web
```

**Comment by vungsung** [comment]
The first part I've noticed, the AdsBypasser userscript results in being detected by that site. After disabled AdsBypasser, the site leads me into Google Drive.

**Comment by timmyrs** [comment]
sehatsegar.net (from #266)
```
QW03bzhWS1N6K2xUbEQwL1g2WFhiNk1va2RvTzdna282dUZyMDR2SThpa0RzbG5hTDE5dGJzUHpTUUlZRUk1a2Z4dGRwQjhiZEM3ODFYMzVZVmp2MVVOY3ZhYXZMRWVwcHVIVko1Z1VlcVk9
https://drive.google.com/file/d/1XWG2FsJj3KPt6XYmLh098rEZBRX8YmPW/view?usp=drive_web
```

**Comment by timmyrs** [comment]
landscapenature.pw (from #312)
```
T1p3S3pVRWRQZ1JRblY1VWJ3VFJxcjVvOGloWTYyOThTbGdReGtWZXhZYz0=
https://mirrorace.com/m/3zH22
```

**Comment by RaveN0X87** [comment]
@timmyrs this script can bypass landscapenature.pw linkach.com sehatsegar.net lonelymoon.net intercelestial.com sweetlantern.com safelink
https://github.com/adsbypasser/adsbypasser/commit/ee76ccbe2fe326e70f6c11d410525f733a73a209
https://github.com/adsbypasser/adsbypasser/commit/53dd2d8df642317f090f65d30045f249d8b085ca
hope you can fix and add to universal bypass

**Comment by timmyrs** [comment]
That's hardly a bypass.

**Comment by anaklayangan** [comment]
Suggestion for `api.rurafs.me` family
`
let openSelf=window.open
window.open=theLink=>openSelf(theLink,"_self")
setTimeout(()=>{document.querySelector("a[href='#generate']").click()},500)
setTimeout(()=>{document.querySelector("#showlink").click()},1000)
`
setTimeout is for XHR time delay https://api.rurafs.me/v2/clients when the element is clicked

**Comment by timmyRS** [comment]
Your bypass does seem to avoid the wait on that safelink site, but it still fails later down the line, ultimately not resulting in the target link.

**Comment by timmyRS** [comment]
However, even without any extensions, I don't seem to be able to get to the destination.

**Comment by timmyRS** [comment]
I suppose I'll add your bypass, close this issue, publish a new release, and see what sort of feedback I get. ¯\_(ツ)_/¯

**Comment by anaklayangan** [comment]
`api.rurafs.me` a.k.a `ChikaRuraSafe` sites works well, but `soralink` sites doesn't, because `soralink` use hidden recaptcha.

**Comment by timmyRS** [comment]
There's plenty of sites using this, surely there must be a template they all just use, so if we could get a hand on that, that might be useful.

**Comment by 0x6c4bf2e1** [comment]
The template name is soralink v3.0.4

**Comment by timmyRS** [comment]
I managed to find a zip of it: [SLV304.zip](https://github.com/timmyRS/Universal-Bypass/files/3564496/SLV304.zip)
However, the PHP code seems to have been "compiled" and obfuscated by ionCube.

**Comment by RaveN0X87** [comment]
`https://kb.themesia.com/docs/soralink/cara-install-dan-konfigurasi-soralink/`
this is a guide to install and configure soralink in Indonesian language from the official web of soralink owner
hopefully can help to bypass those shit

**Comment by timmyRS** [comment]
That's interesting, so you configure a Secret Key per instance. That is useful to know, but I'd still need to know which cryptographic operations are happening exactly, which is hard to find out, given that the code is obfuscated.

**Comment by RaveN0X87** [comment]
I want to help more but unfortunately I'm not a programmer.

**Comment by cferuprasanca** [comment]
teknoku.me safelink

**Comment by cferuprasanca** [comment]
Request bagilagi.com safelink

**Comment by ramenBoyz** [comment]
request travellinginfos.com bagilagi.com sweetlantern.com

**Comment by Chaborz** [comment]
cutlinks.pro stopped working

cutlinks.pro/adskipper.php (You have installed the extension "adskipper", please disabled for get link.)

**Comment by cesesa9442** [comment]
Hello,
Please add 

http://shorten.sh

Thanks

**Comment by timmyRS** [comment]
(Hopefully, this issue is now closed for real. Thanks very much to @ikancupang for not only telling me to get my act together and make it a crowd bypass but already writing functional code for it!)

**Comment by WaferNabati** [comment]
@timmyRS @ikancupang update soralink blocked

**Comment by WaferNabati** [comment]
another sample
`https://soraclient.themesia.com/standalone/`

**Comment by WaferNabati** [comment]
crowd bypass can't capture the real link because every visitor link ID is different
I've accessed the example link above many times but always say "you're the first to encounter this link"

**Comment by timmyRS** [comment]
It worked with `https://soraclient.themesia.com/standalone/`, so maybe it's just a thing with pahe.in?

**Comment by WaferNabati** [comment]
@timmyRS  `https://soraclient.themesia.com/standalone/` script for non-WordPress

**Comment by timmyRS** [comment]
Do you have any other example of that behaviour on a not-pahe.in site?

**Comment by WaferNabati** [comment]
it looks like other websites haven't updated the latest version of soralink but in the next few days they will definitely update it

**Comment by timmyRS** [comment]
I have a fix for pahe.in which I don't quite like but I'm gonna release it and see what breaks.

**Comment by WaferNabati** [comment]
it breaks crowd bypass for old soralink version

**Comment by its4win** [comment]
![image](https://user-images.githubusercontent.com/58930060/71709541-59e67100-2e2a-11ea-998a-0dcccd69470c.png)

Request to bypass this
https://kontenajaib.xyz/?id=T0g4OVRBaDBpektNcjltb0Q5UUxPa3RNSDlaTmZNZytqdHJLVU9kUm1DREVtaWZxMG01U00raC91OGhwN1VraEo5T1lvN3ZMc20rSkJsK2d2KzREc0VCYmNpR2hybUFsMlJ3MGdUUWtuTzlXMEx0d29oWlo2LzVlcmZBSTRGdWVZY3MrVnRjUzVvbm5PaHhPalVabEptdGxWTHcxUFVYKzMzM243TU1LZlBHaHMrTWZ2Y1hGWnRtYWlrWFJRRE1VcVoyNFZwRkIrZHpQMGtOQS9RRkdEZHpNSVhRNnQwVVJaeFArQ0c4djZEcVZKejlOZVB3bUUxWG1Kc1ViN0lLTg==

Thanks
