### ISSUE TITLE
Request technlab.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyrs/Universal-Bypass#196]
http://technlab.com/?id=b1A3MnFWOHI1eEZtT1U2L1NoaVJ5cGF2UWtlUUlHTjRhVnlucEtOT2hQYTNYOXcrY3FkNUllTk5WOEduUXNldld0Zm1nZjNvVUNJdnpyL09LRVpKcnRuc2ErdUxYQTZqMmMxU1lROTdHU2c9

**Comment by timmyrs** [comment]
I'm not sure which cipher is used to encrypt the destination. However, that example link with the ciphertext of `b1A3MnFWOHI1eEZtT1U2L1NoaVJ5cGF2UWtlUUlHTjRhVnlucEtOT2hQYTNYOXcrY3FkNUllTk5WOEduUXNldld0Zm1nZjNvVUNJdnpyL09LRVpKcnRuc2ErdUxYQTZqMmMxU1lROTdHU2c9` leads to `https://drive.google.com/file/d/1VJqT-d5XcTNmc067zff911UXJdChu4Eh/view?usp=drive_web`

This could potentially be the same cipher as with #193

**Comment by timmyrs** [comment]
Duplicate of #193.
