### ISSUE TITLE
[Request] uii.io & short.pe

### ISSUE THREAD

**Issue by version365** [timmyrs/Universal-Bypass#198]
`https://uii.io/o86F7`

`https://short.pe/cs9dV`

**Comment by timmyrs** [comment]
They're both already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on them.

**Comment by version365** [comment]
Oh! Do you have a list of sites that are unbypassble & therefore only crowd bypassed?

**Comment by timmyrs** [comment]
Unfortunately, no, since these sites just use a template. The best way to find out is to just go through the whole process and then open the link again.
