### ISSUE TITLE
[Request] wikiall.org

### ISSUE THREAD

**Issue by version365** [timmyrs/Universal-Bypass#199]
Please add this site..

For it to open first you have go through wi.cr (example `http://wi.cr/2aGdTZv5E`); then this wikiall.org opens.. No permanent path is used, it's random.. (like this `https://wikiall.org/the-foxhound-dog/`)
Opening the wikiall.org link first doesn't give you target link, it's just a normal site.

**Comment by timmyrs** [comment]
Your wi.cr link puts me at a normal AdLinkFly page, nothing like you described.

**Comment by version365** [comment]
Here are some other wi.cr links..
`http://wicr.me/xTGX`
`http://wicr.me/LPrNJaQyj3`
`http://wi.cr/TEUXsHOo3H`

**Comment by timmyrs** [comment]
Still normal AdLinkFly... even an unconfigured one, which means it's actually bypassed :D

**Comment by version365** [comment]
That's pretty strange.. Can you please go to the homepage (wi.cr) and create a shortlink? Then try that link..

**Comment by version365** [comment]
Okay, I think some other extension is causing my problem.. let me check one by one..

**Comment by version365** [comment]
Got it.. a userscript was causing the problem.. sorry for the trouble..
