### ISSUE TITLE
[Request] Bypass 

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#205]
Example Link : https://sweetlantern.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzZmZJOXhtZGRjd2hNU0xIMUdSRHRpVT0=

https://intercelestial.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzY1V5Mkh5WUExd0RJMlZ1N0ZyeDlXQT0=

From : https://pahe.in/game-of-thrones-season-8/

**Comment by timmyrs** [comment]
Duplicate of #193
