### ISSUE TITLE
[Feature Request] Crowd bypass direct

### ISSUE THREAD

**Issue by hjyoung1** [timmyrs/Universal-Bypass#206]
![_20190506_110704](https://user-images.githubusercontent.com/45882061/57208551-f9303b80-6ff1-11e9-93e7-cc6c5b53b6b1.JPG)
Adding another setting like this for crowd bypass sites.

**Comment by timmyrs** [comment]
Crowd bypass is not guaranteed to be correct, so instantly taking you to these destinations would be a mistake.

**Comment by hjyoung1** [comment]
Why not let users decide that?
Even with normal links which bypassed automatically (non crowd bypass) they have same risk of leading to malicious/spam websites.

**Comment by timmyrs** [comment]
Yeah, but in that case the malicious/spam website is either your destination or there is a bug. However, with crowd bypass, a 50% attack could lead you to the wrong destination.

**Comment by Cyberavater** [comment]
Still, I haven't found any wrong bypass from the crowd bypass. So, I'd also vote for this feature {People clicks the link suggested by universal-bypass anyway (even if the destination is a malicious/spam)}.

**Comment by timmyrs** [comment]
The ability to click "Was this not correct?" is very important as sometimes the short link gets updated with a new target, or someone could have maliciously placed a wrong target via a 50% attack, and if you were instantly redirected there's no way to tell Universal Bypass that it gave you the wrong destination. If you're willing to do something fancy for that, feel free to submit a PR.

**Comment by Cyberavater** [comment]
I get it. Today I'm just being lucky! I found a wrong bypass just a few moments ago. :)

**Comment by Cyberavater** [comment]
Example Link: https://lkop.me/wZlQUoQ
