### ISSUE TITLE
[Request] filecrypt.cc

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#208]
Example Link: https://filecrypt.cc/Container/B3D654FCEE.html
P.S. You need to clear cookies every time you want to reproduce the verification-test.

**Comment by timmyrs** [comment]
What exactly is there to be bypassed?

**Comment by Cyberavater** [comment]
Verification-test?

**Comment by timmyrs** [comment]
That's a captcha.
