### ISSUE TITLE
Please Fix error and include new shorteners

### ISSUE THREAD

**Issue by MaklausJonhson** [timmyrs/Universal-Bypass#212]
Hello, the first of all is to congratulate and thank for universal-bypass is one of the best products I've ever tried, the reason for this communication is to inform you that there are some errors, for the shortener "https://cpmlink.net" is not working , it does not work, and I ask you to please repair this, I also ask you to include many more new shorteners that are appearing, such as https://shrtfly.com, I will be informing to you of more shorteners to include as I work more with your product and continue testing thousands of sites.

Thank you from my heart and I send you a big hug.

**Comment by version365** [comment]
The two websites you mentioned, those are not currently bypassable & only done by crowd-bypassing (i.e. if someone with UniBy has already passed it, you don't have to wait.)
