### ISSUE TITLE
safelinking please

### ISSUE THREAD

**Issue by ZeroCool22** [timmyrs/Universal-Bypass#214]
http://zlpaste.net/anomizador/l?hs=nUE0pUZyZ0RyZxLyZxMmLJMyoTyhn2yhMl5hMKDyZxMMImIiZIca

**Comment by timmyrs** [comment]
I can't bypass captchas. Also, I'm not sure if `nUE0pUZyZ0RyZxLyZxMmLJMyoTyhn2yhMl5hMKDyZxMMImIiZIca` contains any useful information. If it does, it somehow has to decipher to `http://bit.ly/2DUsxlm`, and I was unable to find a working cipher combo using cipherfinder.
