### ISSUE TITLE
Request bypass

### ISSUE THREAD

**Issue by xorcan** [timmyrs/Universal-Bypass#215]
https://is.gd/
https://v.gd/

**Comment by timmyrs** [comment]
Could you provide example links?

**Comment by bogachenko** [comment]
`https://v.gd/ddwyMm` its google.com
@timmyrs 
***
I don't really know what's wrong with the site. usual site

**Comment by timmyrs** [comment]
Yeah, both just seem like normal shortened links. I don't see any reason to _bypass_ them.
