### ISSUE TITLE
[Request] virtualdata.me

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#222]
Example link :
https://virtualdata.me/8UCtWk1
https://virtualdata.me/XXiy3Biyt
https://virtualdata.me/yaT6qH

**Comment by hjyoung1** [comment]
Site is already bypassed using crowd bypass. You don't have to wait if someone else has already waited. 
![Screenshot_20190514-011920](https://user-images.githubusercontent.com/45882061/57649713-90932100-75e6-11e9-90d4-f0c9dd83990c.png)
