### ISSUE TITLE
Request Alternative of Shorte.st bypass

### ISSUE THREAD

**Issue by azraei97** [timmyrs/Universal-Bypass#229]
Please add support site gestyy.com and ceesty.com that use Shorte.st

**Comment by bogachenko** [comment]
full link?

**Comment by azraei97** [comment]
http://corneey.com/wsKn1b and http://gestyy.com/wMzibA

**Comment by bogachenko** [comment]
wait for the authors of this script. and for the future, always publish links for example. each new issue begins with a question and "you have links for example?"
