### ISSUE TITLE
Request sivitechno.com

### ISSUE THREAD

**Issue by adctea** [timmyrs/Universal-Bypass#231]
Hello,the addon isn't working on http://sivitechno.com/oNpXEepQ ,could you help me out please?

**Comment by bogachenko** [comment]
read this #213

**Comment by adctea** [comment]
Ok,but what about the rest of the url's that have the same link/website?Should I manually click them/solve them?

**Comment by timmyrs** [comment]
This site is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
