### ISSUE TITLE
Request www.njiir.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#233]
https://www.njiir.com/p/geotechnical-mapping-of-underground.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDdSY3olNjBHQWpDJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMUVfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D
https://www.njiir.com/p/stress-measurements-using-oriented-core.html?url=IyNyWXklNUNPJTFGS0liY28lMUJYYiUwNWF%2BJTdDWXJQJTdCeSU2MHFsTm0lMUVlZkklMTklMTVMQSUxN0ZNWEclMDdFR0slMDZNRE9HR08lMDZNJTVFQVpMJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://www.njiir.com/p/factors-controlling-stope-wall-behavior.html?url=IyMlNUVDRSUwNn4lN0MlMDYlN0RjaWxpJTYwbWVpJTdCJTA1WCUxOCUxMCUxOCUxOSUwNSUxRCUxMCUxMCUwNXhnJTA3aiUxMSU1Q2UlMUElMDclNUNNRiUwNlglNURJT01FJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://www.njiir.com/p/stress-measurements-using-oriented-core.html?url=IyMlNUVDRSUwNn4lN0MlMDYlN0RjaWxpJTYwbWVpJTdCJTA1WCUxOCUxQSUxRiUwNSUxRCUxMCUxMCUwNXhnJTA3XyUxMSU1Q2UlMUElMDclNUNNRiUwNlglNURJT01FJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://www.tetew.info/njir/ORxAQ
https://www.tetew.info/njir/NsFDM

**Comment by timmyrs** [comment]
That's already bypasssed for me.

**Comment by Cyberavater** [comment]
Click all of them some of them aren't working here.
