### ISSUE TITLE
[Request] htps://maranhesduve.club/

### ISSUE THREAD

**Issue by jcvr1994** [timmyrs/Universal-Bypass#235]
https://maranhesduve.club/?tag_id=759228&sub_id1=8456763&sub_id2=5386691501216916817&cookie_id=1b4fba43-dc0b-460d-91d6-42eaf3707de4&lp=adfly_allow&convert=Your%20Video%20Is%20Ready%20To%20Stream&allb=redirect&ob=redirect&href=https%3A%2F%2Fadsrt.me%2FsH2QZ0OY&hop=3

**Comment by timmyrs** [comment]
This is already bypassed for me.

**Comment by jcvr1994** [comment]
![universal bypass](https://user-images.githubusercontent.com/43253672/58137520-2dae1500-7bf8-11e9-988f-577faa663675.jpg)
