### ISSUE TITLE
Request barista.io (Tracking domain barista.us2.list-manage.com)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [timmyrs/Universal-Bypass#241]
https://barista.us2.list-manage.com/track/click?u=804d494a19a5b8c6d7dbff1ae&id=1d35040dd9&e=816d6ac5d9

https://arstechnica.com/information-technology/2019/05/deepfakes-are-getting-better-but-theyre-still-easy-to-spot/

A tad more difficult now.	
Forgot to say, Thanks for your extension, It's had been a time saver for so many times for me.

**Comment by timmyrs** [comment]
This is way too specific. I would add a tracker bypass for `*.list-manage.com/track/*`

**Comment by timmyrs** [comment]
Actually, I think this would be quite a useless tracker bypass, since it doesn't matter which IP address clicks the link, they still know that you have clicked the link in the email, which is all they care about.
