### ISSUE TITLE
Req www.njiir.com

### ISSUE THREAD

**Issue by aiga0** [timmyrs/Universal-Bypass#246]
https://www.njiir.com/p/geotechnical-mapping-of-underground.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDdPUE1keWclMUNQJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMTAlMUNfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D

From 

https://www.tetew.info/njir/VNwzd

**Comment by bogachenko** [comment]
Duplicate? https://github.com/timmyrs/Universal-Bypass/issues/233

**Comment by timmyrs** [comment]
Where is your example link supposed to go to? I don't get any further than njiir.com with and without Universal Bypass.

**Comment by Cyberavater** [comment]
@timmyrs The destination link is; https://www48.zippyshare.com/v/x4OQLexg/file.html

You'll need to click on *Visit Link* to go there.

**Comment by timmyrs** [comment]
I don't see a "Visit Link."

**Comment by Cyberavater** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/32187927/58707374-8c347980-83d6-11e9-9318-7c343ad7f128.png)

**Comment by bogachenko** [comment]
> 
> 
> @timmyrs The destination link is; https://www48.zippyshare.com/v/x4OQLexg/file.html
> 
> You'll need to click on _Visit Link_ to go there.

you gave this link. what is meant on this page will the "Visit link"

**Comment by Cyberavater** [comment]
> @Cyberavater you gave this link. Eh. What is meant on this page will a "Visit link".

@bogachenko Can you please rephrase what you meant? I'm not getting you.

**Comment by timmyrs** [comment]
Are you on the same link as me?
![image](https://user-images.githubusercontent.com/11009697/58707949-a3636f00-83b6-11e9-8289-1f0a3bd1477d.png)
I even disabled adblock.

**Comment by Cyberavater** [comment]
Might be something with IP address. Can you try using a VPN?

**Comment by timmyrs** [comment]
Which country?

**Comment by bogachenko** [comment]
> 
> 
> > @Cyberavater you gave this link. Eh. What is meant on this page will a "Visit link".
> 
> @bogachenko Can you please rephrase what you meant? I'm not getting you.

fuck. my mistake. I misunderstood you. I wrote nonsense

***



> 
> 
> Are you on the same link as me?
> ![image](https://user-images.githubusercontent.com/11009697/58707949-a3636f00-83b6-11e9-8289-1f0a3bd1477d.png)
> I even disabled adblock.

try another browser or delete cache

**Comment by Cyberavater** [comment]
The U.S. is working for me.

**Comment by falfan2018** [comment]
@timmyrs i think because adblock or something like that

**Comment by timmyrs** [comment]
I tried using a U.S. VPN, disabled all adblocking extensions, I still don't see any button on njiir.com.

**Comment by bogachenko** [comment]
Have you tried another browser?

PS: I can throw off the saved page with "Visit link"

**Comment by timmyrs** [comment]
Ideally, I'd like to determine how `IyNERSU1QyU0MCUwNk1EQU4lMDdPUE1keWclMUNQJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMTAlMUNfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D` turns into `https://www48.zippyshare.com/v/x4OQLexg/file.html`

I do see cryptojs in the source, so maybe it's a symetrical cipher. The source code (should a working version of it even exist :laughing:) should reveal the secret, but I'm afraid it'll be obfuscated.

**Comment by vungsung** [comment]
We can simply redirect page to `$( '.result a' ).href`.
There are embedded crpto.js decrypting API and obfuscated call function as timmyrs said. I've tried capturing the packets, and I'm sure the decryption operation is done by those javascript offline. Unfortunately, I know nothing on reverse engining obfuscated javascript.
