### ISSUE TITLE
[Request] UploadHaven

### ISSUE THREAD

**Issue by mich3lam** [timmyrs/Universal-Bypass#247]
Hey guys, was thinking what are the chances to make a bypass for UploadHaven?

https://uploadhaven.com/download/1be75ffe352338663760a61e25a9ec93

For example.

thanks

**Comment by timmyrs** [comment]
I don't understand what there is to be bypassed.

**Comment by mich3lam** [comment]
I have 5/10/15 seconds waiting time before I can click the Download

**Comment by mich3lam** [comment]
I have 5/10/15 seconds wait time before I can click the download buttob

**Comment by bogachenko** [comment]
@timmyrs  there popup and cooldown to download

**Comment by uploadhaven** [comment]
This bypass is breaking the website, since the countdown is accelerated the user submits the form too early, resulting in an expired session.

**Comment by timmyrs** [comment]
@uploadhaven that issue was fixed in Universal Bypass 10.30 as per #252
