### ISSUE TITLE
[Request] Sdarot

### ISSUE THREAD

**Issue by mich3lam** [timmyrs/Universal-Bypass#248]
Hi again! Thanks for all the effort everybody puts into this addon, I love it. I have another request if possible.

There is a site called sdarot which it's address is https://sdarot.**rocks**, right now it's **rocks** but it's subject to change from time to time so if anyone makes the bypass it would be amazing to just make it .* or whatever, no idea how it works haha.

Anyhow, when you go to watch an episode there is 30 seconds waiting time.
For example: 
https://sdarot.rocks/watch/4566

After you pick the season/episode you want below, it will tell you to wait 30 seconds before you can continue. I would like it if anyone manages to bypass that time, thanks

**Comment by timmyrs** [comment]
I'm afraid they're making sure you've actually waited 30 seconds in the backend, so nothing I can do there.
