### ISSUE TITLE
Request to add domains in list

### ISSUE THREAD

**Issue by ezahepe** [timmyrs/Universal-Bypass#251]
https:// shrtz.me /xJhN6e
Actual Domain : https:// shortzon.com
Link Generated : https:// shrtz.me/xJhN6e
Ads displayed: http:// viraltechnical.in/xJhN6e
 
https:// ushortx.com/joHH3t
Actual Domain : https:// ilinkshort.com
Link Generated : https:// ushortx.com/joHH3t
Ads displayed: https:// gamesindians.com/joHH3t

**Comment by timmyrs** [comment]
What?
