### ISSUE TITLE
[Request] linkach.com

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#254]
http://linkach.com/?id=QnlRMS8vZFNHZTJoNmRVbCtJSmp5d2U5Rlp2dUxwVTd1by82aDRjL0o5dz0=
http://linkach.com/?id=Y3puclVLdGRzMTlRV3BuVC9EVE1UM2NDMjc1QmNvZFZkaGk1Qml6dlNEb3pzNVZYeXMvNWZEb2htZHIxdlROUXZZVUIvb1J1ankwZ25WMEVZcVovSlRnbFZrcXc2dGNOZzZ6UkhoT2RHcjRkcmhiN0x2T3lDZ1FIdndDa0kzL24wUGV1bUkrb0RMeU9LYXMwYXZRdzVnPT0=
http://linkach.com/?id=UlQ1QXhnQnVoVHpmUXZYcjFtdHowbnUvdUZBTFd0ZXNmU0p2QTlmK3lpdkpFOE13dy9FZzlBN0toRmhkbW5xUURqdUJKS3JGbDZPK2NFSkdtQWxQT3c9PQ==

**Comment by timmyrs** [comment]
Duplicate of #193.
