### ISSUE TITLE
uploadrar.com\ automatic press create download link button

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#257]
Execute below js to "Press" the button.
`F1.submit();`
idk how to confirm when the setTimeout done its part, so I need help, thx :D

**Comment by timmyrs** [comment]
Could you provide an example link?

**Comment by vungsung** [comment]
https://uploadrar.com/ui9h7xmjhge4
Thanks.

**Comment by vungsung** [comment]
An idea came into my mind, why don't we directly submit F1, instead of using setTimeout?

**Comment by timmyrs** [comment]
Universal Bypass is already bypassing the wait time on this site. Clicking buttons isn't that hard, and maybe the user doesn't want Universal Bypass to do it automatically.
