### ISSUE TITLE
uploadev.org boost download wait time

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#258]
This site uses jquery library, so we can take advantages of it to build our userscript, but we can either choose javascript instead, to be more safety.
I measured a few times and found that 18 seconds is the shortest time that can be used to bypass the server. I might add up more sites like DoUploads which cannot be bypassed instantly but can reduce the wait time.

To boost the download wait time (Useful, from original 20 -> 18 secs):
> jquery version: `$(".seconds").text(18)`
> javascript version: `document.getElementsByClassName("seconds").item(0)["innerText"] = 18`

To unlock the download button (Unnessasry, just saying):
> jquery version: `$(".downloadbtn").attr("disabled", false)`
> javascript version: `document.getElementById("downloadbtn").disabled = ""`

**Comment by timmyrs** [comment]
Could you provide an example link?

**Comment by vungsung** [comment]
https://uploadev.org/ast8vmoghln4
Thanks.

**Comment by timmyrs** [comment]
The website seems broken to me.

**Comment by vungsung** [comment]
Maybe a Japan route VPN can fix it.

**Comment by vungsung** [comment]
Try this if you want: https://www.vpngate.net/en/download.aspx
I often use this to temporary bypass websites that need wait XX hours to download another file zzzz...

**Comment by timmyrs** [comment]
Considering the website doesn't seem to work, and the bypass only saves 2 seconds, I'll just leave it be.
