### ISSUE TITLE
[Request] New sites

### ISSUE THREAD

**Issue by bup4gr** [timmyrs/Universal-Bypass#260]
**1**
`http://brenhealth.com/0V32p`
but `https://shortzon.com/` has other domains

**2**
`http://domehel.com/xGBrhna`
but `https://linkjust.com/` has other domains

**Comment by bup4gr** [comment]
**3**
`https://uii.io/WoVEqa`

**4**
for me don't work `https://ouo.io/HBdTWH` or `https://ouo.press/HBdTWH`

**Comment by timmyrs** [comment]
They're all bypassed by crowd bypass which means you don't have to wait if someone has already waited on it.

**Comment by bup4gr** [comment]
How can i use crowd bypass?
For me the bypass for this sites don't work.
For example i remember that in the past i can bypass ouo.io and ouo.press, but not today.

**Comment by timmyrs** [comment]
You're using it as long as you've enabled it in the options (which it is by default):
![image](https://user-images.githubusercontent.com/11009697/59086660-aa343980-8902-11e9-95b2-c5c6a16bf39b.png)

**Comment by bup4gr** [comment]
Thanks, i have re-enable that option (then i restart the browser) and now `https://uii.io/WoVEqa` and `http://brenhealth.com/0V32p` works.
But `http://domehel.com/xGBrhna`, `https://ouo.io/HBdTWH` and `https://ouo.press/HBdTWH` don't work. I cannot bypass this sites. Is only my problem?

**Comment by timmyrs** [comment]
That means no one has waited on them yet.

**Comment by bup4gr** [comment]
Maybe domehel.com is a new site, but ouo.io and ouo.press are old and famous sites.
I think is improbable that no one has waited on ouo.io and ouo.press.

**Comment by timmyrs** [comment]
They need to have waited on the specific link you have there. It's a reason it's called "unbypassable shorteners." You being on that site doesn't magically create a bypass for them.

**Comment by bup4gr** [comment]
Ok, thanks for your patience.
I have another question: when i enable crowd bypass and a proxy or socks5 is set in the browser, the request on your site is through the proxy/socks5, right?

**Comment by timmyrs** [comment]
Yes.
