### ISSUE TITLE
Bypass not working on Adlinkfly New Version 

### ISSUE THREAD

**Issue by sharpanimes** [timmyrs/Universal-Bypass#261]
All websites using the latest version of adlinkfly script are not working, bypasser is unable to bypass it. Can anyone fix it

**Comment by timmyrs** [comment]
Could you provide an example link?

**Comment by sharpanimes** [comment]
https://ilinkshort.com/zpp8/ here is one

**Comment by timmyrs** [comment]
That's bypassed by crowd bypass which means you don't have to wait if someone has already waited on it.

**Comment by sharpanimes** [comment]
Well what if someone didn't isn't there a way to bypass it directly

**Comment by timmyrs** [comment]
I'm afraid not.

**Comment by sharpanimes** [comment]
😶ok no problem
