### ISSUE TITLE
Require ecleneue.com (One of ad.fly's subpage?) Redirect

### ISSUE THREAD

**Issue by vungsung** [timmyrs/Universal-Bypass#265]
Example Link: 
https://www1.ecleneue.com/pushredirect/?placementid=14488915&clickid=6263515655&t=1560163699&dest=https%3A%2F%2Fgloyah.net%2Fredirecting%2FaHR0cHM6Ly93d3cubWVkaWFmaXJlLmNvbS9maWxlLzlyNzlxNjUyY25xNjlwYS90aGFua2luZ3YzLnJhci9maWxl%2Fd435098861a57948f7f8cbaec69b0e9a

This site will enforce you allow Notification to continue.
Bypass by decoding url in `dest` paramater.
Thank you.

**Comment by timmyrs** [comment]
That's a 404 for me. Where did you get that link from?

**Comment by vungsung** [comment]
The link seems down for me, too.
This is the original link: http://evassmat.com/PmbJ

**Comment by vungsung** [comment]
![image](https://user-images.githubusercontent.com/32069685/59258371-6e82d200-8c6a-11e9-9a75-18a63375750d.png)
Yep, it's ad.fly. There are many forms and if you are unlucky, you will be redirected to this form, that won't let you "click" on a button to continue.

**Comment by timmyrs** [comment]
The http://evassmat.com/PmbJ seems bypassed for me and bring me to Mediafire.

**Comment by Cyberavater** [comment]
@timmyrs It seems it's bypassed using NanoAdblocker (or uBlock maybe?). Can you try turning it off?

**Comment by Cyberavater** [comment]
https://github.com/adsbypasser/adsbypasser/blob/3e4a18d652de7fed8b2084ad88a434cc0ac750fb/src/sites/link/adf.ly.js
