### ISSUE TITLE
[Enhancement] muhammadyoga.me

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#270]
Example Links;
http://muhammadyoga.me/FEey1
http://muhammadyoga.me/MOEUy93ThF
http://muhammadyoga.me/SPqeB3XdHfx
http://muhammadyoga.me/JYUzxRCStfh
http://muhammadyoga.me/F2JOR0

It's currently bypassed using Crowd-Bypass; #244 
While Direct-Bypass is possible;

https://github.com/adsbypasser/adsbypasser/commit/2ad53add7710b0e2608eac67f7875e398adb8c09
https://github.com/adsbypasser/adsbypasser/blob/ea300d9786fab7285da6d8eb3a44d52971f27d78/src/sites/link/linkdrop.net.js

**Comment by timmyrs** [comment]
That code only bypasses the captcha, which Universal Bypass will not do.

**Comment by Cyberavater** [comment]
I'm not sure what you meant by that but since I'm using both bypassers I noticed that Adsbypasser directly bypasses that while Universal Bypass uses Crowd-Bypass (tested separately for verification).

Now, sometimes it needs a little time (most of the time it's really fast) for Adsbypasser to directly bypass but in that time Universal Bypass pops up it's crowd suggestion which breaks the direct bypass. So, I was hoping a solution to that.

**Comment by Cyberavater** [comment]
So, if you won't do something about it can you at least introduce bypass filter in Universal Bypass?

> That code only bypasses the captcha, which Universal Bypass will not do.

Again, I'm not sure what you meant by that since that site *doesn't* have any captcha to bypass (only clicks and wait-code).

**Comment by Cyberavater** [comment]
In v10.31 it still suggests a Crowd-Bypass in the middle of a direct bypass.

**Comment by timmyrs** [comment]
That commit is yet to be put into a release.
