### ISSUE TITLE
Req lewat.club

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#275]
https://lewat.club/post/67-khasiat-dan-manfaat-daun-suji-untuk-kesehatan-pewarna-makanan-alami?5lEml7j

https://lewat.club/post/67-khasiat-dan-manfaat-daun-suji-untuk-kesehatan-pewarna-makanan-alami?ZXpKy

**Comment by timmyrs** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by falfan2018** [comment]
@timmyrs yes, but with crowd bypass always bring me to the wrong destination 
please fix it

**Comment by timmyrs** [comment]
That's what the "Was this not correct?" button is for.
