### ISSUE TITLE
[Request] mylinks.xyz (clictune.com)

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#281]
Example Link: https://www.mylinks.xyz/7peE

**Comment by timmyrs** [comment]
Whats the target for that example link?

**Comment by Cyberavater** [comment]
https://www47.zippyshare.com/v/2TfQhNox/file.html

**Comment by timmyrs** [comment]
Oh, I see now where the link is supposed to be. Guess I'm blind.

**Comment by Cyberavater** [comment]
Nah, it's cool. I clicked at the wrong place too for the first time.

**Comment by Cyberavater** [comment]
Not fully functional from my side. Is it working perfectly for you?

**Comment by timmyrs** [comment]
Yes, using 10.34.

**Comment by Cyberavater** [comment]
Can't reproduce on a fresh browser or even pinpoint the extension that might cause it on the old one. Here's an ss of the console tho (if it helps);
![s](https://user-images.githubusercontent.com/32187927/60190054-d1bc5900-9853-11e9-87d4-86e6ebcc573f.png)

**Comment by timmyrs** [comment]
I assume that could be a timing issue. I'm going to update the codebase so it can better deal with elements that take some time to appear.

**Comment by timmyrs** [comment]
Alrighty, does it work for you using current master?

**Comment by Cyberavater** [comment]
Yup, it works like magic! U are amazing. :)
