### ISSUE TITLE
git.tc

### ISSUE THREAD

**Issue by xorcan** [timmyrs/Universal-Bypass#282]
example link: http://git.tc/xtJWE

auto click to this buton:
![resim](https://user-images.githubusercontent.com/25418042/60197226-afbcd980-9847-11e9-831e-f5c9bc30f19a.png)

thank you for all!

**Comment by Cyberavater** [comment]
@timmyrs Add Crowd-Bypass if possible (or at least keep it open for future).

**Comment by xorcan** [comment]
@Cyberavater what is crowd bypass 

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by timmyrs** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by Cyberavater** [comment]
@xorcan Crowd-Bypass means crowd collected bypass, In other words, you don't have to wait if someone has already waited on it.
Example link: https://lewat.club/post/67-khasiat-dan-manfaat-daun-suji-untuk-kesehatan-pewarna-makanan-alami?5lEml7j

P.S. I'll delete this comment after you read it.

**Comment by Cyberavater** [comment]
@timmyrs Crowd-Bypass is not working there for me.

**Comment by timmyrs** [comment]
Try again.

**Comment by Cyberavater** [comment]
Oh, sorry I was trying with a different version. Now it's fixed.

**Comment by timmyrs** [comment]
It was probably just because no one has waited on it yet, but then I did.

**Comment by Cyberavater** [comment]
Well, I completed the captcha 3 times before reporting to you. So, I'm not sure (altho, I was testing/playing with Universal-Bypass then).

**Comment by xorcan** [comment]
thank you for all :)
