### ISSUE TITLE
link.tl

### ISSUE THREAD

**Issue by xorcan** [timmyrs/Universal-Bypass#283]
example link: http://link.tl/2hTmV

first: auto click to "reklamı geç"
![resim](https://user-images.githubusercontent.com/25418042/60197043-4046ea00-9847-11e9-9f33-c524c15f5e9a.png)
second: we should click right up "pencereyi kapat" button. this is not needed.
![resim](https://user-images.githubusercontent.com/25418042/60196999-29a09300-9847-11e9-863c-e86828f2a75e.png)
and could you block left up this malware warning showing all pages:
![resim](https://user-images.githubusercontent.com/25418042/60197099-6c626b00-9847-11e9-8744-43630c862890.png)
thank you for all !

**Comment by Cyberavater** [comment]
https://github.com/adsbypasser/adsbypasser/commit/ca46e7401d0d078f4e14b6acd017109262bf1bb8

**Comment by timmyrs** [comment]
This is already bypassed and the bypass works fine for me.
