### ISSUE TITLE
req aidainsurance.pw

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#284]
https://aidainsurance.pw/?k=dVJ2L1dSZmJNMkR1UHkwOFhteU5UTGRPcnlCdWdVajdwRk1Tc3NZckpqZz0=

`https://ryuukoi.web.id/anime-spring-2019-batch-subtitle-indonesia/`

**Comment by timmyrs** [comment]
Duplicate of #193
