### ISSUE TITLE
Please Bypass This Anti Bypass Plugin

### ISSUE THREAD

**Issue by dedsec404** [timmyrs/Universal-Bypass#287]
this website (drivenime.com) uses a plugin that has an anti-bypass feature that provides a unique ID at any time

**api.rurafs.me cannot be accessed directly**

> 1nd Redirect
> https://api.rurafs.me/v2/rurasafe/xxxxxxxxx
> 2nd Redirect
> https://bagilagi.com/?k=xxxxx==
> 3nd Redirect
> https://bagilagi.com/xxxxx/
> 4nd Redirect
> https://api.rurafs.me/v2/rurasafe/xxxxxxxxx
> 5nd Redirect
> https://drive.google.com/file/d/xxxxxxx

oh btw, this is **tempermonkey script** that can bypass (drivenime.com)
https://textuploader.com/1dw4p
hope that you can add this script to **Universal Bypass**

**Comment by timmyrs** [comment]
Duplicate of #193
