### ISSUE TITLE
The SafeLinkReview example

### ISSUE THREAD

**Issue by grahamperrin** [timmyrs/Universal-Bypass#292]
Re: https://github.com/timmyrs/Universal-Bypass/issues/7#issue-326854887

Amongst the examples at https://universal-bypass.org/example-links: 

- http://awsubsco.cf/en/cost/bit.ly?id=aHR0cDovL2JfdC5seS8yR09IOE5N&c=1&user=61942

With Universal Bypass disabled, `http://awsubsco.cf/en/cost/bit.ly?id=aHR0cDovL2JfdC5seS8yR09IOE5N&c=1&user=61942` is immediately not found (server not found). 

With the extension enabled: 

1. moz-extension://5b30edda-cf2c-4f99-853d-31c1cc6b9b90/html/before-navigate.html?target=http%3A//bit.ly/2GOH8NM appears
2. the linked destination changes to http://short.awsubs.co/7JYYp
3. following the link briefly displays the page shown below
4. moz-extension://5b30edda-cf2c-4f99-853d-31c1cc6b9b90/html/before-navigate.html?target=https%3A//drive.google.com/open%3Fid%3D1CTYWkl-vJamvlRqj7pJDmtZomkcsERjV appears
5. https://drive.google.com/open?id=1CTYWkl-vJamvlRqj7pJDmtZomkcsERjV is 404

### Screenshot of `http://short.awsubs.co/7JYYp`

![image](https://user-images.githubusercontent.com/192271/61168828-ce131c80-a54b-11e9-95cd-0bdf1163ba3d.png)

(Parts of the page probably not loaded because I keyed <kbd>Escape</kbd> to suppress the automated progress to step 5.)

### Thought

Given the comparative chain of events when the extension is enabled, maybe better to **not** include this one amongst the examples …

**Comment by timmyrs** [comment]
Thank you for reporting this broken example link, I've removed it from the list.

Also, it might be good for you to know that you can disable the instant redirect (which is the default setting):
![image](https://user-images.githubusercontent.com/11009697/61168927-dff9bd00-a555-11e9-9910-4f9788bf749d.png)
