### ISSUE TITLE
Add support for ouo.io

### ISSUE THREAD

**Issue by Keith94** [timmyrs/Universal-Bypass#3]
For example: http://ouo.io/5EiQgs

Link comes from this source page: http://www.9tensu.com/2018/03/galaxy-burst.html

**Comment by timmyrs** [comment]
It's a captcha. No timer. Bypass that for me please, if you dare.

**Comment by ghajini** [comment]
`ouo.io/hUJJOL`
Can you bypass this site, I see no captcha here

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
