### ISSUE TITLE
playground.ru

### ISSUE THREAD

**Issue by bogachenko** [timmyrs/Universal-Bypass#301]
`https://www.playground.ru/cheats/grand_theft_auto_5_gta_v_chit_mod_cheat_mode_enhanced_native_trainer_update_40_bugfix_update_9-87245/`

Click on the large gray button in the center "СКАЧАТЬ"

**Comment by timmyrs** [comment]
It seems like they have backend validation to make sure you actually waited, so nothing I can do there I'm afraid.
