### ISSUE TITLE
Fshare.vn 404 bad request

### ISSUE THREAD

**Issue by hieunhoo** [timmyrs/Universal-Bypass#303]
https://www.fshare.vn/file/M5MDNZQGPZJG?token=1563767785 or any link

bypass get error code 404-> disable bypass website -> Alt+ <- (left back button) anh Alt+ -> (right button -> link downloaded

![Capture](https://user-images.githubusercontent.com/48126508/61605436-ab7db380-ac6f-11e9-8732-669eba6eabd6.PNG)

**Comment by timmyrs** [comment]
Seems like they added backend validation to prevent the countdown from being bypassed, so I'll remove the bypass to prevent breaking the site.

**Comment by hieunhoo** [comment]
Oh, the website announces continually "Traffic of owner not enough." and lead to error 502, after you turn it off, no longer bypass by manual

ồ, trang web thông báo liên tục "Traffic of owner not enough." và dẫn đến lỗi 502, sau khi anh tắt đi thì không còn bypass bằng thủ công được nữa
