### ISSUE TITLE
redirects some microsoft links to the german microsoft store

### ISSUE THREAD

**Issue by DessertArbiter** [timmyrs/Universal-Bypass#306]
it happens until i disable the extension, but then even if i re-enable it i have no more issues, so im guessing it has something to do with getting redirected when not logged in

for example it happens with this link https://social.technet.microsoft.com/Forums/ie/en-US/01ae4232-7213-491b-82da-afa5196cc902/running-multiple-commands-on-vb-script-run-method?forum=ITCG

**Comment by timmyrs** [comment]
Doesn't happen with me. That also seems like a peculiar bug. Do you have any more details you could share?

**Comment by DessertArbiter** [comment]
i added login.live.com as an exclusion in my adblocker and that seems to have fixed it, not sure why disabling this extension also fixes it though

**Comment by timmyrs** [comment]
It could be a weird interference issue. Sometimes extensions which try to do similar things to Universal Bypass (such as an ad blocker), might run into UB and that just has some weird consequences. Do you happen to be on Firefox? I think this sort of thing is more prone to happen there.

**Comment by DessertArbiter** [comment]
nah but im using adguard for system-wide ad blocking

**Comment by timmyrs** [comment]
Does it happen if you disable this option?
![image](https://user-images.githubusercontent.com/11009697/61966446-ed418d80-afd2-11e9-9990-0c76f66b8650.png)
