### ISSUE TITLE
Bypass failure

### ISSUE THREAD

**Issue by Void2258** [timmyrs/Universal-Bypass#309]
Many times when the "you might not have to wait" page comes up, the link does not lead to the page in question, it leads to more ads but not the target page. Because the bypass page doesn't have an override, it sometimes makes the actual page inaccessible, because the bypass page blocks the ability to access the actual (though ad-filled) page route.

**Comment by timmyrs** [comment]
1. That's what the "Was this not correct?" link is for.
2. Could you provide a link where you encounter this?

**Comment by Void2258** [comment]
"Was this not correct" just reloads the prior page, then immdiatly loads up the same bad "you may not have to wait" page. I end up having to turn off the extension completely as the only way to get to the actual page I want.

moz-extension://4843d6c8-19f6-4583-9311-73091d89487e/html/crowd-bypassed.html?target=https%3A%2F%2Fgetfree-vpn.com%2Fre%2F%23https%3A%2F%2Ftechnispot.com%2Fbitcoin-mining-merchant-account%2F%3Fn%3DFcfBDoIgAADQr_FYE6mWR2emOXDTSpQbYtMSxQ0a4tdn27u8XutZOTBwvOtGvKdlz4X8tlu6l9610kxCsn9ZUrg8wSdkfcXI8YDGTDWwHJBXKkqAaKai59Og-RpA-ogMqgpJ70DVVSE4zHVD_IESo7P1ZnjoLjhO5zYEkJLUsirQeMwkqjqbfZ6axaVXW2C4F0G85gDbswMvPw&back=https%3A%2F%2Fclk.ink%2FdI0kS

**Comment by timmyrs** [comment]
Funnily enough I can reproduce this issue but only when I don't have uBlock Origin installed.
