### ISSUE TITLE
[Request] k2s.cc

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#313]
Example Link: https://k2s.cc/file/6a990555d8900/Test.txt
Hope it's free download wait-code is bypassable.

**Comment by timmyrs** [comment]
Seems like a simple timer bypass did the trick.

**Comment by Cyberavater** [comment]
Thanks, highly appreciated.

**Comment by Cyberavater** [comment]
<div style="width:100%;height:0px;position:relative;padding-bottom:33.750%;"><iframe src="https://streamable.com/s/2adft/mwqxrs" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by timmyrs** [comment]
Do you have another extension that might interfer with Universal Bypass?

**Comment by Cyberavater** [comment]
Maybe no, but can try by downloading the file simultaneously twice? Since the issue was logged from there.
