### ISSUE TITLE
[Compatibility] Crowd-Bypass and Adsbypasser

### ISSUE THREAD

**Issue by Cyberavater** [timmyrs/Universal-Bypass#320]
Example Link: http://uiz.io/y6wOr

If you have <a href="https://github.com/adsbypasser/adsbypasser">Adsbypasser</a> installed, it doesn't capture the Crowd-Bypass, which lead people to think that Crowd-Bypass doesn't work on some sites and then they open issues regarding that. So, can you make (Universal-Bypass's) Crowd-Bypass compatible with Adsbypasser, please?

**Comment by timmyrs** [comment]
The issue here is that Adsbypasser is not compatible with Universal Bypass, not the other way around.

**Comment by Cyberavater** [comment]
I'm not sure how you determine that, but Adsbypasser is not having any issue working with Universal Bypass (i.e. Adsbypasser is working perfectly), while Universal Bypass is having issue working with Adsbypasser.
Anyways, it'd be nice if you could figure out a workaround.
