### ISSUE TITLE
bypass link.tl not working

### ISSUE THREAD

**Issue by xorcan** [timmyrs/Universal-Bypass#321]
https://link.tl/U29k

auto click to "reklamı geç (skip ad)"

**Comment by timmyrs** [comment]
I don't understand where that link is supposed to take me to, I only get ads.

**Comment by falfan2018** [comment]
https://lnkload.com/2j7YA
supposed to `https://example.com/`

**Comment by timmyrs** [comment]
I don't even remotely see example.com there, only ads.

**Comment by falfan2018** [comment]
@timmyrs ads are in the first tab and the destination link is in the second tab(auto open new tab)

**Comment by timmyrs** [comment]
Which second tab? It's only ads for me.

**Comment by falfan2018** [comment]
@timmyrs 
![Annotation 2019-08-07 204353](https://user-images.githubusercontent.com/9379770/62627803-4525b000-b954-11e9-81a1-dfc6ab458bd0.png)
![Annotation 2019-08-07 204303](https://user-images.githubusercontent.com/9379770/62627816-4bb42780-b954-11e9-8ee3-31007788a2dd.png)

**Comment by timmyrs** [comment]
I didn't actually get to the destination without some code to screw with the website. I'm not even sure I want to bypass it, because that would be doing them a favour to actually make the website useful, lol.
