### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by anonymous270** [timmyrs/Universal-Bypass#328]
https://mundodocinema.ga/redirecionamento_final?token=bWFnbmV0Oj94dD11cm46YnRpaDo1MDA2OThFQjM2OUJDNjQ3QkI1MTJEN0MzRUNCNkQ5RjhDRENERkMyJmFtcDtkbj0lNWJXV1cuQkxVRFYuVFYlNWQlMjBWaW5nYWRvcmVzJTIwLSUyMFVsdGltYXRvJTIwMjAxOSUyMCUyODEwODBwJTIwLSUyMEJsdVJheSUyMC0lMjBGVUxMJTI5JTIwQWNlc3NlJTIwbyUyME9SSUdJTkFMJTIwV1dXLkJMVURWLlRWJmFtcDt0cj11ZHAlM2ElMmYlMmZ0cmFja2VyLm9wZW5iaXR0b3JyZW50LmNvbSUzYTgwJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZnRyYWNrZXIub3BlbnRyYWNrci5vcmclM2ExMzM3JTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZjkucmFyYmcudG8lM2EyNzMwJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZmV4cGxvZGllLm9yZyUzYTY5NjklMmZhbm5vdW5jZSZhbXA7dHI9aHR0cCUzYSUyZiUyZmdsb3RvcnJlbnRzLnB3JTNhODAlMmZhbm5vdW5jZSZhbXA7dHI9dWRwJTNhJTJmJTJmcDRwLmFyZW5hYmcuY29tJTNhMTMzNyUyZmFubm91bmNlJmFtcDt0cj11ZHAlM2ElMmYlMmZ0b3JyZW50LmdyZXNpbGxlLm9yZyUzYTgwJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZnRyYWNrZXIuYWxldG9ycmVudHkucGwlM2EyNzEwJTJmYW5ub3VuY2UmYW1wO3RyPXVkcCUzYSUyZiUyZnRyYWNrZXIuY29wcGVyc3VyZmVyLnRrJTNhNjk2OSUyZmFubm91bmNlJmFtcDt0cj11ZHAlM2ElMmYlMmZ0cmFja2VyLnBpcmF0ZXB1YmxpYy5jb20lM2ExMzM3JTJmYW5ub3VuY2U=

![1](https://user-images.githubusercontent.com/53842414/62586164-d896ac80-b892-11e9-88b4-cd8be7258da8.PNG)

**Comment by timmyrs** [comment]
I don't see what there is to be bypassed.

**Comment by anonymous270** [comment]
You are required to click on two ads to get the link and also redirects through multiple pages. Same as #182

**Comment by timmyrs** [comment]
Is `magnet:?xt=urn:btih:500698EB369BC647BB512D7C3ECB6D9F8CDCDFC2&amp;dn=%5bWWW.BLUDV.TV%5d%20Vingadores%20-%20Ultimato%202019%20%281080p%20-%20BluRay%20-%20FULL%29%20Acesse%20o%20ORIGINAL%20WWW.BLUDV.TV&amp;tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&amp;tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&amp;tr=udp%3a%2f%2f9.rarbg.to%3a2730%2fannounce&amp;tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&amp;tr=http%3a%2f%2fglotorrents.pw%3a80%2fannounce&amp;tr=udp%3a%2f%2fp4p.arenabg.com%3a1337%2fannounce&amp;tr=udp%3a%2f%2ftorrent.gresille.org%3a80%2fannounce&amp;tr=udp%3a%2f%2ftracker.aletorrenty.pl%3a2710%2fannounce&amp;tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&amp;tr=udp%3a%2f%2ftracker.piratepublic.com%3a1337%2fannounce` is the correct destination?

**Comment by anonymous270** [comment]
Yes

**Comment by anonymous270** [comment]
Nothing has changed here, is there anything I need to do?

**Comment by timmyrs** [comment]
No, the bypass will be with you as soon as a new version of Universal Bypass rolls out.

**Comment by anonymous270** [comment]
Thank you
