### ISSUE TITLE
Request Adtival Network bypass

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#329]
https://kabarviral.blog/post/top-android-phone-games?psU1BSA=1&d=1
supposed to `https://drive.google.com/file/d/1Q_i7B2P5ksY52VmRfQ2gHB3bqwC9ddyC/view`

https://kabarviral.blog/post/top-android-phone-games?VuKrQJ=1&d=1
supposed to `https://multiup.org/ee1e63955e264363af9071c42b4459f7`

https://tips.atv.pw/post/top-android-phone-games?k3lBc=1&d=0
supposed to `https://drive.google.com/file/d/1Un_FJ_IHpkxPOjjLuIF6mop4Z73sGcLN/view`

https://tips.atv.pw/post/top-android-phone-games?fmts1Dh=1&d=0
supposed to `https://www108.zippyshare.com/v/k4hZ4b4X/file.html`

**Comment by timmyrs** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
