### ISSUE TITLE
Request www.razorlink.us

### ISSUE THREAD

**Issue by falfan2018** [timmyrs/Universal-Bypass#330]
https://www.razorlink.us/p/healthy-benefits-of-drinking-warm-white.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDclMThsfnElMUZvUV8lMDclNUUlMDdFR0slMDZNWkklNDAlNUJRWFhBUiUwNiUxQSUxQl9fXyUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D
supposed to `https://www32.zippyshare.com/v/wyG7YVD0/file.html`

https://www.razorlink.us/p/is-catering-good-business.html?url=IyNDTCU1Qk0lNUVBWkwlMTVYJTVCJTVEJTE3X01BJTVFJTA3UVAlMDVRemtBTElBZHBZJTEwQyUwNXklNUJYJTQwJTFETyUxQXJmUH4lNURtJTE5eiU1RCUxOSUwN0wlMDdNREFOJTA3TEElMDYlNDBLJTVCJTA2WkUlNUIlMDUlMUYlMTlGQ0UlNUIlMDdJJTA3RUdLJTA2TURPR0dPJTA2TSU1RUFaTCUwNyUwNyUxMiU1QlglNUMlNUMlNDAjIw%3D%3D
supposed to `https://drive.google.com/file/d/1uR1EuVxNZ2g5hpsQ-k8qXLiadiCRy-xy/view`

https://www.razorlink.us/p/is-catering-good-business.html?url=IyN5JTE4eiU3Qm0lN0R4JTE4JTA3WkslMDZaQUUlMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D
supposed to `https://www.mirrored.to/files/0PUESR0Q/`

https://www.razorlink.us/p/forex-is-invest-of-future.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDclMUMlMUMlMUUlMUIlNjBGTiUxQSUwNyU1RSUwN0VHSyUwNk1aSSU0MCU1QlFYWEFSJTA2JTE5JTFDX19fJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
supposed to `https://www41.zippyshare.com/v/2fnH3644/file.html`

**Comment by Cyberavater** [comment]
This bypass is not working anymore. Please update this bypass. [Example links are given in OP]

**Comment by timmyRS** [comment]
The bypass works, funny old uBlockOrigin is just interfering and breaking it. I don't know what's up with uBlockOrigin breaking all my bypasses recently.

**Comment by Cyberavater** [comment]
Oh yes, it's working after I disabled Nanoadblocker on that page, thanks.
