### ISSUE TITLE
fc.lc

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#335]
https://fc.lc/YvMVa
http://fc.lc/Un1aA

**Comment by falfan2018** [comment]
@timmyRS it seems already bypassed with universal bypass

**Comment by timmyRS** [comment]
The power of writing code and it doing more than what you wanted!

**Comment by falfan2018** [comment]
@timmyRS thanks, highly appreciated you are amazing :D
