### ISSUE TITLE
request thesimsresource.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#336]
http://www.thesimsresource.com/downloads/1456951
destination link https://www.thesimsresource.com/downloads/thankyou/id/1456951

http://www.thesimsresource.com/downloads/1457010
destination link https://www.thesimsresource.com/downloads/thankyou/id/1457010

**Comment by timmyRS** [comment]
That can't be bypassed because they're making sure you've actually waited in the backend.

**Comment by anonymous270** [comment]
Use this https://greasyfork.org/pt-BR/scripts/18938-tsr-freemium

**Comment by NatoBoram** [comment]
tsr-freemium seems down
