### ISSUE TITLE
Request new-xgame.online

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#344]
http://url.animeszx.com.br/redirecionador/5d04ece70bf4a-818175
http://url.animeszx.com.br/redirecionador/5d0da27ced3b2-818175
http://url.animeszx.com.br/redirecionador/5d3324458ab58-818175
http://url.animeszx.com.br/redirecionador/5d35e2d943a1c-818175

**Comment by timmyRS** [comment]
This looks like it's already bypassed.
