### ISSUE TITLE
Req shortlink.in

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#349]
http://shortlink.in/zwO

**Comment by timmyRS** [comment]
That just redirects me a million times until I end up with an ad or error.

**Comment by falfan2018** [comment]
works very well on me with all extensions enable after countdown 5s 
click the top right corner and supposed to `https://example.com/`
![Annotation 2019-08-19 153605](https://user-images.githubusercontent.com/9379770/63251073-2a7a0200-c297-11e9-9717-748dc77802fd.png)

**Comment by timmyRS** [comment]
Weirdly enough, now that I click the link again, I see the same thing you see.
