### ISSUE TITLE
request zanbooredana.com

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#352]
https://zanbooredana.com/vb9VD

**Comment by timmyRS** [comment]
Seems broken for me. Where did you get that link from?

**Comment by falfan2018** [comment]
it comes from `https://www.anisuki.site/2019/08/kanata-no-astra-subtitle-indonesia.html`
a few weeks ago on shorteners `https://mytreep.icu/nG2eV`  auto redirect to `https://zanbooredana.com/***`

**Comment by timmyRS** [comment]
All the `mytreep.icu` links on the source site also seem broken for me. Could this be a region lock?

**Comment by falfan2018** [comment]
nope, broken for me too.

**Comment by timmyRS** [comment]
So, should I close this issue?

**Comment by falfan2018** [comment]
you can close this issue for now

**Comment by falfan2018** [comment]
@timmyRS i think the sites is up now and redirect to `https://hokiciki.org/*****`
