### ISSUE TITLE
plz request

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#354]
Example 1 : `https://ceklinku.xyz/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MTYzTUNzTmlBanlXbnZfQVlIUmFTeU05Q293WHQxTzNr`

Example 2 : `https://ceklinku.xyz/?r=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MWU0VE9ZUzZmYXFUT3NzU0N3VVJyM0lBdWtvSGpocUVp`

**Comment by timmyRS** [comment]
Duplicate of #193

**Comment by anaklayangan** [comment]
I think this is just base64 url
`atob(new URLSearchParams(location.search).get('r'));`
