### ISSUE TITLE
[Request] safelinking.net

### ISSUE THREAD

**Issue by Cyberavater** [timmyRS/Universal-Bypass#355]
Example Link: https://safelinking.net/p/5Ugu8dl

**Comment by timmyRS** [comment]
What exactly is there to be bypassed?

**Comment by Cyberavater** [comment]
Destination Link: https://mirrorace.com/m/4bu3k
![Screenshot (75)](https://user-images.githubusercontent.com/32187927/63292003-8c158d00-c2e6-11e9-9e64-cfcc06dc9acd.png)

**Comment by timmyRS** [comment]
I see that, but that's in no way hidden.

**Comment by Cyberavater** [comment]
> I see that, but that's in no way hidden.
I know..... You can close this issue if you want.
