### ISSUE TITLE
Bug space.tribuntekno.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#367]
`https://space.tribuntekno.com/?id=M2l3UEV2SytpMFlOMFNZVVp4em1TK1V6RmZLbTFma3I2SnhtRWx0UXRvbGNUSk4xNStXeE9xTE1TTXBSYVZ4Ug==`

`https://space.tribuntekno.com/?id=ajErM2tQbHJtZHhKcndFdHFXZ05tbDF6NU95YXNmMXpHMUNFbXRmeDA4WjBoYXdJdFlGZ2l5K0VYdkRrcCs2OA==`

Source : `https://tv21.biz/annabelle-comes-home-2019/`

**Comment by timmyRS** [comment]
Duplicate of #193
