### ISSUE TITLE
Request for up-4ever

### ISSUE THREAD

**Issue by RaReMoDz** [timmyRS/Universal-Bypass#368]
bypass for https://www.up-4ever.org/

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by RaReMoDz** [comment]
https://www.up-4ever.org/25xiyf58awvz

**Comment by timmyRS** [comment]
I'm afraid that can't be bypassed because they make sure you've actually waited in the backend.

**Comment by zNight0** [comment]
shitishit
