### ISSUE TITLE
Bug wegner.tech bad request

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#369]
https://pastekan.com/PDGh
https://pastekan.com/0zxQG

sometimes get bad request after boosting countdown

**Comment by timmyRS** [comment]
I get a DNS error.

**Comment by OAWERF** [comment]
> 
> 
> I get a DNS error.

i think universal bypass already bypassed this website

**Comment by timmyRS** [comment]
Where do you always get these broken links from? But, actually, now it worked, and it seems like it's already crowd bypassed.

**Comment by falfan2018** [comment]
it's from `https://www.huntersekai.website/2019/07/machikado-mazoku-episode-02-subtitle.html`
yeah i know it's already crowd bypassed but i mean if someone haven't passed the link sometimes get bad request and stuck
![Annotation 2019-08-21 030313](https://user-images.githubusercontent.com/9379770/63380296-65c42000-c3c0-11e9-8b6f-35044fd925d9.png)

**Comment by timmyRS** [comment]
I don't think that's an issue with Universal Bypass, tho.

**Comment by falfan2018** [comment]
ahh sorry i test again with only universal bypass enable it works really well
