### ISSUE TITLE
plz bypass this annoying safelink if possible

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#372]
safelink from sites: 
https://drivenime.com/boku-no-hero-academia-the-movie-futari-no-hero-sub-indonesia/
https://movieku.org/the-hobbit-3-subtitle-indonesia/
https://hananime.com/vinland-saga/

or add to crowd bypass if it's possible
thank you so much

**Comment by timmyRS** [comment]
Duplicate of #193
