### ISSUE TITLE
Crowd bypass doesn't work after update v10.42

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#373]
in this types of safelinku
http://semawur.com/yfgUyTcRZXhV
http://semawur.com/vHiX
http://kitasemua.me/c84F8J
http://kitasemua.me/VdvF5tYyFj
 
we must click button continue to activated crowd bypass before the update worked very well, crowd bypass immediately appeared.
probably because this commit 
`https://github.com/timmyRS/Universal-Bypass/commit/b12db55f80648e10111536f6398b1ee82cd375c2`

**Comment by timmyRS** [comment]
You always had to press that button, and I don't see any way to detect that specific site just to press the button. Better to just not do it than to press a Bootstrap button by accident.

**Comment by falfan2018** [comment]
@timmyRS i mean activated the bypass if someone already waited on it. 
after this commit https://github.com/timmyRS/Universal-Bypass/issues/326 
crowd bypass on safelinku all types works very well and after update v,10.42 not working anymore,
exampe safelinku with captcha : 

http://semawur.com/rwHw0sL supposed to `https://drive.google.com/file/d/1UlxReRNB_zCNkG1q7057bz79Fxo3Dzt6/view`
http://semawur.com/D7VhsC9l supposed to `https://drive.google.com/file/d/1RDHwqIb8xUevQsPowzrtjf_rsLsuCFrW/view`

another types with captcha : 
http://1idsly.com/3dbrns supposed to `https://drive.google.com/drive/folders/1vIAIAtmjXLPQeXVhoZGqoL6S0S1zqiEn`
http://advancedautorepairtips.me/ZAT1Tj supposed to 
`https://drive.google.com/drive/folders/1NwEj-hxBtlLPaO-bCP4qSIlSXWti7wmD`

**Comment by timmyRS** [comment]
Can you reproduce the issue in the current master version of Universal Bypass?

**Comment by falfan2018** [comment]
i can't. i'am not a programmer

**Comment by timmyRS** [comment]
It's simple:

1. Download https://github.com/timmyRS/Universal-Bypass/archive/master.zip
2. Unzip it
3. Go to `chrome://extensions/`
4. Disable Universal Bypass
5. Enable "Developer mode" on the top-right
6. Click "Load unpacked" which just appeared
7. Select the `Universal-Bypass-master` folder which you had unpacked

It should be sorta similar if you are on Firefox.

**Comment by falfan2018** [comment]
ok I've tested all the links above it works very well 
sorry if my english bad 
I'm still learning

if there is a problem with another types I will report here
