### ISSUE TITLE
Request drivenime

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#386]
Example link:
`http://bagilagi.com/?id=U3ZCaGl2d0lOTmNvbkNGczdtUmMyWkhod0NxWDQ3K3R1VTdPZmhmcUtoRk8vb2VqQWYyWml3ejk4WGlNSGxpMWVSN25kcnB4K3RzMWg4TEp0ekFBeURMUkUrTEhySmxVUlF2WEF1c29WOGs9`
`http://bagilagi.com/?id=U3ZCaGl2d0lOTmNvbkNGczdtUmMyWkhod0NxWDQ3K3R1VTdPZmhmcUtoSHg4VkZBQ2tLV0pkdXg5TE4rem93RHN4SmNFYitJSjlCSEdmaFdOL0NtK2k4ZzFHZm4weUJBRlRQYTEzTmVoN0k9`

Source link :
`https://drivenime.com/dragon-ball-super-movie-broly-subtitle-indonesia/`

**Comment by 0x6c4bf2e1** [comment]
```
domainBypass(/bagilagi\\.com|sweetlantern\\.com|lonelymoon\\.net|intercelestial\\.com/,()=>{
	ifElement("#generater",g=>{
		setTimeout(()=>{
			g.click()
			setTimeout(()=>{
				let f=document.createElement("form")
				f.method="POST"
				f.action=theShit.base+"?z="+theShit.id
				f.innerHTML='<input type="hidden" name="z" value="'+theShit.z+'"><input type="hidden" name="c" value="'+document.querySelector("#recaptchaResponse").value+'"><input type="hidden" name="soramode" value="'+soramode+'">'
				f=document.body.appendChild(f)
				f.submit()
			},6000)
		},2000)
	})
})
```
I don't know this can be called a bypass or not, because the website is using backend timer 8 seconds.
This is also related to https://github.com/timmyRS/Universal-Bypass/issues/380

**Comment by timmyRS** [comment]
Waiting 8 seconds is as good as no bypass at all. Guess I'm reopening #193 and merging all these issues in there again.
