### ISSUE TITLE
Request safelinkwe.win

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#389]
https://www.safelinkwe.win/2018/03/6-tips-to-choose-high-speed-internet.html

**Comment by 0x6c4bf2e1** [comment]
Your link is wrong.
It should be like this: https://www.safelinkwe.win/2018/03/6-tips-to-choose-high-speed-internet.html?url=aHR0cHM6Ly9leGFtcGxlLmNvbS8=
It seems like this is already bypassed.
