### ISSUE TITLE
vozdesportiva.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#394]
Example link:
http://vozdesportiva.com/?id=c1FrTEVTaUtCTlRlczhXR3FQeHFNZDg2NXlENzA0cFR2N0JEYVBUNGJqRT0=
http://vozdesportiva.com/?id=c1FrTEVTaUtCTlRlczhXR3FQeHFNWHFhVHU5Z0pWSVA1V0dCRlZiUjVWaz0=

Source link:
`https://www.zenomovie.com/gekijouban-fate-stay-night-heavens-feel-ii-lost-butterfly-2019/`

**Comment by timmyRS** [comment]
Duplicate of #193
