### ISSUE TITLE
Request add https://shortbits.site to bypass please

### ISSUE THREAD

**Issue by Boyrules** [timmyRS/Universal-Bypass#400]
Hello sir can u please add https://shortbits.site    to universal bypass please . thanks in advance

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by Boyrules** [comment]
https://shortbits.site/CBfu3cguid5

**Comment by Boyrules** [comment]
https://click4bits.com/shortlink.php?sid=34

**Comment by Boyrules** [comment]
https://shortbits.site/CBp0or6a5jj

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by Boyrules** [comment]
But its not bypassing for me .

**Comment by timmyRS** [comment]
Make sure you're using Universal Bypass 10.44.1.
