### ISSUE TITLE
Bug Crowd-bypass doesn't work after update

### ISSUE THREAD

**Issue by falfan2018** [timmyRS/Universal-Bypass#401]
@timmyRS Crowd-bypass doesn't work after updates on all previously supported shorteners/safelink

**Comment by timmyRS** [comment]
Firefox?

**Comment by falfan2018** [comment]
google chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by timmyRS** [comment]
What makes you think it doesn't work?

**Comment by falfan2018** [comment]
because all the links that worked before did not appear popup crowd bypass after I passed through 2x

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by falfan2018** [comment]
almost all the shorteners that I have encountered
Example :
https://kabarviral.blog/post/top-android-phone-games?7Mr172yQ=1&d=0
https://lewat.club/post/top-android-phone-games?Dk0=1&d=1
https://idzone.site/Tzzp
https://dz4invest.com/uEMY
https://viralusablog.us/hkdG
http://ecotechi.com/82WPqKp
etc

**Comment by falfan2018** [comment]
@timmyRS 
if I revert to the v10.43 all works very well
