### ISSUE TITLE
blogpedia.us safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#403]
Example link :
http://blogpedia.us/?id=bVRsZW92VXhBUFdoaGYyclowRGtBbVhMSGpQcnY5My9hNHEwc2NYekdxaWhDeEt3OWIzaklMb2FBU1BXeXdmaQ==
http://blogpedia.us/?id=YUFFaWtYQjU4WlpRczNIWi9MbW9mbUlZNVRFVHRBMUFQd2pTWk9NYW41TWxhdVBqQmswMEpRTEhmWlJvUmQ0cA==

Source link : 
`https://pusatfilm21.com/aladdin-2019/`

**Comment by timmyRS** [comment]
Duplicate of #193
