### ISSUE TITLE
landscapenature.pw safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#407]
Example link :
http://landscapenature.pw/?id=OG0wWnJ5MWlFbDJsYXVKekVURDFaMU1ucDMxbGNGemFialc0bkFLUGw2NFIwd3doQy9YOXUzTEF2RkJRSks1eGgvNDU1OFh5Q3FnZVh5V0tpbXJJYTJCRFA5YWNHWnI2aGJON2dzVHlMbzg9
http://landscapenature.pw/?id=T1p3S3pVRWRQZ1JRblY1VWJ3VFJxcjVvOGloWTYyOThTbGdReGtWZXhZYz0=

Source link : 
`http://gantzid.com/jojos-bizarre-adventure-golden-wind/`

**Comment by timmyRS** [comment]
Duplicate of #193
