### ISSUE TITLE
spacetica.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#413]
Example link : 
https://spacetica.com/e1UpP
https://spacetica.com/hrs8I
https://spacetica.com/vHkTk

Source link : 
`https://sweetlantern.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzVk1xb1M4M0psV0VCSU9ZdE1qZUJKaz0=`
`https://intercelestial.com/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzZWdtNW52M0JxbFFBMzJiNC9NdG81VT0=`
`https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzWUdEejRzOGF3elRaQVNhNFpOcTI5RT0=`

**Comment by timmyRS** [comment]
I don't see what there is to be bypassed.

**Comment by KagaKouko99** [comment]
it's the same as shorteners
https://www.siherp.com/g2aQt  and tetew.info >https://www.ahexa.com/njir/qZ9ex 
which UB handles it

**Comment by timmyRS** [comment]
I'm not a fan of bypassing sites where there's no timer, literally just a button to press, but I guess that's the expectation.
