### ISSUE TITLE
loot.vozdesportiva.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#414]
Example link: 
https://loot.vozdesportiva.com/2019/05/disability-insurance.html?url=IyNMTiUxRSUxQiUxQiUwN0VHSyUwNlElNURDTSU1QyU1QklYJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://loot.vozdesportiva.com/2019/05/disability-insurance.html?url=IyNMTiUxRSUxQiUxQiUwN0VHSyUwNlElNURDTSU1QyU1QklYJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj

Source link :
`https://www.zenomovie.com/gekijouban-fate-stay-night-heavens-feel-ii-lost-butterfly-2019/
`

**Comment by timmyRS** [comment]
This is already bypassed.
