### ISSUE TITLE
kazefuri.me safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#417]
Example link : 
http://kazefuri.me/?id=MnU1YzVFdGMvWFJLZ0VWUTJzdDFWZ0hsYXhQZlRwVGtORGtXV3Q4WHh0MD0=
http://kazefuri.me/?id=MnU1YzVFdGMvWFJLZ0VWUTJzdDFWbERURlNTZGYzdk5NaW1mQno3OXk1UT0=

Source link : 
`https://kazefuri.web.id/the-kings-avatar-2019-episode-38-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Duplicate of #193
