### ISSUE TITLE
Request seoinlink.com

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#418]
http://seoinlink.com/?id=RHl2bk5kcHB4UmR2ZGtubmZoVDVva2FVeVI4cDgrZWtHUUhQdVVzbFdaSDc1NjVtME1zb1Z5eGRqTkJIZDgyVHZQVGt4aklsQlFDSTluZmFsZ0ZXU3V2ai9tOGJqVXBqK3J1Mng1ejlLVU09
http://seoinlink.com/?id=ZVNBMmFzZnZIeTI5a1lTVkM0TFJTYllaN09EVWc3SzM2UHVMdVBLcDBqWnJWSXcvVi9LbDZGZXRNQkZIZmM2V3pqdjJKWFREWUhtVGIvV2dHaWtkWUE9PQ==

`https://kurosave.com/elemelade-batch/`
`http://laganime.com/boku-hero-mia-s1-sub-indo/`

**Comment by timmyRS** [comment]
Duplicate of #193
