### ISSUE TITLE
Crowd bypass doesn't work on new adsafelink

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#420]
https://wetbread.me/3SBmaVSx
https://wetbread.me/PTtfYOd

Source 
`https://kazefuri.web.id/battle-trought-heaven-s3-ep-8/`

**Comment by timmyRS** [comment]
That would be a very complicated bypass to make, since it's all so indirect on these fake blog post urls...

**Comment by WaferNabati** [comment]
@timmyRS 
if wadooo.com is on the second safelink crowd bypass doesn't work 
example :
http://kazefuri.me/?id=QWNldFVzK09WNnJQV3ZzY0NMbStQZ0NJYWk5Q1BOQ1cxbjJOdXpzUlpQUT0=
http://kazefuri.me/?id=QWNldFVzK09WNnJQV3ZzY0NMbStQcERJb3JkanR6dWo0SVEyb2pEc0IvQT0=

source : `https://kazefuri.web.id/the-untamed-ep-5/`

I have tested it with current master UB 
i already passed through repeatedly but crowd bypass didn't appear

**Comment by WaferNabati** [comment]
another example : 
https://pastelink.net/y9sx
