### ISSUE TITLE
new domain adsafelink (pantauterus.me)

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#426]
https://pantauterus.me/peningkatan-produktivitas-aktifkan-mode-malam-di-semua-perangkat-anda/
https://pantauterus.me/cara-membuat-cadangan-drive-usb-dan-mengembalikannya-kondisi-yang-dapat-di-boot-dan-semua/
![Annotation 2019-09-06 152111](https://user-images.githubusercontent.com/9379770/64412778-5f20f280-d0ba-11e9-83d5-8a4b4b996f1a.png)

Source : 
https://pastebin.com/vWxf07gL
https://kazefuri.web.id/the-great-ruler-ep-4/

**Comment by timmyRS** [comment]
I unfortunately only ever get redirected to wadooo.com, and your example links seem like normal blog posts for me.

**Comment by WaferNabati** [comment]
@timmyRS how do I capture the real link. because every time I found that links if it's refreshed it becomes a normal blog

**Comment by timmyRS** [comment]
Press `F12` to bring up developer tools, click the "Network" tab, enable "Preserve log." It will keep all requests, including redirects, which will be indicated in blue. The blue request before the blog post, should be the one I'm interested in.

**Comment by WaferNabati** [comment]
@timmyRS Which ones???
![Annotation 2019-09-07 042122](https://user-images.githubusercontent.com/9379770/64461363-2ec36d80-d127-11e9-8aae-8bb3098e7638.png)

**Comment by timmyRS** [comment]
You need to have it open before you get to that page.

**Comment by WaferNabati** [comment]
@timmyRS 
![Annotation 2019-09-07 042804](https://user-images.githubusercontent.com/9379770/64461677-0c7e1f80-d128-11e9-8d1d-ae90ecd413a8.png)

**Comment by WaferNabati** [comment]
https://pantauterus.me/g/QpvRF095iS

**Comment by WaferNabati** [comment]
@timmyRS https://liputannubi.net/g/QpvRF095iS
