### ISSUE TITLE
Request crowd bypass adsafelink

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#428]
https://gotravelgo.space/g/2tH43
https://gotravelgo.space/g/orlqphXnc

https://pantauterus.me/g/KDpJv
https://pantauterus.me/g/RvaGw

https://liputannubi.net/g/NBNUwR
https://liputannubi.net/g/M87l

Source link : 
`https://ttod.xyz/koutetsujou-no-kabaneri-movie-unato-kessen-subtitle-indonesia/`
`https://kazefuri.web.id/wan-jie-shen-zhu-ep-42/`
`https://pastebin.com/HFBMC860`

can you make a crowd bypass for one link include all domains
example https://adsafelink.net/9SNVWN9ceb if we have passed it, all domains will also be skipped

**Comment by timmyRS** [comment]
I got your comments in the old issue, I just didn't bother bypassing it yet.

**Comment by WaferNabati** [comment]
I opened a new issue including a new domain too
