### ISSUE TITLE
Mirrorcreator.to 

### ISSUE THREAD

**Issue by traitorAIZEN** [timmyRS/Universal-Bypass#430]
-Bypass the two "click to buttons"-
Usual process:
1. Opens the mirrorcreator link
2. There's a "Click to view the file links". click that...
3. Mirror sites list appear. click that...
4. Then another "Click here to visit the file page on _____"

Please make it so the UB clicks/bypass those buttons automatically.

i use adsbypasss userscript for that but, typically there's this adlinks before the mirrorcreator link the uploader adds, and i found that it conflicts with UB. UB has better performance but the userscript overrides the process when bypassing the adlink. 
That's why it would be great if you can approve of my request, then i won't have to use/enable the slow performing userscript.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by traitorAIZEN** [comment]
https://www.mirrored.to/files/USO9AHJ8/Araburu_09_SD_HS_ACB.mkv_links
