### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Boyrules** [timmyRS/Universal-Bypass#431]
hello sir im trying to add timer in before-navigate.js  and or crowd-bypassed.js
my code is 		setTimeout(function () {
			location.href=params.get("target")
			}, 10000);

i need help how to add this code in before-navigate.js i want to wait 10 sec before going to destination site . please help me sir

**Comment by Boyrules** [comment]
Please don't close this issue just let me know how can I do this please sir

**Comment by timmyRS** [comment]
Why would you want that?

**Comment by Boyrules** [comment]
Hello sir . I want it because when ever link is bypass destination website says don't bypass url so I want to wait 10 sec before going to destination url . Please please please help me how I can do it ..

**Comment by Boyrules** [comment]
I'm finding a way to wait 10 sec before going to final destination from so long with no luck .

**Comment by timmyRS** [comment]
Can you provide me with a link where that happens?

**Comment by Boyrules** [comment]
It's happening on a https://clickbits.io/ on  this website . When ever instantly take me to destination is checked click it's.io says don't bypass link and there r other sites just like clickbits.io  so plz help me sir with it .

**Comment by Boyrules** [comment]
And sir plz let me know ur btc wallet address i want to donate some of btc sat for your great app universal bypass . Thanks

**Comment by Boyrules** [comment]
I have tried adding setTimeout in before-navigate.js and crowd-bypassed.js but it breaks extension .  How I can add setTimeout to before-navigate.js and  crowd-bypassed.js without breaking it

**Comment by timmyRS** [comment]
Can you provide an example link, where I can see your issue in action, so I can fix it?

Also, you can donate to `1He11shSCygUZay6TfBcKD7Rc5AgVvXP9K`

**Comment by Boyrules** [comment]
Sir it won't show u error even if I provide u link because it only act when new short link created bypass instantly . When ever (instantly take me to destination) option is check . So it's not an issue I just want to modify universal bypass crowd-bypassed.html and before-navigate.html in such a way that before going to link it waits 10 second .

**Comment by Boyrules** [comment]
I have send  40000 btc sat to 1He11shSCygUZay6TfBcKD7Rc5AgVvXP9K

**Comment by Boyrules** [comment]
Will donate more in future thanks for ur great extension

**Comment by timmyRS** [comment]
I don't understand your issue here. Are you trying to use the site to short your own links?

**Comment by timmyRS** [comment]
I could make a new option for that.

**Comment by Boyrules** [comment]
It would be great if u do that for me .

**Comment by RaveN0X87** [comment]
if you wait here for at least 5 seconds. the site will not detect shortlink bypass and use macro applications such as jitbit macro recorder to auto click visit shortlink
![Annotation 2019-09-10 203501](https://user-images.githubusercontent.com/39649317/64618639-d502c200-d40a-11e9-927e-59600a4cb8e0.png)

**Comment by Boyrules** [comment]
I'm already using auto clicker software on win 7 And auto clicker app on my android but I need to monitor it other wise it stops some time so I'm finding way to do itself in chrome browser . I have tried tampermonkey with no luck tried editing before-navigate.js , crowd-bypassed.js , before-navigate.html and crowd-bypassed.html but it breaks extension .

**Comment by Boyrules** [comment]
![Screenshot_20190910_191328](https://user-images.githubusercontent.com/54093031/64621367-2eff8980-d403-11e9-910e-fb6ff2acca29.jpg)

**Comment by timmyRS** [comment]
The new "Take me to destinations after x seconds" option is done. However, I'll give the translators a couple of days to translate the new strings before releasing Universal Bypass 11.0.

**Comment by Boyrules** [comment]
thank u so so so much sir . im so happy right now  . i was finding a way from so long , its working great .  thank u so so much  again . u r realy great sir .
