### ISSUE TITLE
Chrome Incognito: Requests to the server have been blocked by an extension.

### ISSUE THREAD

**Issue by Kenifornication** [timmyRS/Universal-Bypass#433]
Hi,

Only a few days ago this problem started happening with me on Chrome (v76.0.3809.132) in Incognito mode, whenever I click a link that is supported by UB (e.g. one of the [example links](https://universal-bypass.org/example-links)), an error screen greets me saying:
```
aihomhdbhpnpmcnnbckjjcebjoikpihj is blocked
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT
```
I tried again with all extensions disabled except UB and the same problem persists

can you look into it, please? how can I provide you with a log if necessary?

**Comment by timmyRS** [comment]
The issue should already be fixed in the current dev version.
