### ISSUE TITLE
Move Options

### ISSUE THREAD

**Issue by Sopor** [timmyRS/Universal-Bypass#434]
Could you add the `Options` here
![image](https://user-images.githubusercontent.com/5789283/64644065-18acfa00-d412-11e9-81dc-e0b586a458d1.png)

instead of in the three dots menu?

As you can see here the three dots menu is not visible after i open UB from the extensions list
![image](https://user-images.githubusercontent.com/5789283/64643968-e6030180-d411-11e9-967e-63030511f4e3.png)

and this is a bit confusing so it is not always obvious that the `Options` is in that menu. I don't know why i need to scroll up to see it. Bug in Firefox?

**Comment by Sopor** [comment]
And why not add something to the `Release Notes` too instead of leaving it empty :)

**Comment by timmyRS** [comment]
That's just how firefox chooses to organize it. Also, I used to add release note, but I found it not worth it since it's only for that version and it's all on https://universal-bypass.org/changelog anyway.

**Comment by Sopor** [comment]
But other extensions do have the Option as i show in the first picture, so why can't you do the same?

**Comment by timmyRS** [comment]
Because the options are in their own page which has requirements such as the Ace editor for the custom bypasses.
