### ISSUE TITLE
Bug mm1.ink shorteners

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#442]
https://freelitecoin.vip/shorten/CBhrssd14dq

crowd bypass work properly but every time we enter again the link always changes

**Comment by Boyrules** [comment]
Same thing happens for me it's not bypassing it . crowd bypass some time works . ( freelitecoin.vip )

**Comment by timmyRS** [comment]
I can bypass the 10 second wait before the captcha, but after that I'm afraid it's all backend validation, so no bypassing it. Also, from what I take it's a website giving you free litecoins. I would expect them to not like to be bypassed.

**Comment by Boyrules** [comment]
How to bypass 10 second before captcha ?

**Comment by timmyRS** [comment]
By waiting for the next Universal Bypass release.

**Comment by timmyRS** [comment]
If you're really impatient, put this in your custom bypasses:
```Javascript
domainBypass("btcleets.xyz",()=>{
	ensureDomLoaded(()=>{
		$=()=>({attr:(n,v)=>safelyNavigate(atob(v))})
		goto()
	})
})
```

**Comment by Boyrules** [comment]
Thank u sir for quick reply . Will try it and reply

**Comment by Boyrules** [comment]
Sir can u also make timer bypass for https://dutchycorp.ovh/sh/CBfhtwv1bpn?verif=eZCW4

**Comment by timmyRS** [comment]
Which timer?

**Comment by Boyrules** [comment]
https://dutchycorp.ovh/sh/CBfhtwv1bpn?verif=eZCW4  before going to this link it loads new page which has timer on it .

**Comment by timmyRS** [comment]
Pretty sure that's already bypassed by crowd bypass.

**Comment by Boyrules** [comment]
Timer is not bypassing for me 
![Screenshot_20190914_142818](https://user-images.githubusercontent.com/54093031/64905900-f78f2680-d6fb-11e9-96bd-ad502f31e05b.jpg)

**Comment by timmyRS** [comment]
That looks like Chrome for Android... there's no Universal Bypass for that.

**Comment by Boyrules** [comment]
I'm using yandex for android

**Comment by timmyRS** [comment]
I don't see that timer, and I hate that ad-infested site.

**Comment by Boyrules** [comment]
I have already bypassed that link on yandex browser so its not showing on yandex so I'm using chrome

**Comment by Boyrules** [comment]
I'm getting  timer on new page before that shortlink .

**Comment by Boyrules** [comment]
Sir can we bypass this timer https://100count.net/first_page/first_page.php

**Comment by KagaKouko99** [comment]
@timmyRS another domain https://technoresults.xyz/?slHash=CBhrssd14dq
