### ISSUE TITLE
Request mawataki.com

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#448]
https://mawataki.com/?id=RU1Ub0xzMm5qYVV6dENBWnVBenlUdDhkVHpXRUlKZmt2VXFLMy9hYitodFhhTmVYTmgzUUR0L1BkaDJ5elN5bnNWanBuWWx0Uyt3Y3FNL04zUnVYSExuS2lMQTVidTk4WWVmWnBLY0FKL2c9

https://mawataki.com/?id=cnVwdnk3aXZsejM5bGozdG5OOGFqc0diNzlFRHVNNnpMUGdVSGpVenZRM2FNRXZNdEVQRjFHNDFrVDExdEkxcg==

Source : 
https://kazefuri.web.id/the-great-ruler-ep-5/

**Comment by timmyRS** [comment]
Duplicate of #193
