### ISSUE TITLE
Timer for crowd source destinations

### ISSUE THREAD

**Issue by Blahx** [timmyRS/Universal-Bypass#458]
Currently, we have timers to automatically take us to destinations for normal bypass.

Can we also include that for crowd source bypass as well?

**Comment by timmyRS** [comment]
No. You need to be able to click "Was this not correct?" You can choose to automatically open the destination in a new tab, tho.

**Comment by Blahx** [comment]
But you recently added "Automatically open crowd-sourced destinations in a new tab." yes?
Could you not add in "after x seconds" like the other option?

**Comment by timmyRS** [comment]
Unfortunately, that would be a bit more complex to do (mainly because Firefox sucks). Also, what would be the use case for that?

**Comment by Boyrules** [comment]
> Currently, we have timers to automatically take us to destinations for normal bypass.
> 
> Can we also include that for crowd source bypass as well?

U need to edit extension by yourself if u need timer on crowd bypass page.

**Comment by Boyrules** [comment]
Edit ur extension crowd-bypassed.js 
let params=new URLSearchParams(location.search)
if(params.has("target")&&params.has("back"))
{
	let i=document.querySelector('[data-message="crowdBypassedInfo"]')
	i.innerHTML=i.innerHTML.replace("%",'<a></a>')
	let a=i.querySelector("a")
	a.setAttribute("target","_blank")
	a.href=a.textContent=params.get("target")
	document.getElementById("ignore").href=params.get("back")+"#ignoreCrowdBypass"
	
	span=document.querySelector("[data-message='beforeNavigateTimer']")
	span.innerHTML=span.innerHTML.replace("%","<span></span>")
	span=span.querySelector("span")
	brws.storage.sync.get(["navigation_delay"],res=>{
		let secondsLeft=res.navigation_delay,
		timer=setInterval(()=>{
			span.textContent=--secondsLeft
			if(secondsLeft<=0)
			{
				location.href=params.get("target")
				clearInterval(timer)
			}
		},1000)
		span.textContent=secondsLeft
	})
}
else
{
	history.back()
}

Step 2 add in crowd-bypassed.html


<!DOCTYPE html>
<html>
<head>
	<title data-message="crowdBypassed"></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<h1 data-message="crowdBypassed"></h1>
	<p data-message="crowdBypassedInfo"></p>
	<br>
	<p><span data-message="beforeNavigateTimer"></span></p>
	<br>
	<p><a id="ignore" href="#" data-message="crowdBypassedIgnore"></a></p>
	<script src="base.js"></script>
	<script src="crowd-bypassed.js"></script>
</body>
</html>

**Comment by Boyrules** [comment]
Step 2 add in crowd-bypassed.html

<!DOCTYPE html>
<html>
<head>
	<title data-message="crowdBypassed"></title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="style.css">
</head>
<body>
	<h1 data-message="crowdBypassed"></h1>
	<p data-message="crowdBypassedInfo"></p>
	<br>
	<p><span data-message="beforeNavigateTimer"></span></p>
	<br>
	<p><a id="ignore" href="#" data-message="crowdBypassedIgnore"></a></p>
	<script src="base.js"></script>
	<script src="crowd-bypassed.js"></script>
</body>
</html>

**Comment by Blahx** [comment]
> Unfortunately, that would be a bit more complex to do (mainly because Firefox sucks). Also, what would be the use case for that?

Some website and surveys have detects if you bypass the shortlinks when you go to the destinations immediately, which is why having the option for the timer like other option would help a lot.

I am using Chrome, so I had assume it wasn't hard to add in that function, but if it is that much of a hassle, then I understand.

**Comment by Boyrules** [comment]
I can help u in adding that feature in crowd  bypass option but u need to know how to add extension to chrome manually .  If u do I can help you

**Comment by Boyrules** [comment]
Here is the edited link of universal bypass add manually to ur chrome 
https://drive.google.com/file/d/1-x4DU1CD2qcUL2BPknQKnB0W5NYvIAXA/view

**Comment by Boyrules** [comment]
I have added timer in crowd bypass page . Edited files in this version is crowd-bypassed.js  and crowd-bypassed.html to add timer .  Set timer in options 10 or 15 sec it will work for both crowd bypass page and before navigate page .
