### ISSUE TITLE
Request ceklinku.xyz

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#464]
https://ceklinku.xyz/?id=cThyWjJxYzhLSmFXMkhSYkVTaGdsMGFYV0NyTmphRFlPWXI1Y201V0YwNy9BWTdKSThxdUlFRW84V1lBdzNncUIzZUJXVHdNenJjZWZmSzZMRGltM3BiWkJTSkhyaXRhdjVOdHhmQTQvWkU9

https://ceklinku.xyz/?id=MmpZcVhabXdZUnAzZHE0WHhjYjdSNFpCc2puM0l2cG14NTQxb3BSWFVReTVtd2x6T1c4NUJCUGt5ckl1WG1ZYkFuSXhzdGN3VmxBLzdsWkFUS3pmNEE9PQ==

Source : 
`https://hinime.com/kanata-no-astra-sub-indo/`

**Comment by timmyRS** [comment]
Duplicate of #193 

You should know this by now. Please just add a comment there.

**Comment by WaferNabati** [comment]
I can't distinguish which can or cannot be bypassed. like this case https://github.com/timmyRS/Universal-Bypass/issues/453

**Comment by timmyRS** [comment]
In that case the "?r=aH" part made me know it's base64-encoded, specifically the "aH". When in doubt, just open an issue, not that it's a big deal.

**Comment by IllyaSan** [comment]
aw, it interesting to do
