### ISSUE TITLE
SoraLink's Bypass

### ISSUE THREAD

**Issue by IllyaSan** [timmyRS/Universal-Bypass#465]
Здравствуй!

uh this is my script for SoraLink v3.x.x
I think you can use it, and sorry for bad format, I'm pretty new in javascript
and I love to use hex variable name because its beautiful

https://pastebin.com/qGP3nTpw

tested on :
Issue 394,403,404,405,406,407,417,418,448,451,464
#394 #403 #404 #405 #406 #407 #417 #418 #448 #451 #464

**Comment by timmyRS** [comment]
From what I see it waits before navigating, which I hardly call a bypass. Also, not a big fan of the obfuscation.

**Comment by KagaKouko99** [comment]
why not add it to UB for a temporary solution. currently many sites use soralink

**Comment by IllyaSan** [comment]
@timmyRS its waiting because if thats directly redirect it will occurs bad request,
And also its not obsufcated

**Comment by Arsindy** [comment]
@IllyaSan thank u so much. it works for bypassing pahe.in safelink

**Comment by Arsindy** [comment]
@IllyaSan the script doesn't work anymore on `https://pahe.in/avengers-endgame-2019-bluray/`
please update
