### ISSUE TITLE
[Site Request] adssuper.com

### ISSUE THREAD

**Issue by csalles1** [timmyRS/Universal-Bypass#466]
I would like to add a bypass to: https://www.adssuper.com/instagram/campanha.php?id===wauFGbi9lI9QXZnJXY0BiIFNTQxIjNCFUQ4YEO2EURxEENDljMBVjM1ITMyEzN4MkM2MEOCNTMFpDapRnY64mc11Dd49jO0VmbnFWb&ref=comandofilmes&titulo=VHJpbG9naWEgTyBIb2JiaXQg4oCTIFZlcnPDo28gRXN0ZW5kaWRhIEJsdVJheSAxMDgwcCBEdWFsIMOBdWRpbyAmIzgyMTE7IFRvcnJlbnQgKDIwMTIsIDIwMTMsIDIwMTQp

From what I've researched, this is the real destination URL part: id===wauFGbi9lI9QXZnJXY0BiIFNTQxIjNCFUQ4YEO2EURxEENDljMBVjM1ITMyEzN4MkM2MEOCNTMFpDapRnY64mc11Dd49jO0VmbnFWb

But it's reversed and base 64 encoded. Similar to issue #182

**Comment by timmyRS** [comment]
It's not, and it seems like the site is offline.

**Comment by csalles1** [comment]
Well, it's working here.

It gets redirected to https://www.mastercuriosidadesbr.com/some_ad_url and the real link is on this page.

I took _wauFGbi9lI9QXZnJXY0BiIFNTQxIjNCFUQ4YEO2EURxEENDljMBVjM1ITMyEzN4MkM2MEOCNTMFpDapRnY64mc11Dd49jO0VmbnFWb_ 

reversed to _bWFnbmV0Oj94dD11cm46YnRpaDpFMTNCOEM2MkM4NzEyMTI1MjVBMjlDNEExRUE2OEY4QUFCNjIxQTNFIiB0YXJnZXQ9Il9ibGFuaw_

decoded and got 
**magnet:?xt=urn:btih:E13B8C62C871212525A29C4A1EA68F8AAB621A3E" target="_blank**

This is almost the same thing that appears on the final page. The only difference is the _target_ part.
