### ISSUE TITLE
Extension does not jump to a link shortener.

### ISSUE THREAD

**Issue by gcorderito** [timmyRS/Universal-Bypass#467]
I just want to report a page of a link shortener in which Universal Bypass does not detect it.
When I go to this link: https://n9.cl/UEu3 takes me to a page where I have to click to continue to the other page, and that page has misleading advertising.
The shortening is as follows: https://n9.cl/

**Comment by timmyRS** [comment]
Your example link gives me an error and when I created a link myself ( https://n9.cl/w48v ) it puts me to my destination automatically.
