### ISSUE TITLE
Ouo.today

### ISSUE THREAD

**Issue by ghajini** [timmyRS/Universal-Bypass#468]
@timmyRS
Request to support bypass for

`https://ww1.ouo.today/?oID=41450&cr=aHR0cDovL2pldGxlZWNoLm5ldC9yZWRpci5waHA/aWQ9aTNFX243M3JVeEpIa3RTMkxqbWFtaHIxQW8xNmFyYkNQcDhfSC1vXzR5N05FNmZMVzN4QndR`

**Comment by timmyRS** [comment]
Seems like this is IP-locked, where did you get that link from?

**Comment by ghajini** [comment]
I got from leech site
STR=

1.visit `jetleech.net`

2. Enter any site you want to leech
eg 

`https://www93.zippyshare.com/v/pMq3pyjk/file.html`

3. Click download and follow subsequent steps, you will get above link shortener

**Comment by timmyRS** [comment]
1. I don't see anything to be bypassed on ouo.today
2. Isn't it faster to just download the file form zippyshare instead of using that shit service?

**Comment by ghajini** [comment]
Hello @timmyRS
I want to bypass `ouo.today` because site asking me to allow `push notifications` so ads, I can't proceed further without allowing push notifications......

`http://prnt.sc/p9hcn6`

With zippyshare I just gave you filehost example, there are many file hosts that I want to generate premium link via `jetleech.net` eg uploaded.net,userscloud.com etc.....

Also pls clear cookies, data if want to reproduce above problem......
We are having trouble fixing `https://github.com/LiCybora/NanoDefenderFirefox/issues/152`

`https://github.com/uBlockOrigin/uAssets/issues/5890`

Thatswhy I want to bypass site......

If you are not going to add, can you provide userscript version that I can enter into violentmonkey.....'😫

**Comment by 0x6c4bf2e1** [comment]
@ghajini 
```
location.replace(atob(new URLSearchParams(location.search).get("cr")));
```

**Comment by ghajini** [comment]
I don't get, can you provide userscript?

**Comment by 0x6c4bf2e1** [comment]
@ghajini 
```
// ==UserScript==
// @name         ouo today
// @match        *://ww1.ouo.today/*
// @run-at       document-start
// @grant        none
// ==/UserScript==
(()=>location.replace(atob(new URLSearchParams(location.search).get("cr"))))()
```

**Comment by ghajini** [comment]
Amazing would you contribute here
`https://github.com/LiCybora/NanoDefenderFirefox/issues/152`

`https://github.com/uBlockOrigin/uAssets/issues/5890`

**Comment by ghajini** [comment]
Version 11.3 doesn't work at this URL

`https://ww10.ouo.today/?cr=aHR0cDovL3VsdGltYXRlLnR1cmtkb3duLmNvbS9saW5rLnBocD9saW5rPWFIUjBjSE02THk5Nk1ta3VZMjl0TDI5a1IweHhSMHQ2&oID=82904`
