### ISSUE TITLE
Bug teknosafe.kertashitam.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#470]
https://teknosafe.kertashitam.com/linkteknolink/safelinkscript.php?lnD7tE92Yw4QuXh74=38937

Source :
`https://www.kertashitam.com/animepostseries.php?animepost=12202`

**Comment by timmyRS** [comment]
I don't see anything to be bypassed there.

**Comment by Recehan-Slayer** [comment]
need an update
```
https://teknosafe.info/linkteknolink/safelinkscript.php?lnD7tE92Yw4QuXh74=40631
https://teknosafe.info/linkteknolink/safelinkscript.php?lnD7tE92Yw4QuXh74=40633
```
