### ISSUE TITLE
Linkvertise bypass is not working.

### ISSUE THREAD

**Issue by LiterallyCJ69** [timmyRS/Universal-Bypass#472]
Doesn't work anymore, I tried many links.

P.S. Thank you for this awesome extension!

**Comment by WaferNabati** [comment]
https://linkvertise.com/26117/429.80947265732027/dynamic?r=aHR0cDovLzE2My4xNzIuODMuMTQ1L2RlYi9hcGkvYXBpMDUvP2Fkcz1hSFIwY0Rvdkx6RTJNeTR4TnpJdU9ETXVNVFExTDJSbFlpOWhjR2t2WVhCcE1EUXZQMlJzUFdRd09EUTJNMlUyTXpVd1l6Tm1NQT09

**Comment by GameOverYoutuber** [comment]
Universal Bypass Linkvertise Not Working

**Comment by Gagels** [comment]
It got fixed :(
