### ISSUE TITLE
Request bypass link-to.net

### ISSUE THREAD

**Issue by wernser412** [timmyRS/Universal-Bypass#477]
url:
https://link-to.net/20540/aaaaa

bypass redirect:

https://proxo.wtf/ProxoKeyKey/BypassDetected.php

url no bypass:

https://proxo.wtf/ProxoKeyKey/

**Comment by timmyRS** [comment]
Please use the latest version of Universal Bypass (11.3).

**Comment by 0x6c4bf2e1** [comment]
@timmyRS 
Please use `location.href` or `location.replace`, instead of `safelyNavigate` to prevent "Bypass Detected"

**Comment by timmyRS** [comment]
I'm going to try to prevent that detection, instead of using such methods. I'm keeping track of it in #478.

**Comment by wernser412** [comment]
> Please use the latest version of Universal Bypass (11.3).

not work Universal Bypass (11.3) detected bypass in the web.
