### ISSUE TITLE
Present "referer" header to destination

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#478]

**Comment by ikancupang** [comment]
It looks like the referer header isn't working right now, so this is the cause of the old way of linkvertise bypass not working.

**Comment by timmyRS** [comment]
The linkvertise bypass is working in 11.18, Chrome are just being bitches and delaying the publishing.

**Comment by ikancupang** [comment]
The old way of linkvertise bypass should still work, but the problem is `details.requestHeaders.push` doesn't work properly, please check in `Request Headers`, "referer" doesn't exist.
