### ISSUE TITLE
Universal Bypass is not supposed to bring you here. Please open an issue or send me an email.

### ISSUE THREAD

**Issue by hieunhoo** [timmyRS/Universal-Bypass#485]
https://www.youtube.com/watch?v=88V096nHCYg
please help
https://www.youtube.com/redirect?v=88V096nHCYg&redir_token=_XH2IuRfXGvveJcANX_aF_VE8wp8MTU3MDAxMTAzNUAxNTY5OTI0NjM1&event=video_description&q=http%3A%2F%2Fbit.ly%2F2knjJhx

![2019-10-01_171626](https://user-images.githubusercontent.com/48126508/65953955-44e6f400-e46f-11e9-8d89-dbeaa7c8abaf.png)
![2019-10-01_171638](https://user-images.githubusercontent.com/48126508/65953973-4e705c00-e46f-11e9-8134-1880df9f3fd4.png)

The link above is the bit.ly link on youtube when I click on the bit.ly link on youtube, that's it, but when copying the bit.ly link is normal

Bit./ly
http://bit.ly/2knjJhx

**Comment by timmyRS** [comment]
Make sure you're using UB 11.4.1.

**Comment by hieunhoo** [comment]
> Make sure you're using UB 11.4.1.

No, I have to reload the page for it to redirect
