### ISSUE TITLE
Request wanhealth.me

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#490]
https://www.wanhealth.me/?id=VDFQRFhkSVBJQW8vSzNORmhrdHlHSy81TzVsSUpiTUVDSHpWaGJjakpETm5sYjVDckFiQnBUQTQ4a2FBSmVhN3Bna0E4eHZ0cUw0MW1Ld3NVUGdHaVZxOE9zcmRLWjROaTVTZ0dzWmVvYXc9

https://www.wanhealth.me/?id=bDVsUXBCU1I2c1F4Um02T3hNOEVONkhNZEswUE9LVlVDZEtxL0RaSnBMU0RjT0RVSEZUMmx3WlNtNThObHg4NA==

Source : 
`https://www.animebatch.id/hataage-kemono-michi-episode-1-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Duplicate of #193
