### ISSUE TITLE
Non-workening shorteners

### ISSUE THREAD

**Issue by vertigo220** [timmyRS/Universal-Bypass#492]
Here are some shorteners I had trouble with last night. Ones with (*) show a "This domain is owned by *!" when going to their main pages, and they appear to all be run by the same company.

skip.az
oko.sh (lksh)
ckk.ai (hrink)
pewwnews.com (UrlShortx)
ouo.io
cutlinks.pro *this one is especially annoying
icutlink.com
yourlearningfactory.com (iLinkShort.com) - Sometimes works, sometimes doesn't, which appears to be the case for some others as well. I'm not sure if that's because this one and the others it happens with only work with crowd-bypass and sometimes they haven't been done before by someone else and sometimes they have.

Speaking of the crowd-bypass, I assume this happens automatically, so if a link doesn't work and I do it manually, it gets added in the background so it'll work for others that follow the same link?

**Comment by vertigo220** [comment]
Closed? Were they fixed? What about my question about crowd-bypass?

**Comment by timmyRS** [comment]
Keep your issues to one URL shortener that isn't bypassed with an example link. Chances are, it's already bypassed. And your assumption about crowd bypass is correct.

**Comment by vertigo220** [comment]
Thanks. There aren't any instructions on how to submit, so I wasn't sure. I suspected I may need to include full links, but didn't think of it until after I collected the URLs.
