### ISSUE TITLE
Bug skip-me.top

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#494]
https://skip-me.top/cYaFas1  should be `https://www78.zippyshare.com/v/DtcDd8aZ/file.html`
https://skip-me.top/oRJEdYhR8  should be `https://drive.google.com/file/d/15tz71hLrRWyV8MSmBWN366xIGlmRbPqn/view`

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by timmyRS** [comment]
Then you press "Was this not correct?"

What a miracle this crowd bypass!
