### ISSUE TITLE
Request | Need to fix link-to.net or adverse or

### ISSUE THREAD

**Issue by MIHAIdavid22** [timmyRS/Universal-Bypass#495]
It seems link-to.net or "adverse" has updated their site and now universal bypass no longer works.
the link to one of said adverse or link-to.net
[https://link-to.net/20540/aaaaa](url)

this is what happened when i tried to use universal bypass.
[https://i.imgur.com/Rc8bIGl.png](url)
the link in the image can be found here:
[https://universal-bypass.org/bypassed?target=https%3A%2F%2Fproxo.wtf%2FProxoKeyKey%2F&referer=https%3A%2F%2Flink-to.net%2F20540%2Faaaaa](url)

**all i request is an update to fix link-to.net or adverse because they got to have annoying 1 minute unskippable videos**

**Comment by timmyRS** [comment]
Make sure you're using UB 11.4.3.
