### ISSUE TITLE
Request wanhealth.me

### ISSUE THREAD

**Issue by dedsec404** [timmyRS/Universal-Bypass#501]
Safelink URL : https://www.wanhealth.me/?id=Z0JpSGx0OXNBNW9HNUNFQWwxOVY1b3pNUUVFTmxZOGhHY0E1Z0tzUDRTU2xWNFp2THA5ZEI1TnRQYklVTjdaZytnU1hDT0c5SXJ2TDcwbWxhb2Y2Mng2eUhoZkRGQ3FIWjluTHRJbk1SWm89

**Comment by timmyRS** [comment]
Duplicate of #193
