### ISSUE TITLE
kiwi browser extension universal bypass not working

### ISSUE THREAD

**Issue by amarmanish72** [timmyRS/Universal-Bypass#503]
Universal Bypass is not supposed to bring you here. Please open an issue or send me an email.
![Screenshot_2019-10-10-10-03-28-763_com kiwibrowser browser](https://user-images.githubusercontent.com/56379034/66539395-5aca7800-eb45-11e9-81b1-170c1be7ad19.png)

**Comment by timmyRS** [comment]
Universal Bypass is not officially available for the kiwi browser, so please don't report issues you might have when using an unsupported browser.

**Comment by RaveN0X87** [comment]
@amarmanish72 works really well for me using kiwi browser latest version and Universal Bypass latest version

**Comment by RaveN0X87** [comment]
the latest version is not compatible. but the version before October release still works fine for me

**Comment by hjyoung1** [comment]
Yes, last working version is 11.3.

**Comment by RaveN0X87** [comment]
I mean is not the UB version but the kiwi browser version below October

**Comment by 3xploiton3** [comment]
Now doesn't work
