### ISSUE TITLE
[Request] gsu.st (Domain prox77.com)

### ISSUE THREAD

**Issue by Cyberavater** [timmyRS/Universal-Bypass#507]
Example Link: https://gsu.st/htxm

**Comment by Cyberavater** [comment]
Crowd+auto click 2 times after that is not working.

**Comment by Cyberavater** [comment]
Crowd Bypass (at the beginning) not yet implemented.
Example Link: https://gsu.st/hES4

**Comment by timmyRS** [comment]
I don't see how crowd bypass could be implemented there. If you don't want to do the captcha, try using https://github.com/dessant/buster
