### ISSUE TITLE
shrinkurl.org does not skip timer

### ISSUE THREAD

**Issue by PBJF** [timmyRS/Universal-Bypass#509]
After solving the captcha, shrinkurl.org's timer is still there, making me wait.

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by PBJF** [comment]
I'm not asking to solve the captcha, but just skip the timer like in the video on the site.

**Comment by timmyRS** [comment]
The timer can't be bypassed because the site uses backend validation to make sure you've actually waited.
