### ISSUE TITLE
Chain on different domains

### ISSUE THREAD

**Issue by PBJF** [timmyRS/Universal-Bypass#522]
bitcoinfaucet,fun
coindice.win
freebitcoin.win

form a chain. Could they all be bypassed?
(beware: popups)
Demo:
https://bitcoinfaucet.fun/claim/FBuso3YJ0Wen

**Comment by timmyRS** [comment]
Since this seems to be from a faucet site, I expect them to make sure that you have actually gone through that process, since they're paying you for it. Anyway, you can try to add this as a custom bypass and tell me if you get an error:

```JavaScript
ensureDomLoaded(()=>ifElement("button#makingdifferenttimer[onclick^='window.location.replace']",b=>b.click()))
```

**Comment by PBJF** [comment]
Meanwhile my editor won't autosave. FF 69.0.3

**Comment by timmyRS** [comment]
I just pasted that code into the custom bypasses section, immediately closed the options, and even then it saved.

**Comment by PBJF** [comment]
Works on Chrome, it's just Firefox acting weird with extensions. Every \*\*\*Monkey and uBo stopped working recently. :|

**Comment by PBJF** [comment]
It works

**Comment by timmyRS** [comment]
I wanted to know if it works for you before I actually add it to UB, until then, this issue is not closed. 🙄
