### ISSUE TITLE
Request safe.intipanime.com

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#524]
Example link : 
http://safe.intipanime.com/?id=NVdzMVpqRGVoRE12NUdtZHRHM2I2S2NndlRDU0U0cGorQnM1OEp6ZTNaWUt5Qk9ucHAxSGRHVGhxZG9kcy94UDhGSEh4L1FXdythdUpZZ1ZxVS81Sk1MRi9QQjdKYVZsT01Gb3VvQTFKdnRUNVptRWFadU5Kc3VlZUgyY1RvM00=

http://safe.intipanime.com/?id=NVdzMVpqRGVoRE12NUdtZHRHM2I2S2NndlRDU0U0cGorQnM1OEp6ZTNaWXdBRFE5VHF2cVlpMDZSMXczMmFPajZndFIxNkJWRGxveTFXQ1RGaWdFQjVKS3BMYW5wQmhUVzJaQWpNYmg3Y2s0VGtXOVVFTlRDZncxL3BkbkVPVGk=

Source link : 
`https://bakadame.com/lord-el-melloi-ii-sei-no-jikenbo-rail-zeppelin-grace-note-sub-indo/`

**Comment by timmyRS** [comment]
Duplicate of #193
