### ISSUE TITLE
PSARips

### ISSUE THREAD

**Issue by NikeAddida** [timmyRS/Universal-Bypass#534]
Hello, all the shortenters from the site PSARips.eu are blocked. Please fix it.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by NikeAddida** [comment]
Sure,
https://universal-bypass.org/crowd-bypassed?target=https%3A%2F%2Fget-to.link%2Fpennyworth-s01e09-alma-cogan-720p-10bit-webrip-2ch-x265-hevc-psa674%2F&referer=https%3A%2F%2Fckk.ai%2FKOisXl6
[image: image.png]

Στις Σάβ, 26 Οκτ 2019 στις 5:23 μ.μ., ο/η Tim Speckhals <
notifications@github.com> έγραψε:
