### ISSUE TITLE
lompat.in another link

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#541]
http://ryukanime.lompat.in/?go=0OoL1HM6Ly91c2Vyc2Nsb3VkLmNvbS84YnBtOGQ0ZWR3cjk=
supposed to `https://userscloud.com/8bpm8d4edwr9`

**Comment by timmyRS** [comment]
That's an interesting custom base64 where only the first 5 characters seem to deviate. Could you provide more example links to try against my current idea?
```JavaScript
atob("aHR0c"+"0OoL1HM6Ly91c2Vyc2Nsb3VkLmNvbS84YnBtOGQ0ZWR3cjk=".substr(5))
```

**Comment by WaferNabati** [comment]
This safelink from https://id.loncat.in/ and users can create their own private safelink like this `http://st.loncat.in/1cgq`
but i don't really understand about programming language
