### ISSUE TITLE
Request zaqe.xyz

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#544]
http://zaqe.xyz/?id=bkI1eDFFYkRwbFptYmxidEpmekpGbUZlMHlOdmZKcXhpbnFkVmovbmJUZ2t5RFArN0F0cGZKTVpkaldRZ0wzY2RwSDYvRGhkUEZuTmNtSEJZMExqQjhEcDArcU9uaEZMNDNILzE0K0JCalU9

http://zaqe.xyz/?id=cFFHR2hWWEpnalp6K3BLRmxDRjhNa2FPWFBEMGVVUmtBTklpWlZRSEZZRT0=

Source :
`https://wizardsubs.com/2019/10/16/mv-izone-suki-to-iwasetai/`

**Comment by timmyRS** [comment]
Duplicate of #193
