### ISSUE TITLE
Request arahin.space

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#545]
https://arahin.space/?id=MnRJNXpXTlZXWGEwM0Jma3I1cGsvU3hMNENPMk5ZZ2QrOVViQlk0NXlXMD0=

https://arahin.space/?id=NWVkNHkzVEtZd1hBV0ZibS9BbjRuUUR6VHhxU3Rrd0trKzRiZHJCUjlIaVYzUEIwS2lPSWx5M3VGY3psMmhXOU8xcmlHQUlLTU9BaDdXZm1VQlIxTGc9PQ==

Source :
`https://haoshoku.net/dragon-ball-heroes-episode-17/`

**Comment by timmyRS** [comment]
Duplicate of #193
