### ISSUE TITLE
please add

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#550]
add https://mirrorace.com/m/1zf2c auto click like this one https://mir.cr/1BGGSEF7

**Comment by Arsindy** [comment]
i don't know what's going on. but now it doesn't seem to work please update.
https://mirrorace.com/m/Tlxi

**Comment by timmyRS** [comment]
This bypass will be with you in UB 11.9

**Comment by Arsindy** [comment]
doesn't work for me using universal bypass version 11.9

**Comment by Arsindy** [comment]
@timmyRS please update. doesn't work again with version 11.10

**Comment by Arsindy** [comment]
update please.

**Comment by Arsindy** [comment]
@timmyRS need update again
