### ISSUE TITLE
Adfly (larati.net, eunsetee.com)

### ISSUE THREAD

**Issue by cygvis** [timmyRS/Universal-Bypass#552]
**note: * are unique URL parameters**

i have AdFly links like these sometimes:
http://larati.net/*
http://eunsetee.com/*
(any other known names that adfly uses?)

and they redirect to one of these (usually):
http://exe.io/*
https://bc.vc/*
https://ckk.ai/*

**Comment by timmyRS** [comment]
Adf.ly and all the other links you've provided are already bypassed by Universal Bypass.
