### ISSUE TITLE
Request mixloads.com

### ISSUE THREAD

**Issue by JackHack96** [timmyRS/Universal-Bypass#554]
Bypass not working on https://mixloads.com/

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by bogachenko** [comment]
`https://mixloads.com/7ubkvwht3ek9` @timmyRS

**Comment by timmyRS** [comment]
Unfortunately, that site uses backend validation to make sure you've actually waited, so it can't be bypassed.
