### ISSUE TITLE
oko.sh

### ISSUE THREAD

**Issue by Cratethief** [timmyRS/Universal-Bypass#555]
Helllo,

I found a few new links. Can you help in bypassing?

https://oko.sh/lEK2nfz
https://oko.sh/yMXxBmGR
https://oko.sh/4LdFzBV9

Thank you for your help

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by ghajini** [comment]
wrong redirects happening

wrong bypass=

`https://oko.sh/TeXibU > https://aii.sh/Dch > https://oko.sh/fwc1 > ​https://ouo.io/5p4G8O > https://hyperdebrid.net/redirect?url=http://free-a3.hyperdebrid.download:2095/d/?file=7836a21cfa&step=1 > http://free-a3.hyperdebrid.download:2095/d/?file=7836a21cfa`

actual bypass = 

`https://oko.sh/TeXibU > https://aii.sh/Dch > https://ckk.ai/LAZGWJ > https://ouo.io/09USF7 > https://hyperdebrid.net/redirect?url=http://free-f2.hyperdebrid.download:2095/d/?file=caec88426e&step=1`

**Comment by timmyRS** [comment]
That's what the "Was this not correct?" button is for.

**Comment by ghajini** [comment]
Yes I know that, but how wrong redirects happening? Any fix for that. ...how to disable crowd bypass

**Comment by timmyRS** [comment]
It's crowd-sourced. Either the real destination changed over time, or someone intentionally reported the wrong destination. If you just click "Was this not correct?" you'll go through the process, this time reporting the correct destination, so the system can give the correct destination to other people. If you don't like the premise of that, you can disable crowd bypass in the options.

**Comment by ghajini** [comment]
Which option is there to disable crowd bypass? 
![IMG_20200214_161027](https://user-images.githubusercontent.com/20338483/74524345-dea5ce00-4f44-11ea-8106-be85bada5b6d.jpg)

**Comment by timmyRS** [comment]
![image](https://user-images.githubusercontent.com/11009697/74524399-3df0e780-4f1f-11ea-8d78-68c05c0b995b.png)

**Comment by ghajini** [comment]
Thanks
