### ISSUE TITLE
It doesn't work for me at cutlinks.pro

### ISSUE THREAD

**Issue by jcvr1994** [timmyRS/Universal-Bypass#566]
You have installed the extension "adskipper", please disabled for get link.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by jcvr1994** [comment]
https://cutlinks.pro/uj5N

**Comment by timmyRS** [comment]
That link doesn't seem to exist (anymore).

**Comment by jcvr1994** [comment]
Disabling the Universal Bypass extension works fine for me

**Comment by MasterIsGaming** [comment]
Yeah same thing like this link https://cutlinks.pro/YDMr Pretty much can't bypass it. 
![image](https://user-images.githubusercontent.com/57578736/68537481-5bf3ee00-0319-11ea-83d1-df58a5f08277.png) This is a screenshot of it

**Comment by timmyRS** [comment]
I get the same message even with Universal Bypass disabled.
