### ISSUE TITLE
wahibirawan.com safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#573]
Example link : 
https://wahibirawan.com/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczQ0grZ0tjTm94WUU2Y1cwODBnOHBmcz0=

https://wahibirawan.com/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczUHhaS21mSmFOOERrUE5RWDdYbWxWTT0=

Source link:
`https://www.oploverz.in/kono-yuusha-ga-ore-tueee-kuse-ni-shinchou-sugiru-06-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Duplicate of #193
