### ISSUE TITLE
[Request] short.pe

### ISSUE THREAD

**Issue by wernser412** [timmyRS/Universal-Bypass#574]
they could create a autoclick para short.pe:

http://short.pe/eOLxUb
![Sin título](https://user-images.githubusercontent.com/53667212/68824909-49a1e900-0666-11ea-9838-a4f980cd13dc.png)

**Comment by timmyRS** [comment]
They use the adlinkfly template and some sites use a captcha there, so auto-clicking that would not be a good idea.

**Comment by wernser412** [comment]
podrias crear un código para diferenciar el tipo o clase de botón contiene la pagina y hacer autockick y si no existiera ese tipo de boton no hacer nada.
