### ISSUE TITLE
[Request/Bug] Lots of new adf.ly links; make them addable

### ISSUE THREAD

**Issue by MulverineX** [timmyRS/Universal-Bypass#579]
Since adfly keeps creating domains a list config in the extension should be added where you can list domains that use the same system as adfly
(Be great if you could add http://cowner.net/ in the meantime though)

**Comment by timmyRS** [comment]
Adf.ly is bypassed regardless of the domain. Their new cowner.net domain, however, is just straight-up broken. Even with no extensions, it doesn't work.
