### ISSUE TITLE
(request) feature instanly redirect to page

### ISSUE THREAD

**Issue by 3xploitzer0** [timmyRS/Universal-Bypass#580]
https://i.imgur.com/Mw2ygjA.png

sir, i want request for add option redirect to page instaly without notification or new tab,

**Comment by timmyRS** [comment]
You can chose to instantly open the destination in a new tab but that page is important because of the "Was this not correct?" button, in case the destination is not correct. It is crowd-sourced, after all.

**Comment by 3xploitzer0** [comment]
ok, how about auto close when i already click destination link,


> 
> 
> You can chose to instantly open the destination in a new tab but that page is important because of the "Was this not correct?" button, in case the destination is not correct. It is crowd-sourced, after all.

**Comment by timmyRS** [comment]
You can't always know that the destination is correct by just looking at
the link.
