### ISSUE TITLE
kontenajaib.xyz safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#582]
Example link :

https://kontenajaib.xyz/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczSlZJTHBtTUNuNU0vQ0hYejBvT1lUOD0=
https://kontenajaib.xyz/?id=TXZXdjVHb3p2Q0pmb3IwdGlVZEczTXhFTyt4THQxVDhMeHJvS1l5K05IWT0=

Source link : 
`https://www.oploverz.in/black-clover-episode-110-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Duplicate of #193
