### ISSUE TITLE
adf.ly trough Cowner.net 

### ISSUE THREAD

**Issue by zeeh1975** [timmyRS/Universal-Bypass#584]
It seems that it's "encapsulated" so adf.ly can't be skipped, can you give a look?
Try opening various simultaneously 

http://cowner.net/ad/locked?rweasy=12&user_id=2861046&_adflyurl_=voyager-t6-23&folder_id=&rndad=3051657292-1574199624&url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1xFrJo9lE4sRIbXP-C0-96YzTP16KIaEk&t=e&subid=2861046&h=12

http://cowner.net/ad/locked?rweasy=12&user_id=2861046&_adflyurl_=voyager-t6-24&folder_id=&rndad=3051657292-1574199625&url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1H4KBzvRumfa-CP4kI5RFpRinxXOMSlgi&t=e&subid=2861046&h=12

http://cowner.net/ad/locked?rweasy=12&user_id=2861046&_adflyurl_=voyager-t6-26&folder_id=&rndad=3051657292-1574199626&url=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D1cDzd8aEKKZ0YHaocv4AjRk-z7-gxjcRp&t=e&subid=2861046&h=12

**Comment by timmyRS** [comment]
The cowner.net website is broken, even without Universal Bypass.
