### ISSUE TITLE
tumblr: t.umblr.com redirect

### ISSUE THREAD

**Issue by mehlon** [timmyRS/Universal-Bypass#587]
Some tumblr blogs have outward redirect links:
https://t.umblr.com/redirect?z=%2F%2Flkml.indiana.edu%2Fhypermail%2Flinux%2Fkernel%2F0311.0%2F0635.html&t=ZWM4NDUyNGMyYWYxMDdiNjk5NzlkMjRlZmVhODAxMzdjYTIyYjM3NixLdDFWOFU2Zw%3D%3D&b=t%3AlMu0rOs9jGwbQo_qiwGh_A&p=https%3A%2F%2Farjunsreedharan.org%2Fpost%2F67970413047%2Fof-backdoors-and-bad-coding&m=0
The page has this code:
```
<noscript>
<meta name="referrer" content="origin" /><meta http-equiv="refresh" content="0;URL=//lkml.indiana.edu/hypermail/linux/kernel/0311.0/0635.html" />
</noscript>
```

But curiously it doesn't work because they put it in noscript tags.

**Comment by timmyRS** [comment]
This has nothing to do with Universal Bypass. It doesn't work with or without UB.
