### ISSUE TITLE
http://shorten.sh

### ISSUE THREAD

**Issue by cesesa9442** [timmyRS/Universal-Bypass#588]
Hello,
Please add bypass to

http://shorten.sh

Thank you

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by cesesa94442** [comment]
http://shorten.sh/xAmt
http://shorten.sh/jNguyL

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
