### ISSUE TITLE
teknoku.me safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#591]
Example link :

https://teknoku.me/?id=MERMT1UwSDUvSjJuTllCSzhIR2tTaWlld0g5Y0tXNWJlQW9hZFA1WVFWZz0=
https://teknoku.me/?id=bjNycTFLTFFiZDNYQ2RHeVlidzM2TWIva1R6YmxWajFNSll0NkNNVUVCRWZZbnZvTEt1SC96UkRTWmRteVdOQ1IvQWNmcjVyNW9kV2hWNlhFQU8wZnk0SWhzOHNsNUEreCsyQjAwN1R3d0E9

Source link : 
`https://www.conan.id/assassins-pride-episode-07-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Duplicate of #193
