### ISSUE TITLE
hightech.web.id safelink

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#593]
Example link :

https://hightech.web.id/ko82jkl9/?sitex=aHR0cHM6Ly9tZWdhdXAubmV0LzI5ZXQyL0hvU28tMDctNzIwcFt4MjY1XS1TQU1FSEFEQUtVLlRWLm1rdg==

https://hightech.web.id/ko82jkl9/?sitex=aHR0cHM6Ly9yYWNhdHkuY29tL2R3MWt2eXViZDM0bQ==

Source link : 
`https://neonime.org/episode/hoshiai-no-sora-1x7/`

**Comment by timmyRS** [comment]
Already solved with #614 (I go through issues the wrong way around)

**Comment by KagaKouko99** [comment]
ok thanks
