### ISSUE TITLE
request: seoinlink.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#603]
http://seoinlink.com/?id=RHl2bk5kcHB4UmR2ZGtubmZoVDVvcWJBMTJKL01zU2pTUTg0UDVOdnVFb2VxSzAyVldHZ3lCdlRaWGZyaS9ZZVFjQjhiL0cxeTZvdm5LQytLRkJlaFBXSWE4bmhDTGtmVm00ajN0U3puYVdEa292MSs2ZXVCSzVRU3Y5bmR5VTQ=

**Comment by adammalyck** [comment]
this issue is not yet fixed, i have update to version 11.13

or will be fixed in the next update?

**Comment by timmyRS** [comment]
This is a duplicate of #193. Because of your spam, I didn't write a response on every issue.

**Comment by adammalyck** [comment]
ok, I will stop reporting for a while
