### ISSUE TITLE
request: shrinkearn.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#605]
https://shrinkearn.com/full?api=a14643403261db545e2825e2af1fabb2fe1166ed&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL3VjP2V4cG9ydD1kb3dubG9hZCZpZD0xVjdFQkFpaXJ1WHVxMkU1NUR0WFhrRzNpd24xRThKU28=&type=2

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by adammalyck** [comment]
i want ask 

if like this, is it have solve the problem?

![image](https://user-images.githubusercontent.com/57831066/69471699-1d1d5980-0d57-11ea-9d36-2b24d19f5f6a.png)

**Comment by timmyRS** [comment]
That means the website is bypassed by crowd bypass.

**Comment by adammalyck** [comment]
i see, thank you
