### ISSUE TITLE
request: cariskuy.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#606]
https://www.cariskuy.com/human-verification/?site=aHR0cDovL2ZzMS5hbmlmaWxlcy5vcmcvMVE1QQ==&c=0&user=2

**Comment by adammalyck** [comment]
is this has been fixed?

**Comment by timmyRS** [comment]
Yes.

**Comment by adammalyck** [comment]
or wait until update on chrome extension?

**Comment by adammalyck** [comment]
because i still waiting 5 second

![image](https://user-images.githubusercontent.com/57831066/69471739-aaf94480-0d57-11ea-81c2-b4f5c89f59b8.png)

**Comment by timmyRS** [comment]
You'll have to wait for the next release.

**Comment by adammalyck** [comment]
OK, thanks for the information
