### ISSUE TITLE
request: infosehatku.club

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#610]
https://infosehatku.club/links/post/17-25-unique-places-in-the-real-world-it-s-coming-from-a-fantasy-movie?a=AjkqgAosGc

**Comment by adammalyck** [comment]
https://infosehatku.club/links/post/6-5-ways-to-reduce-the-impact-of-global-warming?a=5RbSwb

**Comment by timmyRS** [comment]
Cloudflare is not letting me enter that site. Do you have the same problem?

**Comment by adammalyck** [comment]
i don't get a problem, it's working fine until google drive link

**Comment by timmyRS** [comment]
![image](https://user-images.githubusercontent.com/11009697/69471689-7fe81280-0da2-11ea-98ca-96d40fecbd7b.png)

**Comment by adammalyck** [comment]
why you get an error? for me its working fine

**Comment by adammalyck** [comment]
it's have been fix

![image](https://user-images.githubusercontent.com/57831066/69471804-805bbb80-0d58-11ea-9339-3b46b0ff1adc.png)

**Comment by adammalyck** [comment]
thank you

**Comment by timmyRS** [comment]
I recommend you keep this option on:
![image](https://user-images.githubusercontent.com/11009697/69471829-15d06d00-0da4-11ea-8654-8024e2e4add7.png)

**Comment by adammalyck** [comment]
what is its function?

**Comment by adammalyck** [comment]
i have enable it before

**Comment by adammalyck** [comment]
![image](https://user-images.githubusercontent.com/57831066/69472114-17297780-0d5b-11ea-9ead-27e5c7b57003.png)

**Comment by timmyRS** [comment]
It'll tell you when a website is bypassed by crowd bypass.

**Comment by adammalyck** [comment]
like this?

https://user-images.githubusercontent.com/57831066/69471804-805bbb80-0d58-11ea-9339-3b46b0ff1adc.png

**Comment by adammalyck** [comment]
thanks for the information @timmyRS 

i will report for the other issue later :)

**Comment by timmyRS** [comment]
Like this:

![middle](https://user-images.githubusercontent.com/11009697/69472228-92b11600-0da7-11ea-97ce-94cab5f90dbd.png)
