### ISSUE TITLE
request: lonelymoon.net

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#619]
https://lonelymoon.net/?id=dC94MXMvbTRkK21jV1doNE1ZdWMzUUJza3FuSVFianU3aC85UHRrTUpJdz0=

**Comment by timmyRS** [comment]
Duplicate of #193

**Comment by adammalyck** [comment]
is this will be fix in the next release?

**Comment by timmyRS** [comment]
No.

**Comment by adammalyck** [comment]
why?

**Comment by timmyRS** [comment]
Because #193 has not been solved yet.

**Comment by adammalyck** [comment]
oh, your mean this is still progress?\

sorry for my bad english

**Comment by timmyRS** [comment]
Yes.

**Comment by adammalyck** [comment]
ok, waiting for the next update

thanks for your hard working @timmyRS
