### ISSUE TITLE
request: zflas.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#622]
http://zflas.com/go?go=68747470733a2f2f61736961787869312e736974652f646f776e6c6f61642f646f72612d616e642d7468652d6c6f73742d636974792d6f662d676f6c642d32303139

**Comment by timmyRS** [comment]
I don't understand.

**Comment by adammalyck** [comment]
what you don't understand?

**Comment by adammalyck** [comment]
is this issue has been fixed?
