### ISSUE TITLE
Request blocking 3dp scripts adtival

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#624]
https://www.shrinkads.com/full/?api=d1f51d5bad4cd73415c25c2863c05189942a3b35&url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MVZsc21QR0YzR1NsS19pc3hVTGY2anNhcjdhV2tMOHRT&type=2

https://www.shrinkads.com/full/?api=d1f51d5bad4cd73415c25c2863c05189942a3b35&url=aHR0cHM6Ly91cHRvYm94LmNvbS81aHVjb2F5bXF0aTI=&type=2

Source :
`https://movieku.org/the-exorcist-subtitle-indonesia/`

**Comment by KagaKouko99** [comment]
@timmyRS bug
https://www.adtival.network/full/?api=dbbe0df41fefb5869d22614b8ac803a2953a1bbc&url=aHR0cHM6Ly9yYWNhdHkuY29tLzBqbHN4bHZhM2huZg==&type=2
