### ISSUE TITLE
Request gplinks.in

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#626]
https://gplinks.in/full?api=4c0a87740173ca5385525b8838757a8983c95852&url=aHR0cHM6Ly9oYW5hZmlsZXMuY29tL2ZpbGUvNHR0em9SYnF4Uw==&type=2

https://gplinks.in/full?api=4c0a87740173ca5385525b8838757a8983c95852&url=aHR0cHM6Ly9maWxlcy5jeC9pZC8xZ2VldHc3&type=2

Source :
`https://hananime.com/nanatsu-no-taizai-signs-of-holy-war-bd-sub-indo-batch/`

**Comment by timmyRS** [comment]
Bypassed by current developement version.
