### ISSUE TITLE
request: fileanimehade.my.id

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#630]
https://www.fileanimehade.my.id/file/e4e3072a01ee65f31fb8bc3d393b4de030bd09e917fe94f2afb368b44d2838da595fbdbdaff71d97f19da7da073398a00a4cd473fc0439feb182825844ac68e00_VlzuMtwlXZv61sMvMitfgnkhISLIEa~_rZC7fQlIIiVRv1cdVEHkRU_zuA3xkjbJzjut39JRdpMV~8alsliA--

**Comment by timmyRS** [comment]
I get an error:
> the file was invalid or has been downloaded many times, please try again after few hours.

**Comment by adammalyck** [comment]
![image](https://user-images.githubusercontent.com/57831066/69476058-c5e4ac80-0d89-11ea-86f3-7c4d4484b653.png)

**Comment by adammalyck** [comment]
same error

**Comment by adammalyck** [comment]
just close this issue if not get a solve

**Comment by adammalyck** [comment]
i forgot, i will check the source website

**Comment by adammalyck** [comment]
please remove the "awaiting response", i'm not get the source

but i will check it again later, thank you
