### ISSUE TITLE
request: landscapenature.pw

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#639]
http://landscapenature.pw/?id=OW1KTkZBUE10UmJjeXE2citBUG1WamJkeEk1QVNjdTRYbDF1c0ozUDNkUkdGM0JmODJUU21QaHNuakFkaUFYSEtzVWYyOVZkVFdiK0QyK0lJZ1Z4ZVE9PQ==

**Comment by timmyRS** [comment]
Duplicate of #193
