### ISSUE TITLE
request: wanhealth.me

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#640]
https://www.wanhealth.me/?id=a3haY1JjN3N2T1pHZ3IrdmM2RUtaUXF4TG85MUplTmhwdkZjREoyV2svOTlBWGtQb2ZVMjVrdzRFaFFsY1VndjF2bUFVdXNzYmRQRWVMN1FzenYyMzZaRVJxYWQ2NFU2NFVtaWJnNURQdXc9

source : 
https://www.animebatch.id/detective-conan-batch-subtitle-indonesia-episode-1-900/

**Comment by timmyRS** [comment]
Please stop duplicating issues.

**Comment by adammalyck** [comment]
sorry, because i don't know
