### ISSUE TITLE
request: apasih.pw

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#641]
https://apasih.pw/?id=a1NobVhjdlBzd2lucDN3OTN0V2l5dUJ5UlVaUzNFZ1V2Zk9NODNtS3JzSVFzNmZUZ0xMdS81N1EzZUtOWlZxVElyQXJtTDcvbHRvSHJaMU1RWFZVYlpFaWwyRTlkbENnOUp0Tm12QTJ2MjZKaEI5YU1JSDVxajJnODRuM1JvUnE=

source :
https://www.koenime.com/detective-conan-subtitle-indonesia/

**Comment by timmyRS** [comment]
Duplicate of #406. Please search for existing issues before creating a new one.

**Comment by adammalyck** [comment]
sorry, thanks for the info
