### ISSUE TITLE
request: bercara.com & semawur.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#642]
https://bercara.com/b1Rv4eBGMKS

https://semawur.com/post/133-cara-daftar-paket-internet-murah-telkomsel-bonus-4g#x7AjbEnUH

**Comment by adammalyck** [comment]
please fix "semawur" too

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
