### ISSUE TITLE
request: pastelinku.net

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#643]
http://pastelinku.net/?id=QWM0WElDRFlwcVgyVU5zdXBvaHJ2MU51UEowdmdqd2VLRkdzWEZERS9iL0JFUVpTbU9HRlIrMGdGWXlYU2hvVTNHeklBTTNMbGtaRjBiVy93VzMxM3BXV0VxSXNqL1VWL0FENmhrMGo3Nzg9

source :
https://drivenime.com/detective-conan-movie-23-the-fist-of-blue-sapphire-subtitle-indonesia/

**Comment by timmyRS** [comment]
Duplicate of #193
