### ISSUE TITLE
problem with mega.nz

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#650]
https://mega.nz/#!WkwVEY7I!d6Nyzw3MjryXzg5KFy4qta8beusjQyRpeLtiApDmM2c

sometimes if accesing mega.nz  stuck like this
![Annotation 2019-11-24 095747](https://user-images.githubusercontent.com/9379770/69488844-b062a600-0ea1-11ea-9b55-063c5726fc28.png)

I have checked all the extensions I use, the problem is in ub

**Comment by timmyRS** [comment]
I don't see how Universal Bypass could be causing that in any way.

**Comment by WaferNabati** [comment]
that's weird. when i disabled ub and enabled it again the issue is gone but sometimes it reappears

**Comment by timmyRS** [comment]
Do you maybe have some custom bypasses in UB?

**Comment by ikancupang** [comment]
@timmyRS He uses an unstable custom bypass script from #465

**Comment by WaferNabati** [comment]
yes i use custom script from there

**Comment by ikancupang** [comment]
`_0xf0bfa = theShit;` is the cause of the error.
make sure you understand the script you are using to avoid errors.
