### ISSUE TITLE
evassmat bypassing

### ISSUE THREAD

**Issue by HadesGit** [timmyRS/Universal-Bypass#651]
Is it possible to add evassmat.com to the list?

I have this link as an example

https://trollo.blog/kawaikereba-hentai-demo-suki-ni-natte-kuremasu-ka-ln/

with the link going to http://evassmat.com/7ku9 instead of a google drive. Never saw that evassmat before, so it wasn't an issue till now.

Otherwise the bypass works perfectly. Thanks for that.

**Comment by timmyRS** [comment]
I don't understand what there is to be bypassed
