### ISSUE TITLE
bug: download.id

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#652]
https://download.id/audacity.html# (download dialog not show and finally get error)
https://download.id/xnconvert.html# (must waiting until 0 second)
https://download.id/bluestacks.html# (working fine)

conclusion : there are some links that are still in the bug
please fix this

sorry for bad english

**Comment by timmyRS** [comment]
I don't have an error on any of the links.

**Comment by adammalyck** [comment]
sure? i will try again

**Comment by adammalyck** [comment]
https://download.id/xnconvert.html# , the download dialog will show after 0 second
while this link https://download.id/bluestacks.html# , the download dialog will show without wait 0 second (download dialog show at 9 second)

**Comment by timmyRS** [comment]
Do you have other extensions which might interfere?

Also, if I might suggest, you can just use google to find an official download link instead of using some shady website.

**Comment by adammalyck** [comment]
i'm using adguard

maybe the download link is error, just wait a few hour

thanks for the respons

**Comment by adammalyck** [comment]
please fix this, it's will redirect to MEDIAFIRE but still wait until 10 second

https://download.id/driverpack-solution.html#

download button via MEDIAFIRE
