### ISSUE TITLE
adfoc.us

### ISSUE THREAD

**Issue by checkraisefold** [timmyRS/Universal-Bypass#662]
Example link: http://adfoc.us/serve/?id=27122861261654

This is extremely easy to add. I'm not very experienced in javascript and universal bypass doesn't have much documentation, so I'm not gonna do a PR myself at risk of breaking something, but I did look and find out that the link is in plain text as a href but it's just hidden until the countdown is over.

The custom bypass I came up with was this:
`domainBypass("adfoc.us", function()
{
	ensureDomLoaded(function()
	{
		safelyNavigate(document.querySelector(".skip").href)
		// Make sure to use safelyNavigate(url) to avoid bad redirects.
	})
})`
It works, but that would screw up if you just went to the main page of adfoc.us, and I'm not sure how to approach this problem.

**Comment by timmyRS** [comment]
Oh shit, I removed that bypass thinking that website was dead, when in reality, it was just blocked in my local network.

**Comment by UltraBlackLinux** [comment]
The adfoc.us bypass no longer seems to work... The page doesn't even redirect me. Just emptyness
