### ISSUE TITLE
request: doi.liriklagukeren.com

### ISSUE THREAD

**Issue by adammalyck** [timmyRS/Universal-Bypass#665]
https://doi.liriklagukeren.com/?id=M1pOeUtEc1VyTnlRZGRtaTBBaUFCcDBhTm9mUDhVSWVuTmpkQVBSTUZUcU53bXdLQ3hEWndFYjE0K0dyT2ZXMS9KWmVXelJIWm16TmJ6b0J5UE5jbVhDNmgxTFNVRE0vOVBzOTBuSGxXaGM9

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by adammalyck** [comment]
sorry, because i test it still not working, buat after refresh it will working
