### ISSUE TITLE
https://eio.io/

### ISSUE THREAD

**Issue by vittbol** [timmyRS/Universal-Bypass#668]
http://exe.io/JsyXS

It's weird, because whenever I enter in a exe.io/eio.io (they're from the same shorter, I don't know how to get a eio.io link exemple), it says: "Unfortunalety, you're the first to encounter...", it supposedly bypass the next link but it doesn't, it just shows another same "unfortunalety..." message.

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
