### ISSUE TITLE
Shortlink name bcvc unable to bypass by UB (Universal Bypass)

### ISSUE THREAD

**Issue by GeekWorld7** [timmyRS/Universal-Bypass#669]
I have encountered a shortlink which universal bypass is not able to bypass.
![image](https://user-images.githubusercontent.com/58249176/69703552-a2b65600-1117-11ea-9543-207862efeb17.png)

It's called bcvc.live

I will be thankful to you if you include this link in your bypass script.

Thanks
GeekWorld7

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
