### ISSUE TITLE
Universal Bypass breaks banking site

### ISSUE THREAD

**Issue by rjonmarco** [timmyRS/Universal-Bypass#674]
https://secure1.bpiexpressonline.com/AuthFiles/login.aspx?URL=/direct_signin.htm

which redirects to

https://online.bpi.com.ph/portalserver/onlinebanking/sign-in
**What I get**
![firefox_qRNNL1yENk](https://user-images.githubusercontent.com/9809253/69736132-e0919980-116c-11ea-95ca-8fbc35387f96.png)

**Expected**
![7Td2s0A9by](https://user-images.githubusercontent.com/9809253/69736136-e12a3000-116c-11ea-824c-712bc5d9a55e.png)

Workaround:
Disable UniversalBypass when accessing the site.

**Comment by timmyRS** [comment]
Works for me in Chrome & Firefox. Do you maybe have a custom bypass in UB or other extensions?
