### ISSUE TITLE
https://acortalo.xyz/#!3555b64a56e6c03356d9a7ffbfb97056943719c8acbe47c28ee5401f49c4bbfaumG/fse8VkdoNidOd3phKcAeIhBTk/tuMYFJf803V7Yrku0tsk/fIg6IAhWczX3o

### ISSUE THREAD

**Issue by MCALBLACK** [timmyRS/Universal-Bypass#686]
THIS LINK CANNOT MAKE IT PASS

**Comment by timmyRS** [comment]
That's giving me a 404. Where did you get that link from?

**Comment by MCALBLACK** [comment]
https://www.megawarez.org/halo-the-master-chief-collection-pc-full/

**Comment by MCALBLACK** [comment]
from there I want to enter the link to pass the shorteners and take me to another page where nothing loads me
