### ISSUE TITLE
Imgur doesn't load when Universal Bypass is enabled

### ISSUE THREAD

**Issue by cca310** [timmyRS/Universal-Bypass#688]
This is what I see when addon is enabled: 
![Screenshot_2019-12-05 A tiny 3D pixelart diorama](https://user-images.githubusercontent.com/36178056/70291365-f32d5380-17a8-11ea-8e77-09cffce971c0.png)

This is what I see when I disable the addon: 
![Screenshot_2019-12-05 A tiny 3D pixelart diorama(1)](https://user-images.githubusercontent.com/36178056/70291378-fcb6bb80-17a8-11ea-9e73-e97d5b426d29.png)

**Comment by mooms06** [comment]
Same issue here.

Firefox 71.0  64bits on Windows 10 1909.
