### ISSUE TITLE
Crowd bypass not working on different device

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#690]
i don't know why but crowd bypass doesn't working on pahe.in site the link always changes.
i test with different device but the benefit for skipping not working.
Universal Bypass version 11.17.2
Browser Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

link :  https://pahe.in/?dd1fa7bc42=eVM0U3JGVlJUSStObEdJcVorZ3p3UzE4NEFQeTVyRUVOaExON3dITXNtM1Bsb3l5NWg4ZCsyUjdFTW4zMktQY00xcVFYSVhCNUFNMThlSW80clY0ZGc9PQ==

site :  https://pahe.in/

**Comment by timmyRS** [comment]
It's working for me, but it could be some sort of race condition. Do you have many other extensions?

**Comment by Arsindy** [comment]
yes i use ublock origin, ublock protector idm integration module buster captcha solver and universal bypass both on my pc and laptop
browser goggle chrome

**Comment by timmyRS** [comment]
and the bypass doesn't work on either of them?

**Comment by Arsindy** [comment]
If I pass the link on my PC crowd bypass doesn't work on my laptop but working on my PC if i open the same link and the other way around

**Comment by Arsindy** [comment]
this issue only on pahe.in safelink and works well in other shorteners that use crowd bypass

**Comment by timmyRS** [comment]
Where do you get the pahe.in link from?

**Comment by Arsindy** [comment]
https://pahe.in/vikings-season-6-web-hd/

can you test the gd link 1080p x265 i passed it

**Comment by timmyRS** [comment]
I had to wait on that and after I did, it worked. Looks like they're handing out fresh links for each new visitor, so it'll be a bit trickier to get the crowd bypass part to work on that.

**Comment by Arsindy** [comment]
yes that's what i mean
