### ISSUE TITLE
https://www.uploadedpremiumlink.xyz/ (Links generated by this website)

### ISSUE THREAD

**Issue by LEO33SoFo** [timmyRS/Universal-Bypass#694]
URL shorteners generated by this premium link generator are not bypassed by **Universal Bypass**.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by LEO33SoFo** [comment]
There is not way to provide a manual example link, because the website generates dynamic links, depending on the link you provided to download.
You can see for yourself by trying to generate a premium link with this test file: [Uploaded file example](http://uploaded.net/file/24bbp9d7).
You will notice lots of URL shorterners, one after another, which **Universal Bypass** fails to bypass.

**Comment by timmyRS** [comment]
I don't have uploaded.net premium but the bypass for the wait on the free download seems to work fine

**Comment by LEO33SoFo** [comment]
Are you sure?

These are the domains which fail to bypass:
_https://ouo.io/
https://fodz.xyz
https://oko.sh
https://ckk.ai
http://short.pe
http://shorten.sh_

**Comment by leviathanhaizen** [comment]
https://www.uploadedpremiumlink.net/

![image](https://user-images.githubusercontent.com/66950085/84665052-f8d2d580-af51-11ea-869a-6ffe8fc6db63.png)
