### ISSUE TITLE
fileru.net

### ISSUE THREAD

**Issue by xorcan** [timmyRS/Universal-Bypass#698]
**https://fileru.net/download.php?v=4abd748025330cd496f83295e00093f1 report skip universal**

**Comment by timmyRS** [comment]
I get "Bu video telif ihlali sebebiyle kaldırılmıştır." which seems to mean "This video has been removed for copyright infringement."

**Comment by xorcan** [comment]
try this https://fileru.net/download.php?v=43ed4be7fbbb44852901c9dbad8be995

**Comment by timmyRS** [comment]
Same.

**Comment by xorcan** [comment]
https://fileru.net/download.php?v=43ed4be7fbbb44852901c9dbad8be995

https://fileru.net/download.php?v=5485d49ded094f478642a70243c3748a


@timmyRS

**Comment by timmyRS** [comment]
All the same. I assume these work for you. Maybe it's some sort of clever region block. Which country should I connect to via VPN?

**Comment by xorcan** [comment]
at this site: https://720p-izle.com/izle/altyazi/kill-bill-vol-1.html
click where i show with red square: 
![resim](https://user-images.githubusercontent.com/25418042/70712063-0170f780-1cf4-11ea-94df-3842a55e20c8.png)

page will open

im in turkey now, maybe it works

**Comment by xorcan** [comment]
another link: https://fileru.net/download.php?v=86d351731fa587a5eb9d315fdc674747

**Comment by timmyRS** [comment]
I unfortuntely don't have a Turkey VPN and I'm also region blocked from 720p-izle.com.

**Comment by xorcan** [comment]
i have tried with america vpn, it works.
please try again for us :)

**Comment by timmyRS** [comment]
Nope, same issue, also tried with Firefox.
