### ISSUE TITLE
portableapps.com

### ISSUE THREAD

**Issue by xorcan** [timmyRS/Universal-Bypass#704]
**https://portableapps.com/downloading/?a=PortableApps.comPlatform&s=s&d=pa&n=The%20PortableApps.com%20Platform&f=PortableApps.com_Platform_Setup_16.0.3.paf.exe**

downloading...
4
3
2
1

(skip countdown)

**Comment by timmyRS** [comment]
I don't really see the point in bypassing that, but okay.
