### ISSUE TITLE
wupfile.com

### ISSUE THREAD

**Issue by 0xh3LL0** [timmyRS/Universal-Bypass#710]
https://wupfile.com/6v23gwce0tqw/

choose free download, the countdown should appear.

**Comment by timmyRS** [comment]
File Not Found

**Comment by 0xh3LL0** [comment]
https://wupfile.com/6v23gwce0tqw/HazukashigariyaMusum_v01-02s.rar.html

**Comment by timmyRS** [comment]
Unfortunately, they use backend validation to make sure you have actually waited before you can download the file.
