### ISSUE TITLE
mexa.sh

### ISSUE THREAD

**Issue by 0xh3LL0** [timmyRS/Universal-Bypass#712]
https://mexa.sh/1wjboqkk146x/

choose free download

**Comment by timmyRS** [comment]
404

**Comment by 0xh3LL0** [comment]
https://mexa.sh/1wjboqkk146x/Kenkouki_v02.rar.html

**Comment by timmyRS** [comment]
Unfortunately, they use backend validation to make sure you have actually waited before you can download the file.
