### ISSUE TITLE
https://apglinks.net/

### ISSUE THREAD

**Issue by neomike00** [timmyRS/Universal-Bypass#716]
https://apglinks.net/#!VlRKR2MyUkhWbXRZTVM5U1pWRXZkMUJ0YUZwTFJIWXhla0V5TkdobFRrZHVPSHAzZFZKS2JTczVPVUY2YjA5MFpqSjZNV0ZGUlRaSWVFa3dPR2RaZEFvMGVtSllNWGxuWkVGaFZqWk5jRk5YZVRsTVVrMWFaVzVPTldsWWIweHBTa3hyZFhOTU9EWlpabWgzUFhWeGRYbzFZamwwWlhNPQ==

**Comment by neomike00** [comment]
Is usually used as a captcha for games, but even without adblock, it doesn´t get the clicks so you are locked in a loop.

**Comment by timmyRS** [comment]
That link doesn't seem to work. Where did you get it from?
