### ISSUE TITLE
Info regarding Linkvertise

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#719]
Before I get 10 more issues regarding this, note that Linkvertise is bypassed as of Universal Bypass 11.18, but for some reason the publishing is being delayed on Chrome. Just give it some time and it will resolve itself. Thanks for your understanding and sorry for the inconvencience.

**Comment by jdearaujo1** [comment]
hey timmyRS, I use the 11.18 on Firefox and it's not working for me

**Comment by timmyRS** [comment]
@jdearaujo1 Could you provide a link where it doesn't work?

**Comment by adapths** [comment]
@timmyRS tried on firefox, doesn't seem to work
https://link-to.net/43159/Gladius

**Comment by timmyRS** [comment]
Alright, I'll trick it into thinking that extension is installed.

**Comment by adapths** [comment]
thanks, when you do the extension patch would it be in a seperate update or a small hotfix?

**Comment by timmyRS** [comment]
I don't really have a set release cycle, but you can add
```JavaScript
ensureDomLoaded(()=>{
	var div = document.createElement('div');
	div.id = "ogxzi8ZzrLy8S4zhUwyc3jPMlXi1h91bA0bASIiZtyT6cOTlX78HtEyXTK0WUGCY3CO8E4hBYI02ZD9mr7jit7R1YqPdkllJ";
	document.body.appendChild(div);
})
```
in the "Custom Bypasses" section in the meantime to (hopefully) the same effect.

**Comment by adapths** [comment]
that worked, hope it doesnt download anything as linkvertise's extensions just steal your passwords :p

**Comment by timmyRS** [comment]
I looked at their extension's code and it provides an element with that obscure ID to identify itself, so Linkvertise knows/thinks it's installed but other than that it only replaces Google, Yahoo, and Bing with "Lookbox."

**Comment by adapths** [comment]
do you think it'd be possible to trick it into thinking you watched their videos / turned on notifications?

**Comment by timmyRS** [comment]
The current bypass should fake having watched the video. I haven't encoundered a link where you need to turn on notifications yet, tho.

**Comment by GabbyAnims** [comment]
I'd like to ask, do you have any idea why the bypass is being delayed on Chrome?

**Comment by timmyRS** [comment]
Because Google are assholes who have a monopoly and don't care about individuals like you and me. That's my guess at least.

**Comment by GabbyAnims** [comment]
Indeed. Anyways, could you give me a video on bypassing linkvertise, because i couldn't understand what were you saying. Oh, and my Universal Bypass  is 11.17. Although i can't update mine.

**Comment by GabbyAnims** [comment]
By the way, i'm new here so i hope you can understand me.

**Comment by timmyRS** [comment]
Unfortunately, you'll have to wait for 11.18. That code snippet I posted above is to skip the "install extension" step on Linkvertise, which is not in a release yet.

**Comment by trenonux** [comment]
Countdown stuck after click continue, I use Universal Bypass 11.18 (current master) on Chrome, I tried the link https://github.com/timmyRS/Universal-Bypass/issues/719#issuecomment-565847884

**Comment by QuickFatHedgehog** [comment]
Just install the extension by the source code, just download it. there is a button to load unpacked extension. but i dont think it will auto update

**Comment by timmyRS** [comment]
I'm replacing the pinned issue with #738 since this is not just related to Linkvertise, but Google Chrome in general.

**Comment by jkrosado** [comment]
It still doesn't work anyway. Clicked a Linkvertise link on 11.18 and it took me to Linkvertise, not the direct link.

**Comment by timmyRS** [comment]
@jkrosado #738
