### ISSUE TITLE
Request wizardsubs.com 

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#726]
https://wizardsubs.com/?408631a1f0=WWRzTlE3dG00ck5XNnJTT3lSTEpFQU9tdTVsQzZhZ0tTa1oycHVyRFFGdlYxSTluT0FYNnAvTXlxTXJKY3ErM29SbDhZbWxoaWRxQm13RDhIaCs3QVNIS2kyNzZTOEYyMkYwMk5NU2xraHBLMzFmVEluSytKbm1mcjFvOU5VV041WTc4UkNUR0JWNjhBWEd4MzZSa293PT0=

https://wizardsubs.com/?408631a1f0=WWRzTlE3dG00ck5XNnJTT3lSTEpFQU9tdTVsQzZhZ0tTa1oycHVyRFFGdlYxSTluT0FYNnAvTXlxTXJKY3ErM0JQeDNiQ2dHdncwV2ZseW81OHRwRUpLNDFJYUFwUWUzUWsyNXBtU0F0MjFhcUNmL2cydWp2bXpkVzRwNXk3d0RqOEtET21vUUJQejh2cFJSMXlBTUJRPT0=

Source :
`https://wizardsubs.com/2019/12/14/ultraman-tiga-episode-01-49-hdtv-subtitle-indonesia/`

**Comment by WaferNabati** [comment]
@timmyRS improve separate link button
https://wizardsubs.com/2019/12/22/mv-love-want-you-want-you/
https://wizardsubs.com/2019/12/21/saraba-kamen-rider-den-o-final-countdown-dc-bd-subtitle-indonesia/

**Comment by ikancupang** [comment]
@timmyRS
This will be fine
`a.href+="#bypassClipboard="+a.href.split("?408631a1f0=")[1]`
because this site uses "static id".

This #790 also uses "static id".

**Comment by timmyRS** [comment]
If that is the case, we can just remove the code for them completely.

**Comment by ikancupang** [comment]
@timmyRS Sorry, I mean "static id" only on wizardsubs.com
`https://wizardsubs.com/?408631a1f0=[this_is_a_static_id]`
the id will not change even if the page is reloaded or different visitors
but after redirecting to zaqe.xyz the id becomes dynamic
`https://zaqe.xyz/?id=[this_becomes_a_dynamic_id]`
so the bypass clipboard is still needed on wizardsubs.com

unlike pahe.in where the id will change every page reloads
`https://pahe.in?73e659772d=[the_id_always_changes_every_page_reloads]`
