### ISSUE TITLE
BUG : filehorse.com

### ISSUE THREAD

**Issue by FinderID** [timmyRS/Universal-Bypass#730]
https://www.filehorse.com/download-winrar-64/download/

the size file must be 3 MB, but the downloaded size file is just 2 MB and detected by Avast (infected file)

i try dowlnload other Software like Mozilla Firefox, the size is same just 2 MB and detected as virus

all software when download, it will be just 2 MB size

**Comment by timmyRS** [comment]
I don't think there's an issue with Universal Bypass here. Maybe try not using shady download sites?
