### ISSUE TITLE
bdzone.xyz

### ISSUE THREAD

**Issue by gabri25ele** [timmyRS/Universal-Bypass#737]
https://bdzone.xyz/cheat.php?link=aHR0cHM6Ly9vdW8uaW8vSmFpdzZUcQ==

![Cattura](https://user-images.githubusercontent.com/33927879/71073653-15e44280-2181-11ea-9765-09c87f77ecba.PNG)

**Comment by timmyRS** [comment]
This is fixed in current master.

**Comment by gabri25ele** [comment]
fixed?
But I get that advice.
Hope to have an update soon.
