### ISSUE TITLE
Info regarding Google Chrome

### ISSUE THREAD

**Issue by timmyRS** [timmyRS/Universal-Bypass#738]
Google have decided that updates are overrated, as they are now delaying new versions for **over a week,** resulting in the latest Universal Bypass version available on Chrome being 11.18.

Before reporting issues encountered in Chrome, please scan [the changelog](https://universal-bypass.org/changelog-full) to see if the problem is not already fixed.

To circumvent Google's arbitrary delays, Universal Bypass 12 features auto-updating of the injection script. However, when this will be available on Chrome is unclear.

**Comment by Hacker577DIE** [comment]
Ok. Thanks for the info. Ima verify.

**Comment by Hacker577DIE** [comment]
Does not work unfortunately.

**Comment by Hacker577DIE** [comment]
I need help without this i cant access my fav content.

Does not work, not even on Firefox.

**Comment by QuickFatHedgehog** [comment]
works on both chrome and firefox

**Comment by jcvr1994** [comment]
Finally the extension was updated to version 11.18

**Comment by timmyRS** [comment]
Indeed, that should have a working linkvertise bypass, but I'd really like to get 12.0 up there, and have it auto-update to circumvent that stupid 7-day wait Google put in place. Unfortunately, that's gonna be 2 weeks from now.

**Comment by mehmet-efe61** [comment]
Is there a way to install the extension from the developer options on chrome?
2 weeks seem like a long wait.

**Comment by timmyRS** [comment]
Yeah, you can clone this repository, enable developer mode on the Chrome extensions page, click "Load unpacked" and then select the folder you saved the repository in. Because master is already 12.0, you can use auto-updating by deleting `injection_script.js`.

**Comment by Hacker577DIE** [comment]
How you do this

**Comment by Hacker577DIE** [comment]
Where is load unpacked

**Comment by Hacker577DIE** [comment]
At least

**Comment by mehmet-efe61** [comment]
Turn on development mode on chrome extension page

**Comment by QuickFatHedgehog** [comment]
enable developer mode on the chrome extension page
its literally on top of you. cant u even read?

**Comment by QuickFatHedgehog** [comment]
https://github.com/timmyRS/Universal-Bypass/issues/738#issuecomment-568036787

**Comment by iamsrk48** [comment]
can you please give an example for add custom domain in bypass list.

**Comment by timmyRS** [comment]
Little update on this: Seems that my 7 day estimate was incorrect. Who knows how long this will take, or if any updates will ever happen again.

**Comment by timmyRS** [comment]
UB 12.3 is now available on Chrome.
