### ISSUE TITLE
Linkvertise

### ISSUE THREAD

**Issue by mr-personman** [timmyRS/Universal-Bypass#745]
You may be fed up with messages about linkvertise, and I can see why. Linkvertise is scummy, scammy, and outright bad. Here are the links that don't work:
**link-to.net
up-to-down.net
linkvertise.com**
If this is seen, it would be much appreciated by myself and many others if Linkvertise could be skippable.

Much thanks

**Comment by timmyRS** [comment]
I'm fed up with messages about it **because it's already bypassed.** Just use Firefox. See #738.
