### ISSUE TITLE
linkvertise.com bypass not working

### ISSUE THREAD

**Issue by coldscientist** [timmyRS/Universal-Bypass#747]
Before you report a broken bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/timmyRS/Universal-Bypass/issues?utf8=%E2%9C%93&q=is%3Aopen+ENTER+DOMAIN+HERE
I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.

Sample link: https://linkvertise.com/27807/Win10Nov32BitsGDrive

**Comment by QuickFatHedgehog** [comment]
cant u see the info? its literally pinned

**Comment by coldscientist** [comment]
There's closed issues about it, so I believe it was fixed in the past, but it's not bypassing linkvertise links anymore.

**Comment by coldscientist** [comment]
So I read that it was already fixed but the extension wasn't published on Google Store yet. No worries, let's wait for it. It would be cool if the pinned post was renamed to something that we just read and can understand it right away, instead of a generic title.

**Comment by timmyRS** [comment]
Do you have a better idea for a title?

**Comment by coldscientist** [comment]
Maybe it could be "Why Extension Isn't Working on Chrome". A little Click Bait and not accurate, I know. But it should decrease the issues opening because people are curious by nature and will click on it before opening an issue - the people open an issue because it's not working as expected, anyway.
I see that you cleaned the opened issues and let only the info one available. It's a good thing to do, so one issue only will trigger the curiosity and make the people click to read it.
