### ISSUE TITLE
https://roda.site/

### ISSUE THREAD

**Issue by win-than-htike** [timmyRS/Universal-Bypass#752]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/timmyRS/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** I need to be able to see what there is to be bypassed, otherwise I can't create a bypass.

example ==> https://channelmyanmar.org/?1c17f28bf0=M1RiR08vNE1qcmM2bW1HazBxcjFmNUtybzZMcVNPa0g4Q2NHRVkrdFdrUEQzaHhBVkg1UEx2ZldMVGRCRmtVOXVBMTJqNUZFOXdaaFVPOVU2dEdVVnR1OWp3cStScVVwMTc1QnZSOUVOODNOdERBL1RtcDFBM2kycit6UGg3U0U=

**Comment by timmyRS** [comment]
Where did you get that link from?

**Comment by KagaKouko99** [comment]
another sample :
https://channelmyanmar.org/?1c17f28bf0=ZU1WWXIvNkY3amcyNDdrT3h6MGd6Z0R2cDdPZmlyQ1dyUkhBMWdvYW1MU21IS3I3ci9PeDBaYmdRakJ5RVF5dzM5R28xeWU3L1I2emZlOHYzR2Jlb2MwQTU4TkozdTBZdG01R1B6NEdvUVU9

https://channelmyanmar.org/?1c17f28bf0=ZU1WWXIvNkY3amcyNDdrT3h6MGd6cS9xYm4vM0xwNTNXcVkxUm1DbXRMT2VNcFRBdStack1rVkU1c0xQb3d3d0RwV0tNYzNVK1RVbUJpWDJBa3VtVmE3UmVvNEE4anltelhYaUUvZDdHajliTEU2M0lzU0g4ZHFkd1Z0Z2lYSjk=

from : 
https://channelmyanmar.org/tvshows/the-witcher-2019-season-1/

**Comment by KagaKouko99** [comment]
it seems the crowd bypass is still not functioning properly after I passed and opened the same link, still not bypassed

**Comment by timmyRS** [comment]
It did work for me, but I did just notice an oversight, which might be responsible for your problem.

**Comment by WaferNabati** [comment]
another type download button
https://channelmyanmar.org/tvshows/the-mandalorian-2019/
