### ISSUE TITLE
Bug preflight bypass

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#753]
example link :
https://www.adtival.network/full/?api=dbbe0df41fefb5869d22614b8ac803a2953a1bbc&url=aHR0cHM6Ly9yYWNhdHkuY29tL202dHhsMGdqNDZ1ZQ==&type=2

Source link : 
https://doramaindo.id/shinmai-shimai-no-futari-gohan-subtitle-indonesia.html

**Comment by KagaKouko99** [comment]
@timmyRS another sample bug preflight bypass
https://www.adtival.network/full/?api=dbbe0df41fefb5869d22614b8ac803a2953a1bbc&url=aHR0cHM6Ly9hdXRvcmF0aW8uY29tL1BlaVhYRWtG&type=2

**Comment by timmyRS** [comment]
This seems to be working fine. Are you using 12.0.1?

**Comment by KagaKouko99** [comment]
yes i'am using current master

**Comment by timmyRS** [comment]
And what exactly is wrong?

**Comment by KagaKouko99** [comment]
nevermind all the links that I have encountered are only 1 that didn't work
