### ISSUE TITLE
uiz.io

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#754]
https://uiz.io/ftQTW

**Comment by timmyRS** [comment]
That's a performance enhancement. I'm gonna check this out later.

**Comment by timmyRS** [comment]
If ikancupang is right with his fix, then this should work. I have a  network-wide ad blocker, so I can't test it.

**Comment by WaferNabati** [comment]
still doesn't work

**Comment by ikancupang** [comment]
@timmyRS 56527e7 doesn't work, if `bypassed=true` removed uiz.io crowd bypass will work,
and `ifElement("#go-adsredirect",f=>{` needs to be replaced with `awaitElement("#go-adsredirect",f=>{` because `#go-adsredirect` doesn't exist before the countdown = 0.

**Comment by timmyRS** [comment]
Then this should work? I don't wanna remove that `bypassed=true` statement because it's a performance improvement.

**Comment by ikancupang** [comment]
Still doesn't work, but if `bypassed=true` removed from domainBypass function, the crowd bypass will work.

**Comment by ikancupang** [comment]
Works

**Comment by ikancupang** [comment]
Now they detect bypass software.

**Comment by WaferNabati** [comment]
need update
https://uiz.io/KxeXAK

<details>

![Untitled2](https://user-images.githubusercontent.com/9379770/71358045-374a9180-25ba-11ea-8f3e-b4f9ccd3f9c6.png)

**Comment by ikancupang** [comment]
If the bypass is updated, in minutes they will update the website.

**Comment by timmyRS** [comment]
Gotta take advantage of the injection script auto-updating. :^)

**Comment by timmyRS** [comment]
I just had a mental image of a sad guy constantly refreshing this thread and/or the commit list seeing if there was something for him to do.
