### ISSUE TITLE
https://ckk.ai

### ISSUE THREAD

**Issue by ellemti** [timmyRS/Universal-Bypass#758]
https://ckk.ai

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by ellemti** [comment]
https://adlinkcash.com/i0rS

**Comment by ellemti** [comment]
> Could you provide an example link?

https://adlinkcash.com/i0rS

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by ellemti** [comment]
but it doesn't pass throw it

**Comment by ellemti** [comment]
> This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

but it doesn't pass throw it

**Comment by timmyRS** [comment]
Have you enabled "Give and take the destinations of unbypassable shorteners." in the options?

**Comment by ellemti** [comment]
> Have you enabled "Give and take the destinations of unbypassable shorteners." in the options?

it is enable

**Comment by ellemti** [comment]
> Have you enabled "Give and take the destinations of unbypassable shorteners." in the options?

https://cdn.discordapp.com/attachments/519599539095863356/658298051881861140/unknown.png

**Comment by timmyRS** [comment]
Are these your only two extensions?

**Comment by ellemti** [comment]
> Are these your only two extensions?

no , but the extension work on other ad website , it just doesn't work on this one

**Comment by timmyRS** [comment]
What other extensions are you using? Specifically, which ad blocker?

**Comment by ellemti** [comment]
> What other extensions are you using? Specifically, which ad blocker?

ad blocker plus. 
and as i said even i use it , your extension wok fine on other ad websites, (of course after i disable adblocker, which on this condition i did)

**Comment by timmyRS** [comment]
Honestly, I have no idea why this is not working for you. I have made some improvements to the relevant code recently, so should Chrome ever allow you an update, the problem might be solved.

**Comment by ellemti** [comment]
> Honestly, I have no idea why this is not working for you. I have made some improvements to the relevant code recently, so should Chrome ever allow you an update, the problem might be solved.

i dos work on almost 95% ad web and even if doesn't work, it updates itself after i pass the ad website normally. but on this ad website "https://adlinkcash.com/i0rS" it doesn't at all. here is even a video "https://cdn.discordapp.com/attachments/519599539095863356/658309098491740174/AdLinkCash_-_Google_Chrome_2019-12-22_15-03-41.mp4"
