### ISSUE TITLE
Request xmaster.xyz

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#759]
https://xmaster.xyz/?sitex=aHR0cHM6Ly9yYWNhdHkuY29tL3lyaml4MngzcGdtcg==
https://xmaster.xyz/?sitex=aHR0cHM6Ly9taXIuY3IvMUZYWEZaQ1E=

Source :
`https://neonime.org/episode/dragon-ball-heroes-1x18/`

**Comment by timmyRS** [comment]
This seems like it is already bypassed.
