### ISSUE TITLE
multiup.org

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#762]
https://multiup.org/download/9de3d46376f3fe028e3e12a7e39ca1fe/_Over-Time__Kamen_Rider_Zero-One_-_04__27502966_.mkv
https://multiup.org/download/7bcccfc352a77797c783df47b6e35e5b/_Over-Time__Kamen_Rider_Zero-One_-_03__B1BC46CB_.mkv

can you make a bypass for this website because every time you click the filehosting for the first time is always redirected to the ads site even by using ublock origin

**Comment by timmyRS** [comment]
I don't see anything to be bypassed.

But I can give you some useful links:
- https://transmissionbt.com/
- https://nyaa.si/?f=0&c=0_0&q=kamen+rider+zero-one

**Comment by Arsindy** [comment]
ok thanks

**Comment by ikancupang** [comment]
@timmyRS maybe what Arsindy meant was like this:
```ruby
document.querySelectorAll("form > button[namehost]").forEach(e=>{
	let a=document.createElement("a")
	a.href=e.getAttribute("link")
	a.setAttribute("class",e.getAttribute("class"))
	a.innerHTML='<i class="fa fa-fw fa-download"></i>'+e.textContent
	e.closest("footer").replaceChild(a,e.parentNode)
})
```

**Comment by Arsindy** [comment]
yes there is always redirected to amazon and others ads site

**Comment by timmyRS** [comment]
I don't see any difference in functionality, but if you say it's better, let's put it in.

**Comment by Arsindy** [comment]
thank you so much. now the original link is visible and directed to the original destination. can you also add an auto submit button like other mirroring site. (mirrorcreator) 
on this button
![Annotation 2019-12-22 174643](https://user-images.githubusercontent.com/55402429/71320807-46124500-24e3-11ea-8abb-73b71b6a5ec3.png)

**Comment by Arsindy** [comment]
you are amazing. thanks a lot

**Comment by Arsindy** [comment]
@timmyRS button with captcha
https://multiup.org/download/7b13b544f1202430ee747ac11222590d/OnceDDL_Shameless.US.S10E10.Now.Leaving.Illinois.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
