### ISSUE TITLE
was this not correct button cannot change the correct destination in crowdsourced

### ISSUE THREAD

**Issue by RaveN0X87** [timmyRS/Universal-Bypass#764]
https://ouo.io/9qzJEu it should be https://drive.google.com/file/d/1v9ULEMXC3O8h6qOpzXMIQH4NSxI-EC6a/view

after you click the was this not correct button and pass it to the destination page and open the same link 
the destination of the crowd bypass can't be changed

**Comment by timmyRS** [comment]
I've cleansed the database of the offending records.
