### ISSUE TITLE
this site's not working

### ISSUE THREAD

**Issue by smilefate** [timmyRS/Universal-Bypass#771]
[lnk.news](https://lnk.news/) & [uiz.io](https://uiz.io/)

**Comment by timmyRS** [comment]
Could you provide an examle link?

**Comment by smilefate** [comment]
https://lnk.news/2jfog & https://uiz.io/sdMqe

**Comment by timmyRS** [comment]
All seems to be working fine.

**Comment by smilefate** [comment]
Why doesn't he work for me? 
Version: 11.18

**Comment by timmyRS** [comment]
Because you're using Google Chrome. See #738.

**Comment by smilefate** [comment]
oh, damn it chrome.. Can't we update manually?

**Comment by timmyRS** [comment]
Unfortunately, the only way to get extensions on Chrome is through the Chrome Web Store. You download and install it manually, as described in #738, but that'll only auto-update the injection script, not the extension.

**Comment by smilefate** [comment]
Oh, Thanks ♥
