### ISSUE TITLE
sweetlantern.com

### ISSUE THREAD

**Issue by FinderID** [timmyRS/Universal-Bypass#772]
https://sweetlantern.com/?id=Nm56S1kxTkNUNFNIWmVvRjE3QXFyTXNlUzhLMmFXeWhRVjF2bHZObWkzQ0JhaWVKbFY4WkQ1b1FJc1djZ1dBQ1JST0pMS21rdjYzY1dKOUhHa2xzQ3I2SjVvdEtHRnNqZXFiVVppSDdZaDA9

**Comment by timmyRS** [comment]
Where did you get that link from?

**Comment by FinderID** [comment]
https://pahe.in/iron-will-1994-nf-web-dl-480p-720p/

**Comment by FinderID** [comment]
https://pahe.in/?dd1fa7bc42=RFJacGpvUDBvZlNIU2x6M3dTVnk1aWtqZ2Q1aFhNRlF2TjV5Q3VFS3Y3L1Y2Y1FHRFVzdVZnS0pVZFZmZ09ZbjVEcVgxWXpUQTl2WFRXcm9YWUxid3c9PQ==

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
