### ISSUE TITLE
infotekno.net

### ISSUE THREAD

**Issue by FinderID** [timmyRS/Universal-Bypass#774]
https://infotekno.net/?id=NGo2T1BtVFRLci9UN3FCT2NlWmdmUHNxVTA4b29KNW50K2Ntd0dwQkFNMEF1djVMTDFGaTNDSmc0N2toazhaL1FRTWl4TWw5VEZXZFo3SG9IZkpxbmVJanBFaFVzaDRWTjRlZUh1aHhvTStsbE9VQ0pSTk1CN0F3NGxVazNmTGQ0Lzc3aHJSeEdQS3ZaQ055bjRudU91YVc3UGhIYkFEQ1NEVVVrRUZXKy9RPQ==

source :
https://ad4msan.com/?9c2a6bf968=RnY2dzRRaFFhMXhDeTA1Mjk4WXRyV2hTeU44U3duSDFjNFFNMjJyYjZmQ3k4b0RTVWF5S0p6cjFvbWN6NkJZY0k5RmZ1M01DNDIxRE53d2pNQTEyZDNLOTN2M2h3amNhMjJzVkZQY1B2QktJVFlCTlNmeHZEUW9vZko0Y2poWnk0ZktBbTFDVEhDNllUWFkzWXJRVU9FNEJyWUNHakw3QzRwamNKek1BUHMwPQ==

**Comment by KagaKouko99** [comment]
another sample:
https://ad4msan.com/?9c2a6bf968=QlhIdnA5blFCYUFBRWppQzlzeTJ1c1lXd04rUG5oRnY2eStSK01RUkxoQXJXSDBoNmlRblVkNU5RcVZ3ZXVMaWpNbElialYrSDgveDgxd040SjNGWjgyOHN2SE54VENUUzVzbXFERlh1NzVOemxTUlVkc0hqZ1pDWi9vNXl6SkdWV0pENE1WL0xPL3htYS9hUHp4UWVsdms2VVk0NUxnSmdHZU8vb3hmSHFFPQ==

https://ad4msan.com/?9c2a6bf968=QlhIdnA5blFCYUFBRWppQzlzeTJ1c1lXd04rUG5oRnY2eStSK01RUkxoQXJXSDBoNmlRblVkNU5RcVZ3ZXVMaVJyL0FucnQ5MlMwc1FYM096eVNuQSt4T2FTeEdPMXBrb3R5WlFZczUzZ3k2K2w4U0xGbTcxUGxid1JnMGRjQWRhZ2ZOSEk2RkVPRWZDZ1FlbnVLTTRkeWZVcnlOb1FYa3ZkNGllMk5ZUWJrPQ==

Source link:
`https://ad4msan.com/windows-10-pro-19h2-1909-update-desember-2019windows-10-pro-19h2-1909`

**Comment by KagaKouko99** [comment]
doesn't work

**Comment by ikancupang** [comment]
It works for me, I've tried these links
```
https://ad4msan.com/windows-10-pro-19h2-1909-update-desember-2019windows-10-pro-19h2-1909
https://ad4msan.com/wondershare-filmora-9-3-0-23
https://ad4msan.com/far-cry-primal
```
All works well.

**Comment by KagaKouko99** [comment]
sorry, I tried again it works well

**Comment by WaferNabati** [comment]
@ikancupang another download button
https://ad4msan.com/fifa-17
