### ISSUE TITLE
anisatsu.com

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#776]
if possible. skip the captcha as well. it's very annoying https://www.anisatsu.com/

https://www.mispuani.xyz/4-keys-to-weight-loss?u=U2FsdGVkX1%2FC6Xiw5AAwfxFPNPho5Dm4H68QI5jWapWQskGXfj2wFrnQ3ySAbUJYmIISnSKXNeBIzTk8utXQApx6RDFxThcHMt9ikXhXqv%2BB8VaXpTuJPhNAUHvCOAn0EyRnHvwCUb4belAFKCMdnFK3IOGpWpEfQmtSnywibA1Xas6ZalTNDyvq5%2F%2FuVfPOzWUhy9sfVUcRnrPYRduSHvXcwVjvctOfY%2BGwo5WyXRgcaeztFMX4WtaW9K7SfWopZ8DcRdnrzOGNK3h2%2Bqn%2B%2FNYf%2BeIu2gbEFl2YfupAPGQRyvu%2FS%2FCnmFm8FgEnJ0bqhN2IlOTMFgeuMZqo%2FzUkLrahwwPW31WUtoLox0t0muAvRAxAOqTZbSmsbxeMoD5PzhJ9DcF%2F0PRZcfeel%2F6XBgqM1FCsOPkIawaQ0nVliII%3D

**Comment by RaveN0X87** [comment]
safelinkscript 
https://mispuani.xyz/spark-theme/sparklingkuv2.js
https://mispuani.xyz/spark-theme/sparklingku.js

**Comment by ikancupang** [comment]
Usually you use adblocker to block those safelink scripts right?
But you still want Universal Bypass to decrypt that safelink?
Well then.
