### ISSUE TITLE
pahe.in

### ISSUE THREAD

**Issue by Arsindy** [timmyRS/Universal-Bypass#782]
https://pahe.in/the-morning-show-season-1-complete-web-dl-480p-720p/
https://pahe.in/the-prince-of-tennis-match-tennis-juniors-season-1-complete-nf-web-dl-480p-720p/
https://pahe.in/sniper-ghost-shooter-2016-web-hd-480p-720p/

**Comment by Recehan-Slayer** [comment]
need update
`https://pahe.in/midway-2019-uhd-bluray-720p-1080p-2160p/`

**Comment by Recehan-Slayer** [comment]
@ikancupang need update
```
https://pahe.in/harley-quinn-birds-of-prey-2020/
https://pahe.me/harley-quinn-birds-of-prey-2020/
```
