### ISSUE TITLE
conan.id

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#790]
https://www.conan.id/?e7fc10d9e3=OTRIeXUrdkVnd0hSNlJ1VVEycDUrVTFPNGZRSXVEMWtkcThaa3V6MVV6Vlp5bDE4UHVVYzdJRWZRakd5Vlp4ZEF2andSRjRjUmR2UGo3blp6UE9yTXc9PQ==

https://www.conan.id/?e7fc10d9e3=OTRIeXUrdkVnd0hSNlJ1VVEycDUrYkJveW52eWtsSnkyb0dQRGpUcFVzWVpqTWxhblRmL3hVMWhVV1oxbmhpNVVBQkRWWkxRdkVQZWxpRDcxbVRyQlN4c3poV0MzZDExZUxmZkpsZk5Ya0dRQ0tNZ21UaVVQcGJSUndkSHBTM2JPN0tBWGFyc3pSdmw2cmFhcnZGL1VzbkN3Sm56QkRrNjRFYWdlK1R4c0xjUUZKSDlFSWNMQkU4K2J1aFkyc0ZDTWx5TXVvM1lTZituTWY1M3pWeXFxR01VWklKdjNBMFMybDBsQ3BINDZMUEhTRW1nMlZFRTF0VzdzVDhBQkJCeQ==

Source:
`https://www.conan.id/sword-art-online-alicization-war-of-underworld-episode-12-subtitle-indonesia/`
`https://www.conan.id/boruto-episode-138-subtitle-indonesia/`

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
