### ISSUE TITLE
New domain adtival (droidtamvan.me)

### ISSUE THREAD

**Issue by WaferNabati** [timmyRS/Universal-Bypass#796]
https://www.droidtamvan.me/hOLxAt
https://www.droidtamvan.me/SJq8TO

`https://www.durandalsub.ga/2019/11/azur-lane-episode-05-subtitle-indonesia.html`

**Comment by timmyRS** [comment]
Seems like it's already bypassed.

**Comment by WaferNabati** [comment]
@timmyRS yes in the domain (movienear.me)  it's already bypassed. but yesterday there was another domain that appeared not bypassed (droidtamvan.me)

**Comment by WaferNabati** [comment]
@timmyRS https://droidtamvan.me/WMKn
