### ISSUE TITLE
Link Vertise (Add - on Installation) bypass request

### ISSUE THREAD

**Issue by gold10star** [timmyRS/Universal-Bypass#797]
Link vertise Add on Bypass not working in this universal bypass version.

Please check and provide us the Injection code and guide us how to insert the same in the script.

Thanks in Advance

**Comment by timmyRS** [comment]
Just wait like 7-10 days for 12.3 to be released on Chrome.

**Comment by gold10star** [comment]
I have checked the latest version 12.3 using developer option. Its bypassing perfectly.

Thank you.

One request, Can you just provide us a script to remove add on extension to the version 11.8?

I wanna bypass this step by step only.
