### ISSUE TITLE
Changelog delivers a 404

### ISSUE THREAD

**Issue by Gitoffthelawn** [timmyRS/Universal-Bypass#798]
Happy new year!  And thank you again for Universal Bypass!

Changelog within extension v12.3 points to: https://universal-bypass.org/changelog-normal
This generates a 404.

Actual changelogs appear to be at:
https://universal-bypass.org/changelog-full
and
https://universal-bypass.org/changelog-firefox
and
https://universal-bypass.org/changelog-chrome

BTW, I strongly prefer changelog to be included within the extension, so it is visible within Firefox, without having to go to an external site.  This is standard across virtually all other extensions. :)

**Comment by timmyRS** [comment]
I've fixed the changelog link on AMO.
The reason the changelog is on the website is because it helps you understand the changes over multiple versions, not just with the latest version. And as of 12, a main part of the extension self-updates without an extension update.

**Comment by Gitoffthelawn** [comment]
Thanks for the fix.  I tested it, and it looks good. :)

A few questions, if you have the time:

1. When I now go to about:addons and look at the release notes, the link is fixed (without any official extension update).  Is about:addons pulling release notes data from AMO in real time?
2. When you say the extension self-updates, is it actually changing the extension's code, or just the rules?
3. I agree that seeing the full changelog is helpful.  Ideally, I'd like to see the most recent changes listed within about:addons, along with the existing link to the full changelog.  The best of both worlds. :)

**Comment by timmyRS** [comment]
1. Yes.
2. It's downloading the [injection_script.js](https://github.com/timmyRS/Universal-Bypass/blob/master/injection_script.js) every hour, which is the script inserted into websites.
3. That sounds like a good idea, and I'll try to implement that in the future, although lazyness may overcome me and I'll stick to just pasting a link in there.

**Comment by Gitoffthelawn** [comment]
Thanks for all your helpful answers! :)

1. I didn't know that.  Learn something new each day!
2. I've read why you are doing this, and the logic is sound.
  a. What security precautions are implemented and what security risks does it introduce?
  b. Is that JavaScript code inserted into each page, or does it actually change the running code of the extension?  If it's the latter, I'm surprised (but somewhat happy) that Mozilla / Google allow it, because it prevents the user from reviewing all the source code before installing an extension.  
3. Great!

**Comment by timmyRS** [comment]
It would absolutely be possible to download code to be executed with extension privileges, but Universal Bypass only updates the code that is injected into every website, alongside your userscript. That does theoretically loosen security a little bit as instead of someone having to hack my AMO account, someone would just have to hack my Github account, but I find it to be unlikely that a rouge commit comes through or that Github itself is hacked to deliver false data.
