### ISSUE TITLE
Some shorterners fail to bypass

### ISSUE THREAD

**Issue by LEO33SoFo** [timmyRS/Universal-Bypass#799]
This is the URL list I have encountered:

https://spiin.xyz
https://ckk.ai
https://oko.sh
http://glory-link.com
https://short.pe
http://clik.pw
https://adslinkfly.online
https://techsapparel.com

**Comment by LEO33SoFo** [comment]
@timmyRS Why is the issue closed? Is this already fixed?

**Comment by timmyRS** [comment]
Most of them I recognize as being bypassed, but I generally don't accept dumps as issues.
