### ISSUE TITLE
kontenajaib.xyz

### ISSUE THREAD

**Issue by nggomaen** [timmyRS/Universal-Bypass#807]
https://kontenajaib.xyz/?id=Wjg3eEthVHlubDRZTE1wdS9rRGVQV0hBYTlmM2Qva0hTekFEMEFoYkl2YmpqcEF3aGFydmVjb3JqQnJDVlBhczRxb2d2Um83dTR3WUFtOVlLVHJjbXZTMkJQam40US84RUZ0WlVua3JZUW5UUEZmUWV1YWhlQUhMbVdjUVFjbUdQTHV3bS9sSFR6NFM4eHpGSGRheS9LdkN5aXlSaUFQclhUeE00UWpkSjNuUld2S29JdElRNFp0SEg4K1pqTVp2ZTROeVFGWC9PMUtxRGpveTM3bnhtS29uNVVyRHJKL2pFWTVnZkNUTW9xS3VJbDd1ZlRXSU5vMi9abm0xM3d3QkE4U0JVU2JDZ3ovWS9CMHRoaUdYWW5aQ3p2U29pU3lkVlFGZ0lqNnNuK0l0bTdSbmZHMzEzZDdLTkNKcjJoR0ZpTHpTcFpzWlBEc0lUZTlLNnZRSnBvTWJaNGpZcmtkWEFMeEFyYUpRbG9rPQ==

pls add this. thanks in advance

**Comment by timmyRS** [comment]
Where did you get that from?

**Comment by its4win** [comment]
I think the source from any download link in https://www.oploverz.in/

Its same as my issue on 
https://www.oploverz.in/one-piece-episode-916-subtitle-indonesia/

Example:
https://kontenajaib.xyz/?id=eFBtT2o0T1ZNUFRuaWZHcUJXUmVvMEJReGtXelFVckdTTUt0S1pkSGEza1E1ekZCUU5GalVrYnRra3pYQ2Q2cmFvOU9rZ2JDdGxPSWw4RFd6VmhhbjcxbzVicXg2RTB5QmRKNWYzeXowaFhUU2t0YS9oWlYrYmZXUk85L1RwQU1DRHJzV2phVnZHWEhQZ2t0SHNEMmJOYlNmRjJ6ei9iWHdXdlBhdWNwUUQ3bmhZVlk0cWVFWDBrdnNCT3ZsU0tTYzJuU29KRzRxZFpPR0I1aGZjdnpTNzhnQ0E1SFVqM2VtL3A2VGR0STR1bW1wbFZCZ1RwT2ROSGkwU1VCWmE0Zg==

-and-

https://www.oploverz.in/one-piece-stampede-subtitle-indonesia/

Example:
https://kontenajaib.xyz/?id=aEVCZ1plaFVVODMwWnVpbUZLRTh6REVZSmkwV3NKOUp0VjdmY0R1OHVScE1PTlg1WmRCSUthcnp2em1TNUF4Z3FpcmRhQnFCdUpDcW5pODJSSVZVUzVYUXl4V2JEL3lyblZIM2NyUEpTYUlZVVFFL0ZWZEJCYXhOdjhqamRCRUN4alJJUzVOSzVldFBIcUxXSlVLTGhQWVhpeFJpdUNTRCtmU1Q1ZmpvZXJnRmFseTNHVjVnZ2FjY3RocVBOUHFvM0ZzMUFVMXZxUGpqa1d3TUZ0enRnWnNlUmlmbTI3TUFwR2wreUs2VGVwaHVXRGw2WmlucVlQY1VIR1JKZkg1ZQ==

**Comment by Username778** [comment]
Same. When i arrive at kontenajaib, i got bad request.
Damn you shortlink

**Comment by nggomaen** [comment]
> Where did you get that from?

Sorry for late reply. I got from oploverz.in. I think from this one
https://www.oploverz.in/darwins-game-episode-01-subtitle-indonesia/

**Comment by timmyRS** [comment]
@ikancupang I've adjusted the backend to accept longer links.

**Comment by ikancupang** [comment]
@timmyRS The backend still can't accept longer "path".

**Comment by timmyRS** [comment]
What do you mean? I think it's long enough for this bypass.

**Comment by ikancupang** [comment]
@timmyRS Please try this example link https://github.com/timmyRS/Universal-Bypass/issues/807#issue-545337839, crowd bypass doesn't work, then try using this commit 7ef76e4, crowd bypass will work.

**Comment by timmyRS** [comment]
I see, that's a bit longer than I expected.

**Comment by Recehan-Slayer** [comment]
@timmyRS @ikancupang please update. The unique id always changes when you refresh the page or for other visitors in the first safelink. but in the second safelink it isn't.
for example `https://www.oploverz.in/plunderer-episode-04-subtitle-indonesia/`

**Comment by ikancupang** [comment]
@Recehan-Slayer Your example link works well for me.

**Comment by Recehan-Slayer** [comment]
@ikancupang  for example . these two links go to the same destination `https://www16.zippyshare.com/v/LN0BORaf/file.html`

`https://kontenajaib.xyz/?id=TzJ1Y2xNZDR6ZVpxLzBSOHdjd2l2aFZ5d1NBdjdzbVluWHp4UFl5a3p2M0RBVUxpQmtPZW04V0pDTHQwaVNoVEJhTnUxMlJzc3JpVFh3dkI2RzdSS0pRTSs0c0RNdXVFVEs0MFRGZmpvQy8vYm02K1U0SXBpZnhndXcxWGxxbUl4TUdMaWdwOFNjclB5dGRGTHAybVRwdXVDZ2ZBSlpUYmxzSHdnYktVRjlOY2krN3M2VklVSTAxd09McTRzeFUyVXVTTDRERFpJK1VyakxQN2dSU3hJaVM1NU14a3pLaVJhWmNWTzUvNnppSTNuQlk3ZTZEc2VTNlVjU0FVdGROc3p1NHZUNCtTYjdwRFUwNndVaTZLL2djVVdnZVpGNk9NZ3p6Qjh4SkR0akpOdkZzc1J5K21wRmZhdm9qYVRPeUw=`

`https://kontenajaib.xyz/?id=eGlFaStacDFoQU5ZaGtHSTROVFcxU21TVEE5Wk1aM2NDT0N3aW1EMnBiUW1QeXdjUEhCQWZpS1ZtejB1QmhlTUFGcnN4YjlHZ29rUGVjZ29MMDNHejl0bWx2V3JaS2hjSGN1YVRrYlMyVjZ3LzRZMkRHZ0hrWlp5eC9BK0hQQnQwSXpRZHRncDFJM2xiZTNOV2xtRjQwSWRTeDRUS3JQb3BpaUVWWHlvU3dzN0E3NnBEL3VuWDBQRVhuanV6dFV1SXNwTHM2NXFibENrNlFkakVqeUw5NTVrd3dhdEFsRk5zV1BkUWRRWi9XMGVpb1liTSs3WGxpcG5rKzF4eXE2dHZFTWVpRTZMRXB0b1dlendMQWUwWWZkTk12cWNaZUZRNHBNUFZ5L3lnVlljbVhVNGM4dVljT0FPV0gzKzU1WmY=`

**Comment by timmyRS** [comment]
This is an issue with a lot of websites using the soralink template (https://github.com/timmyRS/Universal-Bypass/blob/master/injection_script.js#L1022-L1066) I have just been too lazy to implement the logic for all of these irrelevant websites literally no one uses.

**Comment by ikancupang** [comment]
Interesting, I've tried refreshing the page several times and changed the IP, the results are still
`https://kontenajaib.xyz/?id=Q3VTY3BGclVTMnJ3eStFRG1pQ3FtMFRqTUhOdG1kZElhUTNPZjB6dGt4M3NTYjlPQjNJREpnNFZKYnB5TWhlVURDNC9qVWZjREloV3p1RjJwRWoxYnkrcHV5SGhmYVFUUkhUNlFLUFZ0Y3VPZDg0Q3RmOXJycGxGbUdkZnFTR0ZnT01rcTV6eEtGQVJuN0RHZ0wxWjV5NHNzVnZOaXIvVkRBSXVBY3hwbGhQeEZNMTN4Mm9RTGlpV1R5N3JVeWFEKzZMdDZrUm9HZ1pWcHpqVmgyMDhTa0ROcURnYytxeHNFd0pVMUo2TDNrV3VEdjlLRlRwWjZDdC9meGZSQytIWS84VXZuQzRZYitObXZ0S2lzOGwzV1l1dmNqa2ZqbTlzaHBvQ0tobEhoMGZDVkRrVzBybkJMbFNLdTZMRXlwVXE=`

**Comment by Recehan-Slayer** [comment]
maybe, try clearing cache cookies . or using vpn

**Comment by Recehan-Slayer** [comment]
maybe, try clearing cache cookies,different browser or using vpn

**Comment by Recehan-Slayer** [comment]
@ikancupang need updates `https://www.oploverz.in/haikyuu-season-4-episode-07-subtitle-indonesia/`

**Comment by Recehan-Slayer** [comment]
@ikancupang another new domain v4.hexafile.net
`https://www.oploverz.in/boruto-naruto-next-generations-149-subtitle-indonesia/`

**Comment by ikancupang** [comment]
2f7ced9
