### ISSUE TITLE
Request Bypass shrink-service.it

### ISSUE THREAD

**Issue by LukePoke** [timmyrs/Universal-Bypass#81]
Example: https://shrink-service.it/s/Bu0RXl

**Comment by LukePoke** [comment]
Here is the list of eps to download:

https://redanimedatabase.forumcommunity.net/?t=54083371

It's the latest Hellsing Ultimate (OAV) Full HD Sub ITA list

**Comment by timmyrs** [comment]
It looks like I need an account to view that. Whenever I click on your shrink-service.it link, it directs me to gearbest.com and nothing else even without any extensions. I'd say that site is broken.

**Comment by timmyrs** [comment]
I've just figured out a way to bypass it despite it being broken. Going to implement it now.

**Comment by LukePoke** [comment]
Thanks so much!
