### ISSUE TITLE
animeskuy.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#812]
https://animeskuy.com/?6166a85f5c=aGlxT3o2eUEwS2NPU3VkVWFJZTYzek1reWlvanZKNDdya0VnMktvZ3FrcGJXaVhRU0RlTm9yS2MzN2NXSjdIbi83SDgxcldXQXg2SkpqS3JvaVJMVHc9PQ==

Source:
`https://animeskuy.com/messiah-s01e01/`

**Comment by DineshSolanki** [comment]
when I open Firefox Developer tools on this page, my browser stops responding and this happens, can you tell me what's happening, I'm still learning web.
![image](https://user-images.githubusercontent.com/15937452/73604023-9d123c00-45b0-11ea-9d19-a1b9a0b51fc6.png)

**Comment by timmyRS** [comment]
@DineshSolanki There's a `debugger;` statement, you will probably have to disable breakpoints:
![image](https://user-images.githubusercontent.com/11009697/73604223-48a99500-458d-11ea-8cb7-33127461c5f8.png)

**Comment by DineshSolanki** [comment]
> 
> 
> @DineshSolanki There's a `debugger;` statement, you will have to deactivate breakpoints:
> ![image](https://user-images.githubusercontent.com/11009697/73604223-48a99500-458d-11ea-8cb7-33127461c5f8.png)

I thought that too, I tried that, it didn't work, after searching I found a link that addresses the same issue ( https://stackoverflow.com/questions/39766524/firefox-disable-debugger-keywords) unfortunately it is still not solved.

**Comment by DineshSolanki** [comment]
and I observed that the mechanism is same for the sites of the last 5 issues, so if this is solved, 5 issues could be solved. issue #810 #841

**Comment by timmyRS** [comment]
That's just the soralink template, I'd just have to put  "animeskuy.com" in the list that we already have in the code I'm just not bothered about it.

**Comment by Recehan-Slayer** [comment]
they now use an old version of soralink
