### ISSUE TITLE
keisekai.fun countdown

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#814]
http://keisekai.fun/fshare/file/8
http://keisekai.fun/fshare/file/9

**Comment by timmyRS** [comment]
file 8 and 9? is this site even of any relevance for anyone?

**Comment by KagaKouko99** [comment]
yes. source link `https://www.huntersekai.website/2020/01/magia-record-mahou-shoujo-madokamagica.html`
