### ISSUE TITLE
Website bypass request https://cpbild.co/

### ISSUE THREAD

**Issue by AlessandroDevITA** [timmyRS/Universal-Bypass#816]
The website is https://cpbild.co/ when a link is created it leads to human verification and surveys. Many YouTubers use it to link thier pages and it's really time wasting.

Thanks!

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by AlessandroDevITA** [comment]
> Could you provide an example link?

Sure! Here: https://cpbild.co/f2986bf

**Comment by timmyRS** [comment]
Unfortunately, there's no way to bypass that, but I personally wouln't recommend complying with that site. Just find another youtube video.
