### ISSUE TITLE
Wrong Redirection from the Wait x seconds page

### ISSUE THREAD

**Issue by Fuzen777** [timmyRS/Universal-Bypass#818]
Hey. Not a major issue but something that can be a bit puzzling, on Chrome 79.

When UB pops in with the wait x seconds page, there is a link redirecting to the options to quickly change the wait delay. However, that link leads to a “blank” options page. Any change made here does not impact anything and is discarded. (So you have to access this screen from the Extensions panel.)

**Comment by timmyRS** [comment]
Oh my lord, UB 12.3 is actually available on Chrome, I never thought I'd see the day.
