### ISSUE TITLE
Cannot create multiple custom bypasses

### ISSUE THREAD

**Issue by Shakeandbake** [timmyrs/Universal-Bypass#82]
When creating multiple custom bypasses, whatever script is visible when you press save is written to all other custom bypasses (making them all the same).

**Comment by timmyrs** [comment]
You should give them all a unique name.

**Comment by Shakeandbake** [comment]
They had unique names...

**Comment by Shakeandbake** [comment]
I am working around this by using one bypass for all domains and putting switches in the js

**Comment by timmyrs** [comment]
Jesus Christ why does the simplest of code not work in Firefox -.-

**Comment by Shakeandbake** [comment]
BTW Here is my custom bypasser that others may find useful. Bypasses lnkshrnk, autodownloads linx.cloud and bypasses the captcha on spaste.

if(document.domain==="lnkshrnk.net"){
  var myreg = /revC\(\"([^\)]*)\"\)/
  location.href = revC(myreg.exec(document.querySelector("script:last-of-type").text)[1])
} else if(document.domain==="linx.cloud"){
  let b=document.querySelector(".entry-content a");
  if(b){
    location.href = b.href
  }
} else if(document.domain==="www.spaste.com"){
  let b=document.querySelector("#captchaVerifiedStatus")
  if(b){
    b.click();
    setTimeout(function(){ 
      document.querySelector('div[data-id="'+document.querySelector("#currentCapQue").innerText+'"]').click();
      document.querySelector('div[data-id="'+document.querySelector("#currentCapQue").innerText+'"]').click();
      document.querySelector('div[data-id="'+document.querySelector("#currentCapQue").innerText+'"]').click();
      document.querySelector("#template-contactform-submit").click();
    }, 500);
  }
}
