### ISSUE TITLE
Bypass trackers breaks crowd bypass shorteners

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#830]
if bypass tracker is activated it will replace the original link
https://bit.ly/2FzmqmX
https://bit.ly/2tNDpPD

Source:
`https://www.extonan.web.id/jibaku-shounen-hanako-kun#ep-01`

**Comment by timmyRS** [comment]
I've fixed the issue in the backend, but it's not gonna be fixed for those links immediately.

**Comment by Recehan-Slayer** [comment]
@Sainan the issues reappeared. please fix it
`https://extonan.web.id/otome-game-no-hametsu-flag-shika-nai-akuyaku-reijou-ni-tensei-shiteshimatta#ep-06`

**Comment by Sainan** [comment]
It's always either too many or too little redirects...
