### ISSUE TITLE
Universal Bypass breaks topvn.xyz

### ISSUE THREAD

**Issue by ghajini** [timmyRS/Universal-Bypass#833]
I see error `invalid token/session` when universal bypass is activate on site....I have to manually disable universal bypass for website to work

URL = 
`topvn.xyz`

STR=
Make sure you have no cookies related to ouo.io/.press/ above website

1. Go to `topvn.xyz`

2.enter any site 
E.g

https://rapidgator.net/file/797ca8e689d8bebd1d2615ad3f848544

3. Proceed further you will get error

![IMG_20200112_172204](https://user-images.githubusercontent.com/20338483/72218340-1b566200-3560-11ea-825d-534658afa3f5.jpg)

**Comment by ghajini** [comment]
Also universal bypass is active I get wrong destinations
Eg during bypass of

https://oko.sh/z0yQBB

**Comment by ghajini** [comment]
Wrong bypasses. .......means universal bypass can redirect me to malicious site

**Comment by timmyRS** [comment]
This will be fixed in 12.10.
