### ISSUE TITLE
Linkvertise.com

### ISSUE THREAD

**Issue by WaterMaloneioe** [timmyRS/Universal-Bypass#838]
Instead of Directing us instantly please add an option where it just makes the ad timer 0 cause the destination says that it is not supported, but when i do it manually it works.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by Azks** [comment]
https://linkvertise.com/20540/proxokeyy

**Comment by timmyRS** [comment]
This is already bypassed.

**Comment by freshflowz** [comment]
[[ ](https://linkvertise.com/365707/freshflows)](url)

**Comment by freshflowz** [comment]
[]( [)](https://linkvertise.com/365707/fresh flows)
