### ISSUE TITLE
lnkshrnk instantly closes page

### ISSUE THREAD

**Issue by Shakeandbake** [timmyrs/Universal-Bypass#84]
lnkshrnk.net bypass now instantly closes page

Need way to be able to enable/disable individual hardcoded bypasses

**Comment by timmyrs** [comment]
Works in Chrome & Firefox when using latest Universal Bypass.

**Comment by Shakeandbake** [comment]
Sorry let me explain better. 
Here is an example link that eventually leads to lnkshrnk
https://linx.cloud/getlinx/https://linx.cloud/get-download/aHR0cDovL2xua3Nocm5rLm5ldC85bDltcA==

I believe the bypass is redirecting to the first link which is a false ad page. I stated that it instantly closed because I believe my ublock is instantly closing that page. If i disable universal bypass and interact with the lnkshrink page in any way, i can see the ad page it tries to pop open.

**Comment by timmyrs** [comment]
That also works in Chrome & Firefox using latest Universal Bypass.

**Comment by Shakeandbake** [comment]
I have the latest version of universal bypass, the page that its directing to is not the true link, it is a fake page. It is made to look like the download page but its not. Infact sometimes its just a full page of porn. I have even freshly installed firefox and only your addon to prove this. 
https://psarips.com/movie/skyscraper-2018/psarips.com/download/lKokxRVsW2MB2VlvPXfxzFC7dq0qJ4rWk/ZMImVVakJWIiLZlcmpiawsgUY+0fmLMt66EHFBCit7jHEGzpbd9g3R9NwK9Hdp5rST0l5T5qi3ve5UIKWBbT6VcD9b9J9j:KoX35TltWHCL1hHoMiAtFA==
Since the old link i posted expired, here is a link from a torrent website which uses lnkshrnk. The proper link should redirect to linx.cloud. Any other page you see is a false page. This worked last night so its something you added recently.

**Comment by timmyrs** [comment]
Both your links have been taking me to https://linx.cloud/skyscraper-2018-2160p-10bit-hdr-bluray-8ch-x265-hevc-psa73223/ which I assume is correct. You can temporarily disable Universal Bypass at `about:addons` and see if it works without Universal Bypass enabled.

**Comment by Shakeandbake** [comment]
I installed a firefox fresh (i normally use chrome) and only added your addon. With your addon enabled, it always redirects to an ad page once it gets to the lnkshrnk page. I cannot get to linx.cloud with your addon enabled. If i disable your addon and use the lnkshrnk page manually, the first and second click on that page opens ads in second tabs. The third click opened the correct link in a new tab, and redirected the original link to some porn website.

**Comment by timmyrs** [comment]
This is weird because I don't have these issues on the same link, but I guess I'll change the linkshrink bypass...

**Comment by Shakeandbake** [comment]
Thank you for fixing this. Btw my custom bypasser still works on that page.
var myreg = /revC\(\"([^\)]*)\"\)/
let s=document.evaluate("//script[contains(text(),'window.open(revC')]",document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null).singleNodeValue;
location.href = revC(myreg.exec(s.text)[1]);

revC is a function they embed on the page to decipher their own url.

**Comment by timmyrs** [comment]
Your script doesn't work for me.
