### ISSUE TITLE
wizardsubs.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#842]
`https://wizardsubs.com/2016/01/25/ultraman-tiga-the-movie-the-final-odyssey-subtitle-indonesia/`
`https://wizardsubs.com/2016/03/20/w-sxa-s-ultraman-tiga-episode-01-subtitle-indonesia-2/`
`https://wizardsubs.com/2019/12/22/kamen-rider-den-o-movie-cho-den-o-trilogy-episode-red-bd-subtitle-indonesia-x265/`
`https://wizardsubs.com/2019/12/21/saraba-kamen-rider-den-o-final-countdown-dc-bd-subtitle-indonesia/`

**Comment by timmyRS** [comment]
Crowd bypass seems to work fine here
