### ISSUE TITLE
can't bypass this

### ISSUE THREAD

**Issue by surya27895** [timmyrs/Universal-Bypass#85]
can't bypass from this site 
[http://www.shortsfl.com/2017/02/health-insurance-companies.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDd6ZSUxOVhyJTFGJTdEJTFGJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMTlfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM=](http://www.shortsfl.com/2017/02/health-insurance-companies.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDd6ZSUxOVhyJTFGJTdEJTFGJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMTlfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM=)

i think that an another variant of bloggerku template

**Comment by timmyrs** [comment]
If that leads to https://www1.zippyshare.com/v/7U7Zp1MR/file.html then it's already bypassed.
