### ISSUE TITLE
many short link

### ISSUE THREAD

**Issue by FinderID** [timmyRS/Universal-Bypass#854]
http://mediadebrid34.site/ads1/?file=78ff41dabc

there's any short link from this site

**Comment by FinderID** [comment]
![image](https://user-images.githubusercontent.com/57831066/72775169-32313000-3bc2-11ea-8615-c61c2bc7564d.png)

**Comment by timmyRS** [comment]
All of them are arleady bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
