### ISSUE TITLE
[Feature Request] Ignore/Whitelist domain

### ISSUE THREAD

**Issue by Jinkiesz** [timmyRS/Universal-Bypass#857]
Allow us to whitelist certain domain like localhost to be ignored by bypass

**Comment by timmyRS** [comment]
There's no bypass for "localhost" so you would have to have some sort of template set up there which is just generally bypassed. Either way, I don't see any use for this feature.

**Comment by ImportTaste** [comment]
@timmyRS Personally I just find it annoying for Google Docs/Drive because there are times I want to look at the Last Modified Date of the file to determine if I even want to download it. Universal Bypass will force the download to start regardless.

Would creating a custom bypass that essentially does nothing override thee default injection scripts, and if not, is there a way to get it to?

**Comment by Sainan** [comment]
> Would creating a custom bypass that essentially does nothing override thee default injection scripts, and if not, is there a way to get it to?

No & no, but it's easy pretty to disable Universal Bypass temporarily.

**Comment by halotroop2288** [comment]
> Personally I just find it annoying for Google Docs/Drive because...

...Universal Bypass crashes every Google Drive download page.

If they're not going to fix the issue, at least provide me a way to get around it.

**Comment by Sainan** [comment]
> Universal Bypass crashes every Google Drive download page
I have never encounted that. Maybe report this issue with steps to reproduce?

**Comment by ImportTaste** [comment]
It happens to me as well, the only actual step is opening a google drive download page.

**Comment by Sainan** [comment]
Open a new issue.

**Comment by ImportTaste** [comment]
> Open a new issue.

I'll pass.

**Comment by Sainan** [comment]
Jesus fucking christ. Alright then, as long as your comfortable in your cowardice.

**Comment by halotroop2288** [comment]
> No & no, but it's easy pretty to disable Universal Bypass temporarily.

First, you refuse to help in the way the user reporting the problem suggested.

> Open a new issue.

Then you tell us to open a new issue, knowing full well that you could have solved it already.

> Jesus fucking christ. Alright then, as long as your comfortable in your cowardice.

Then you call us cowards for not immediately bowing to your whim.

> Can't reproduce in Chrome or Firefox. [...] Ensure your UB is up-to-date.
> **@Sainan closed this** (#1751)

Then you close the issue I made, as you requested, immediately, without offering any other solution but to "ensure the extension is up to date" (which obviously, it is. Or I would not have come to Github to investigate it or make a report.)

You are astonishingly rude and I hope someone forks this project so we never have to deal with you again.

**Comment by Sainan** [comment]
If you can fix the issue yourself, then you wouldn't report it. In this case, it was not an issue with Universal Bypass. So, all good.
