### ISSUE TITLE
icutlink.com

### ISSUE THREAD

**Issue by bcn09722** [timmyRS/Universal-Bypass#859]
example link
https://icutlink.com/fAAQeYRQb

It redirect to
https://educationstark.xyz/fAAQeYRQb
and it will go to
https://newsten.online
There is a countdown, wait for the countdown to end, it will redirect to
https://icutlink.com/fAAQeYRQb

**Comment by ikancupang** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
