### ISSUE TITLE
new domain shrink.world (liveshootv.com)

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#863]
new domain (liveshootv.com) from shrink.world `https://www.adshovel.com/`

https://www.liveshootv.com/pZf07maE
https://www.liveshootv.com/b4B2tH
http://www.shrink.world/R3w1r2ah

**Comment by Recehan-Slayer** [comment]
new domain (modebaca.com) from shrinkads.com

http://www.modebaca.com/7Ed1
https://www.shrinkads.com/PqNy7J

**Comment by Recehan-Slayer** [comment]
@timmyRS please fix. crowd bypass always bring to the wrong destination link
https://www.shrink.world/y0nhHW supposed to `https://mega.nz/#!pJoiEYAZ!2mwisKg0Y5OgkTVkUU__kboBW3Gq6g_WU_uCG1pNdg0`
https://www.shrink.world/nr6pi supposed to 
`https://sharer.pw/file/Zl3P-u8rCLp`

https://www.shrinkads.com/3sncky supposed to `https://mirrorace.com/m/2WEbr`
https://www.shrinkads.com/VfRfRp supposed to `https://mygavilan-my.sharepoint.com/:v:/g/personal/yuki_fansub_my_gavilan_edu/EYNCU_EOKIhClGdQnF9ooVQB66emnc8QO04IdGSCFp1xWA?e=7kVa2f&download=1`

**Comment by timmyRS** [comment]
Works in 12.5. Use Firefox if you care for updates.

**Comment by Recehan-Slayer** [comment]
doesn't work with both firefox with latest version and chrome with current master version.
for example this link `https://www.shrinkads.com/3sncky` always bring to `geraifilm.com` 
all extension are turn off except universal bypass

**Comment by Recehan-Slayer** [comment]
@timmyRS add the shrink.world domain too 
for example  `https://www.shrink.world/y0nhHW`

**Comment by Recehan-Slayer** [comment]
@ikancupang new domain link.mymastah.xyz and liveshootv.com

**Comment by Recehan-Slayer** [comment]
new domain sportif.id

**Comment by Recehan-Slayer** [comment]
@ikancupang new domain cararoot.id

**Comment by Recehan-Slayer** [comment]
@ikancupang add haipedia.com `https://www.shrinkads.com/syLTyOUP`

**Comment by Recehan-Slayer** [comment]
@ikancupang new gubukbisnis.me

**Comment by Recehan-Slayer** [comment]
@ikancupang new domain `apk.sekilastekno.com`
