### ISSUE TITLE
hinime.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#864]
https://hinime.com/?124ffe9b89=Q0U4V1FBOXBKYVNZMGZjNDZDWGR1Y280NTZhWE5JRHVOY2RwbWRGblM5U21ZWlRlS0ZWdUsraXM0aEVXcHdhQTlyMnpmdlFsSVNTTUc0MlptZStqSm01cXhtS01QR0NFcng2LzRwTFdwZlBUNmJqSi9mTElOMWdmRFFRSUpLR2Q=

Source:
```
https://hinime.com/kandagawa-jet-girls-sub-indo/
https://hinime.com/black-clover-sub-indo/
```

**Comment by DineshSolanki** [comment]
It seems, that the website needs no more bypassing, they all are direct download links.
