### ISSUE TITLE
bakadame.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#865]
https://bakadame.com/?e41b7e5034=YjRsL09lUGJCUlN5OEVaK0I3VENxUWxOSkpBQ2Nld2U4YkVXcEljTmM2a3lwWkZGYkZmK0VrbndnTWhxSno4SEFIdkFzK3I2dTd4VlZ0dU1vNUQ5alUvTDIwWmFwM0dWZURVZlJvQkxydmQwQVVIVTF6Nnc2cFdPU2lIR2tLNmp4cW9Ob1cxM0lRVlRXYXRhT0h6ZCthY1VLZWlTRDZTUWJkVWUzUEsyQU5nPQ==

Source:

`https://bakadame.com/one-piece-sub-indo-batch/`
`https://bakadame.com/doraemon-movie-sub-indo/`
`https://bakadame.com/manga-bokutachi-wa-benkyou-ga-dekinai-bahasa-indonesia/`
`https://bakadame.com/light-novel-youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-bahasa-indonesia/
`

**Comment by timmyRS** [comment]
IDs are generated uniquely per user here.
