### ISSUE TITLE
sht.io

### ISSUE THREAD

**Issue by KagaKouko99** [timmyRS/Universal-Bypass#866]
https://sht.io/ku54
https://sht.io/ku55

**Comment by timmyRS** [comment]
What is there to be bypassed?

**Comment by DineshSolanki** [comment]
> 
> 
> What is there to be bypassed?

there is nothing to bypass, just two clicks to get to destination. maybe he meant that.

**Comment by KagaKouko99** [comment]
click continue twice. but if there is nothing to bypass you can close this issue.
