### ISSUE TITLE
nexusmods.com

### ISSUE THREAD

**Issue by ccsimplyspolit** [timmyRS/Universal-Bypass#873]
https://www.nexusmods.com/witcher3/mods/1021?tab=files

can't download

https://www.nexusmods.com/witcher3/mods/1021?tab=files&file_id=25280

https://universal-bypass.org/bypassed?target=%23ERROR-download-location-not-found&referer=https%3A%2F%2Fwww.nexusmods.com%2Fwitcher3%2Fmods%2F1021%3Ftab%3Dfiles%26file_id%3D25280

```
Universal Bypass is not supposed to bring you here.

Make sure that you have allowed Universal Bypass access to all websites and not just when you click the extension. If that didn't fix it, please open an issue with reproducable steps and information about your browser. Note that only Google Chrome, Firefox, Edge, and Opera are supported.
```

**Comment by timmyRS** [comment]
Works perfectly fine using 12.0+.
