### ISSUE TITLE
Problem loading images from thingiverse

### ISSUE THREAD

**Issue by scmanjarrez** [timmyrs/Universal-Bypass#88]
Hi,
I've been using Universal-bypass a lot, but I have noticed that everytime I try to open a new link using the wheel button (Open Link in New Tab) in thingiverse (https://www.thingiverse.com), images are not loading. 
I'm not sure why it is happening, but when I disable the addon, the open in new tab works perfectly. I have checked the debugging console, but no error is appearing.

![image](https://user-images.githubusercontent.com/9284124/47577800-14860400-d948-11e8-8667-39069c86a40e.png)

![image](https://user-images.githubusercontent.com/9284124/47577819-1c45a880-d948-11e8-800b-a05ee7d73f13.png)

**Comment by timmyrs** [comment]
Images work fine for me with and without Universal Bypass in Chrome and Firefox.

**Comment by scmanjarrez** [comment]
I have tested it again in Chrome and it doesn't work, I'm using vanilla Chrome for the test.
How did you test it? You must click several times in the wheel button opening several times at the same time, not one at a time, then you open the first one and no images loaded.
![image](https://user-images.githubusercontent.com/9284124/47605411-77d66b80-da06-11e8-8896-3288e6311fa5.png)
![image](https://user-images.githubusercontent.com/9284124/47605413-7c028900-da06-11e8-8b9a-0e90c0d32989.png)
None of the tabs have loaded the images.

**Comment by timmyrs** [comment]
I have this issue with and without Universal Bypass. The site is just rate limiting you when you're loading too many images too fast.
