### ISSUE TITLE
[Suggestion] Crowd-Bypass message

### ISSUE THREAD

**Issue by Cyberavater** [timmyRS/Universal-Bypass#890]
It'd be nice if the **Was this not correct?** message was shown at the bottom right corner just like the message **Unfortunately you are the first to encounter this link**.

Thanks!

**Comment by timmyRS** [comment]
I understand that many users are annoyed by the crowd bypass message, but it would be too easy for a bad actor to replace the correct link via a 51% attack and then make Universal Bypass lose track of the "was this not correct?" message on the bottom right.

**Comment by Cyberavater** [comment]
I didn't fully understand you (maybe I'm not aware of the technical term). But were I successful to convey my suggestion?
Simply put, my suggestion was to remove the need of whole page for just a short message. If you already understood it and think it's not a good idea then it's understandable.

**Comment by timmyRS** [comment]
I understand, I just think it wouldn't be possible to implement it in a way that I and by extend the users would be happy with.
