### ISSUE TITLE
h-gen.xyz

### ISSUE THREAD

**Issue by awh46722** [timmyRS/Universal-Bypass#905]
Universal Bypass does not work in the redirection process from this site to linkvertise.net.
It worked without a problem in January 2020, but when I tried it in February, it didn't work.
I am using the extension program together with the ublock origin, noscript.
Based on the error, the Universal Bypass seems to have been blocked
For your information, January was used in the same environment.

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by matt1tk** [comment]
@timmyRS Go to the site and pick one at random, it's not really possible to provide an example

**Comment by timmyRS** [comment]
Sitting on that page and waiting for over a minute, I think you're asking for it.

**Comment by matt1tk** [comment]
Yeah think the site is broken. before this I was able to use UB to bypass it just fine.

**Comment by timmyRS** [comment]
I didn't even use UB in that test just now. I think the website is just broken.
