### ISSUE TITLE
[Request] Gplinks.co

### ISSUE THREAD

**Issue by Chetan7575** [timmyRS/Universal-Bypass#919]
Sample Links: 
https://gplinks.co/HgmZ
https://gplinks.co/MathsLibarty2020

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by Chetan7575** [comment]
Thanks**Dude**

**Comment by Chetan7575** [comment]
> This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

Any way to bypass the whole site all links?

**Comment by timmyRS** [comment]
Unfortunately not.

**Comment by darkRaspberry** [comment]
Thanks very bad

**Comment by darkRaspberry** [comment]
Still having issue.
