### ISSUE TITLE
ENTER DOMAIN HEREhttps://shirosafe.web.id/id/D6MwY

### ISSUE THREAD

**Issue by CoronaVirusG0** [timmyRS/Universal-Bypass#923]
Before you report a broken bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/timmyRS/Universal-Bypass/issues?utf8=%E2%9C%93&q=is%3Aopen+ENTER+DOMAIN+HERE
I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.

If that is not the case, please **provide an example link.** I need to be able to see what has gone wrong in order to fix it.

**Comment by timmyRS** [comment]
Ha, not quite what I'd like, but I guess ends the cat & mouse game nicely. Re #900.
