### ISSUE TITLE
kontenajaib.xyz via animekompi.web.id

### ISSUE THREAD

**Issue by skyway34** [timmyRS/Universal-Bypass#934]
https://kontenajaib.xyz/?id=V3pDeTBaTTRmc24vbzZxVm5uZEwwK0FiRGw2M1h0cnBGZFV4alFsWDY1Q2t5ZG5ZUDMyT0owaUdQaGQ2T3IwU04wU1lRbFd6MHp3SzlWUXpjSEpRZzY4MFdRNDVaME9VL3FQSXpJTytJcENraFpGdERPWk5NcFNNaXJDWTloNTE0SEhSclFuVkRTSnhmUkJnQnJNQ2VpVkFkTWQzaW15bUx2S2R0ZGttaFRwSWNHeHdJQVU1YWUxWk9ZRHAyMFFmY2VzZGVYN2FZNk5CbXJhcHlPV3MvTS9aR3RheENtOW9WcTM3a2JYWEF2S2NvWjBHSXlDUnNSYkI4UXhLMFZOSjkvMGhiTmpJYitWMVZQN3QzcjNKVTNreTdJem9mS1BVWHZId2ZndkEyN2pwVG95OVJkVExXOHFwd1c5REVCU1c=

**Comment by skyway34** [comment]
source
https://www.oploverz.in/darwins-game-episode-06-subtitle-indonesia/

**Comment by Recehan-Slayer** [comment]
https://github.com/timmyRS/Universal-Bypass/issues/807 Already bypassed by crowd bypass.

**Comment by timmyRS** [comment]
Since they use the same naming as oploverz, we could just apply the same bypass there. Either way, I'm not bothered.

**Comment by Recehan-Slayer** [comment]
on the animekomi site. they don't use soralink templates or anything like that. they just copy the link from the original sources. and some of the posts don't even use safelink.

**Comment by ikancupang** [comment]
This is already bypassed by crowd bypass, `animekompi.web.id` doesn't use soralink template and just copy paste the links from `oploverz.in` so IDs are not uniquely generated per user/session.
