### ISSUE TITLE
encurta.eu

### ISSUE THREAD

**Issue by LGLTeam** [timmyRS/Universal-Bypass#941]
By visiting this link: https://encurta.eu/rkBt9rW6

It redirect to wrong url https://www.anuncio.encurta.net/ instead the real one which is mega.nz https://mega.nz/#!jlUmjAbQ!L2G1ESflo7iHagLHgztaKioPvNbKLn3dYj9YBB106bA

**Comment by timmyRS** [comment]
How did you get that mega.nz link? Maybe it's just my inability to speak French, but I can't navigate that page.

**Comment by ikancupang** [comment]
@timmyRS 
• click the Invisible reCAPTCHA button `Clique aqui para prosseguir`
• wait in 9 seconds `Por favor, aguarde...`
• the link is on the second `Obter link`

Seems like `Was this not correct?` button is not working properly.

**Comment by timmyRS** [comment]
Thanks to that change, and me cleaning up the backend, this site is bypassed properly now. :)
