### ISSUE TITLE
Website Not Bypassed

### ISSUE THREAD

**Issue by niemant** [timmyRS/Universal-Bypass#943]
Hello,
https://earnload.co/IbMQD is not being bypassed it gives the following message:
Please disable Adblock to proceed to the destination page.

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

For an extension that protects your adblocker, check out https://github.com/jspenguin2017/uBlockProtector

**Comment by niemant** [comment]
I've already tried it, before using UBypass, and It's not working.

Regards.

**Comment by niemant** [comment]
You might not have to wait!

Other Universal Bypass users have already waited for you and reported that this leads to https://pastr.io/view/lMwtuEqDj6x

Was this not correct?

Do you want this to be opened in a new tab instantly or in x seconds? Change Universal Bypass' options.

**Comment by timmyRS** [comment]
You can use UB in conjunction with Nano Defender, and now because I've waited on that link, you can see the crowd bypass in action.

**Comment by niemant** [comment]
I might not be understanding this, it redirects to:
https://pastr.io/view/lMwtuEqDj6x

That contains the following:
Email:- jazznlydia@yahoo.com
Password:- 1133

I use Ublock Origin.

Regards

**Comment by niemant** [comment]
I get It regards.

**Comment by niemant** [comment]
But every different link from that website is the same:
![2020-02-18 10_47_34-EARNLoad (By GPlinks 2 0)](https://user-images.githubusercontent.com/20712470/74741773-2b86ee80-523c-11ea-9a82-d1c954d5dae0.png)

**Comment by timmyRS** [comment]
Where did you get that earnload.co link from?

**Comment by ghajini** [comment]
@timmyRS ,From movie site ; moviesrex.in or
`https://moviesrex.in/the-dark-knight-rises-2012-imax-bluray-dual-audio/`

@niemant for antiadblock issues use ublock origin and report antiadblock issues at https://github.com/uBlockOrigin/uAssets

**Comment by timmyRS** [comment]
This will be bypassed properly once you get UB 13.3 or higher.

**Comment by niemant** [comment]
Telegram groups.
They use earnload a lot.

Regards

**Comment by timmyRS** [comment]
Well, don't be in shady telegram groups. :)

Unfortunately, crowd bypass is the only way to bypass that site, and it works as intended.

**Comment by niemant** [comment]
I added this filter and it worked like a charm:
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/460abd01a21ee17893ada6e377c16098a369f540/filters/ThirdParty/filter_120_AdBlockID/filter.txt
