### ISSUE TITLE
Not working on https://1link.club/

### ISSUE THREAD

**Issue by connorclark65** [timmyRS/Universal-Bypass#944]
Hi there, love the extension. been working great on some websites, but i've been running into one site where your extension doesnt seem to work. could you take a look? thanks!

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by ikancupang** [comment]
I have tried this example link `https://1link.club/15151`, it seems to work well.

**Comment by connorclark65** [comment]
oops, my apologies. i didnt have it set to all the time. however, it seems bypass isnt able to work on cutdl.xyz? an example: https://cutdl.xyz/tOFJ

**Comment by ikancupang** [comment]
`https://cutdl.xyz/tOFJ` it does seem to work for me.
