### ISSUE TITLE
Options: How to disable "You're almost at your destination" page

### ISSUE THREAD

**Issue by teohhanhui** [timmyRS/Universal-Bypass#945]
I've read the changelog and it seems like I should be using:

"Take me to destinations after `0` second(s)."

I also have this option enabled:

"Instantly take me to destinations of trackers."

But I still see the "You're almost at your destination" page. How do I disable it entirely?

**Comment by timmyRS** [comment]
That page is always loaded to avoid issues with Chromium browsers stopping UB from redirecting you, but it does still instantly navigate you. However, if the destination takes long to load, then you will see that page in the meantime.

**Comment by teohhanhui** [comment]
Perhaps an option to replace it with a (visually) blank page would be nice. So that it gives the impression of a redirection without the visual noise.
