### ISSUE TITLE
turkdown.com

### ISSUE THREAD

**Issue by ekardon** [timmyRS/Universal-Bypass#946]
Hello, I coma across a bunch of url shortener websites with Google Recaptcha v2. I am not sure whether you can bypass them or not but here is the link for the mentioned shortener.

https://exe.io/wHr8F
https://exe.io/Z7a7F
https://exe.io/e6Dxj1cv

**Comment by ekardon** [comment]
crowd bypass won't help it because, the website i use create this shortlinks on the fly. Noone else other than me will have those links. Shame :/

**Comment by timmyRS** [comment]
Could you provide a source, then?

**Comment by ekardon** [comment]
source for what? i don't understand. i posted the links?

**Comment by timmyRS** [comment]
The link where you got the links from.

**Comment by ekardon** [comment]
it's a cbox site. you need an account to post and recieve the links. but i can give you the first link they provided.
[Here](https://api.turkdown.com/link/?id=9e75f98b706e025)

**Comment by timmyRS** [comment]
I'd assume the `id` in `https://api.turkdown.com/link/?id=9e75f98b706e025` is globally unique, but I'm not sure what exactly to do with that.

**Comment by ekardon** [comment]
Hey, yea it's probably hold in the database untill link expires. I checked all the links and wrote them down after you said that. There doesn't seem to be anything that can be done, other bypassing all shorteners.

Here, all the links:

```md
https://api.turkdown.com/link/?id=9e75f98b706e025
https://api.turkdown.com/link/?ajax=9e75f98b706e025
http://ultimate.turkdown.com/link.php?stepone=aHR0cDovL2JjLnZjL0s2UEQ1Smk=      (http://bc.vc/K6PD5Ji)
http://ultimate.turkdown.com/link.php?link=aHR0cDovL2V4ZS5pby9lNkR4ajFjdg==     (http://exe.io/e6Dxj1cv)
http://ultimate.turkdown.com/link.php?link=aHR0cHM6Ly9zaG90bHkuaW8vNTgyMQ==     (https://shotly.io/5821)
http://ultimate.turkdown.com/link.php?link=aHR0cDovL3RtZWFybi5jb20vNjJHZnFE     (http://tmearn.com/62GfqD)
http://ultimate.turkdown.com/link.php?link=aHR0cDovL2NsaWsucHcvemxsSTB0         (http://clik.pw/zllI0t)
http://ultimate.turkdown.com/link.php?link=aHR0cHM6Ly9zaHJpbmttZS5pby9lYmxP     (https://shrinkme.io/eblO)
http://ultimate.turkdown.com/link.php?link=aHR0cDovL3Nob3J0ZWFybi5ldS9QSDY4TFAx (http://shortearn.eu/PH68LP1)
http://perfect.turkdown.com/download/?file=695e7c7cdea8595a767097d35e3e96
```


All shorteners return back to original website but they have a `link` parameter, which is the actual url for the shorteners base64 encoded (I included them inside the parentheses). Other than that, I wasn't able to do anything.

**Comment by timmyRS** [comment]
If the links stay consistent tho, then crowd bypass should be working as intended.

**Comment by ekardon** [comment]
how can it stay consistent? for each file i requested all of the above generated from scratch. Anyways i think there is no way to bypass any of this.

**Comment by timmyRS** [comment]
If that `http://perfect.turkdown.com/download/?file=695e7c7cdea8595a767097d35e3e96` link directly downloads the file, then bypassing it might be difficult.

**Comment by ekardon** [comment]
yes that's the final link which downloads the file. I double checked there were no more redirects etc.
