### ISSUE TITLE
Shrink-service.it

### ISSUE THREAD

**Issue by arminolat** [timmyRS/Universal-Bypass#949]
Greetings!

I've been using your great extension for quite some time now, but recently I've been having some trouble with shrink-service.it

Is there any way to bypass this? Nothing happens when I open these links.
I see someone made a similar request a couple years ago, it says it was implemented, but that's it.  https://github.com/timmyrs/Universal-Bypass/issues/81
Thanks!

Olat

**Comment by timmyRS** [comment]
Could you provide an example link?

**Comment by timmyRS** [comment]
I had deleted that bypass later as the website seemed dead, which it apparently isn't. Either way, the bypass no longer works. And I'm not to sure the site itself works; I have this link `https://adshrink.it/2ualzJ` which is meant to go to `https://google.com` but I just can't get it to do it.

**Comment by timmyRS** [comment]
Nevermind, I did get it to do it by some miracle, but unfortunately that link actually lead to `https://adshrink.it/adshrink-unauthorized/`. Honestly, the website is broken in its current state, so I'm not sure anyone even uses it.

**Comment by arminolat** [comment]
Hi, thanks for replying!

Those links are used on Worldsrc.org, which is probably one of the most popular direct download sites currently. 

Also, dlfox :( 

Anyway, thanks for trying, the extension is still awesome, I just hoped these could be implemented as well. 

Cheers!

**Comment by timmyRS** [comment]
I just clicked on the first series I saw on worldsrc.org, and the "Direct download" button gave me a direct download.

**Comment by arminolat** [comment]
Hmmm... The website is available in English too, in the upper right corner. 

I tried multiple links, for example this one https://www.worldsrc.org/games/detalis?Ty=148

It just takes me to adshrink.it 

Are you able to open it?

**Comment by timmyRS** [comment]
I see. That can be bypassed easily, and will be in 13.4. :)

**Comment by arminolat** [comment]
That's great!

Thank you so much!

**Comment by arminolat** [comment]
I just tested it and it works now!

Thank you so so much, you're a legend! :)
