### ISSUE TITLE
Breakage

### ISSUE THREAD

**Issue by ghajini** [timmyRS/Universal-Bypass#951]
over here
https://babahd.host/mere-brother-ki-dulhan-2011-hindi-400mb-bluray-480p-downlaod/

when I try to download by clicking `watch online and single download link`
and follow subsequent steps I get final page saying ***bad request***
This breakage happens on every other ***such*** sites iam using

I have crowd bypass disabled....

with universal bypass disabled I get final page `pktrade.site`

other extensions iam using are ublock origin and decentraleyes

**Comment by timmyRS** [comment]
This will be fixed in the next release. In the meanwhile, you could enable crowd bypass to prevent this issue.

**Comment by ghajini** [comment]
Every other link is unique, so I doubt crowd bypass work?, also I have a bit false redirections when crowd bypass enabled. ....
