### ISSUE TITLE
How to Disable Universal Bypass in spesific Website?

### ISSUE THREAD

**Issue by Dhanamerdeka** [timmyRS/Universal-Bypass#953]
How to Disable Universal Bypass in spesific Website?

**Comment by timmyRS** [comment]
The real question is: which website is UB causing issues on? So, you know, it can get fixed.

**Comment by Dhanamerdeka** [comment]
I mean.... like
Universal bypass run in all short url website
ouo.io adfly etc
but i want to disable this on ouo.io
how i can setting that?

**Comment by timmyRS** [comment]
Why would you want to disable it on ouo.io?

**Comment by Dhanamerdeka** [comment]
no i mean
can i setting it by myself to disable the script run in spesific url?
like make custom whitelist for user?

**Comment by timmyRS** [comment]
You can't. Why would you want that? What issue do you currently have on ouo.io?

**Comment by Dhanamerdeka** [comment]
no. like i wan't to disable the script when going to the shortlink from the author that i supported 
so i don't want to use the script
i think that weired that i must go to setting just for go trough the safelink and then turn on that again

**Comment by timmyRS** [comment]
So, you would like to disable the entire ouo.io bypass just to support 1 person who happens to use that site?

**Comment by RandomKino** [comment]
Hi there, seems like UB is causing issues on movie.douban.com. I also wish there is whitelist option.

**Comment by timmyRS** [comment]
@RandomKino What issues is it causing on movie.douban.com? Would you mind creating a new issue?

**Comment by Dhanamerdeka** [comment]
I think you missunderstand what i want to say
I say... can this script create new feature or a way to disable some site individually by user
in example i want ouo.io disabled or other safelink to be disable
but in other people that site script run normally....
do u understand what i saying about?
i need some "Custom Whitelist"

**Comment by timmyRS** [comment]
I understand what you want, but I don't understand why it should be a feature. Since there is no issue with the ouo.io bypass, I'll close this.

**Comment by Dhanamerdeka** [comment]
:( nooooooooo
I dont have problem with ouo io,,,
I use ouo io for example...
like anyone want to all shortlink to be skipped automatically
but other need some of it to be excepted from this script
now you understand the point of this? :) pls understand
i know my english is bad :v

**Comment by timmyRS** [comment]
I understand what you're saying, but I don't think it would be a useful addition to Universal Bypass.

**Comment by ikancupang** [comment]
@Dhanamerdeka if you really want to whitelist a domain for example "ouo.io", Add `domainBypass("ouo.io")` to `Custom Bypasses`.

**Comment by timmyRS** [comment]
That won't always work, but for ouo.io, it just might, although it should be
```Javascript
domainBypass("ouo.io",()=>{})
```
to prevent anything from breaking.
