### ISSUE TITLE
short.pe

### ISSUE THREAD

**Issue by theOptimistic** [timmyRS/Universal-Bypass#957]
Link: `https://short.pe/full?api=c056d7df413b9f9d5e751a849fb36c7ce8e8f96e&url=bWFnbmV0Oj94dD11cm46YnRpaDpkOTgzYWNlZTBjNTYzYWI3MDBlZTdkOGFkYTlmNTk0MWIzYTkyOTU3JmRuPVRoZS5XYWxraW5nLkRlYWQuUzEwRTA5LjcyMHAuV0VCLkgyNjQtWExGJTVCcmFydHYlNUQmdHI9aHR0cCUzQSUyRiUyRnRyYWNrZXIudHJhY2tlcmZpeC5jb20lM0E4MCUyRmFubm91bmNlJnRyPXVkcCUzQSUyRiUyRjkucmFyYmcubWUlM0EyNzIwJnRyPXVkcCUzQSUyRiUyRjkucmFyYmcudG8lM0EyNzgw&type=1`

From: `https://edvok.com/the-walking-dead-temp-10seriehd2019estreno`

**Comment by timmyRS** [comment]
This will be fixed in the next release.
