### ISSUE TITLE
Issues on movie.douban.com

### ISSUE THREAD

**Issue by RandomKino** [timmyRS/Universal-Bypass#959]
Hi there, I found 2 issues that might caused by UB on firefox. 

First is the front page, the 2 sections on the top will be forever loading when UB is on.

Normal (UB is off): 
![1](https://user-images.githubusercontent.com/61402104/75130188-f85cb900-569a-11ea-9148-0adfe40b9c78.png)

Abnormal (UB is on):
![2](https://user-images.githubusercontent.com/61402104/75130220-175b4b00-569b-11ea-98d3-6695ae1fb876.png)

Another issue is when I submitting the rating on a movie page, instead of refresh the page, it will redirect to a page like this: 
![3](https://user-images.githubusercontent.com/61402104/75130308-a4060900-569b-11ea-8582-f58483a4fed3.PNG)

**Comment by timmyRS** [comment]
I can't test creating a review, but the homepage is loading fine for me using UB 13.5 on Firefox.

**Comment by RandomKino** [comment]
Oh really? I already disabled all the other extensions when I was testing. Now I'm wondering what actually causing those issues. Anyway, thanks for the reply, great work, saves a lot of time. :)
