### ISSUE TITLE
Bypass broken for nekopoi safelink

### ISSUE THREAD

**Issue by anakaiti** [timmyrs/Universal-Bypass#96]
It redirects to a corrupted link. In my case:

Original link: 
```
http://arubedo.blogspot.com/p/nxt.html?url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL29wZW4/aWQ9MW5ZZk0wMnlfMTZzUlpDUVhyNHVLT1hIMUNxWl9aeVBP
```
Bypassed link: 
```
https://arubedo.blogspot.com/p/%E6%9B%A9%E3%BF%9A%EE%A6%9Ev%E6%A5%A2%0B)%E2%97%A8%EB%BA%BF%EF%9B%A1%E6%A9%AE%EE%9A%9D%1D%1C%1C%CE%8B%CB%99%1C%EA%9D%99K%E9%9B%9B%D9%9B%19K%E8%9B%9BK%DB%9C%19[%EF%9A%99%0FL[%E6%99%93L%0C%EE%97%8CM%EC%94%96%D4%96%1C%ED%9D%92%D3%96%12%0CP%DC%96%E7%96%9ET`
```
Expected bypass link:
```
https://drive.google.com/open?id=1nYfM02y_16sRZCQXr4uKOXH1CqZ_ZyPO
```

Example links: [1](https://drive.google.com/open?id=1nYfM02y_16sRZCQXr4uKOXH1CqZ_ZyPO) | (2)[https://www53.zippyshare.com/v/1wo9XHKD/file.html]

The script used seems to be [Nekopoi Safelink](https://www.codepelajar.com/2018/10/template-safelink-nekopoi.html)(text in Indonesian)

**Comment by timmyrs** [comment]
Works in Firefox and Chrome using latest version.
