### ISSUE TITLE
Destination automatically closes using Firefox for Android

### ISSUE THREAD

**Issue by Bivoutic** [timmyRS/Universal-Bypass#960]
I dont have much to say besides the title, happened with all the test links too

**Comment by timmyRS** [comment]
Which browser and which versions?

**Comment by Bivoutic** [comment]
Firefox 68.5.0

**Comment by timmyRS** [comment]
As an immediate fix: If you change the "Automatically take me to destinations after 0 seconds." option to anything other than 0 seconds or you just turn it off, it seems to be working fine.
