### ISSUE TITLE
GOOGLE exetention universal bybass it says error 404 cant find this url ??

### ISSUE THREAD

**Issue by Universskd** [timmyRS/Universal-Bypass#961]

**Comment by timmyRS** [comment]
As per usual, Google are being idiots. Universal Bypass should be available from the Chrome Web Store again in a couple of days.

**Comment by 3xploiton3** [comment]
then alternative to install?

please make tutorial manually when google act like that

**Comment by timmyRS** [comment]
Google literally does not allow you to install extensions in any other way than from the Chrome Web Store.

**Comment by 3xploiton3** [comment]
> Google literally does not allow you to install extensions in any other way than from the Chrome Web Store.

i did install manually on brave browser, for now running well

just showing few error

Unrecognized manifest key 'browser_specific_settings'.
`"browser_specific_settings": {

> 		"gecko": {
> 			"id": "{529b261b-df0b-4e3b-bf42-07b462da0ee8}"
> 		}
> 	},`

**Comment by timmyRS** [comment]
You should use `php .build.php` to create this file: [Universal Bypass for Chromium-based browsers.zip](https://github.com/timmyRS/Universal-Bypass/files/4247906/Universal.Bypass.for.Chromium-based.browsers.zip)

I guess you could load it in somehow? However, Google really doesn't like anyone doing this, and it won't auto-update, but it might work.

**Comment by jcvr1994** [comment]
https://www.crx4chrome.com/extensions/aihomhdbhpnpmcnnbckjjcebjoikpihj/

**Comment by Noah670** [comment]
Why does Google keep on blocking this, manually adding the .crx works but you have to manually update each release.

**Comment by kegang0619** [comment]
I'm waiting for it

**Comment by smilefate** [comment]
• Download ([clone/packaged](https://codeload.github.com/timmyRS/Universal-Bypass/zip/master)) file on Github.
• Download "[Google Chrome DEV](https://www.google.com/intl/tr/chrome/dev/)" version.
•  Enter the extensions (chrome://extensions/) section of the browser> Activate "Developer Mode" from the top right> Press the "Load Unpacked" button.> Select the Clone file you downloaded from Github and you can use it easily. 🎉🎉🎉

**Comment by timmyRS** [comment]
You don't even need the developer version of Google Chrome to load the clone, but if you do that you're not gonna get **any** updates.

**Comment by smilefate** [comment]
I know, but regular web store updates are late.

**Comment by timmyRS** [comment]
I honestly thought this issue with Google would've been resolved by now, but whatever, life goes on, and I just released 13.6: 
[Universal Bypass for Chromium-based browsers.zip](https://github.com/timmyRS/Universal-Bypass/files/4274579/Universal.Bypass.for.Chromium-based.browsers.zip)

**Comment by smilefate** [comment]
Will it get updates? great then

**Comment by timmyRS** [comment]
It will auto-update the bypass definitions: https://universal-bypass.org/faq#versions

**Comment by remanime** [comment]
excuse me ummm im not good with pc so could you make a video  how to add to google 
about You should use php .build.php to create this file: Universal Bypass for Chromium-based browsers.zip

**Comment by smilefate** [comment]
> excuse me ummm im not good with pc so could you make a video how to add to google
> about You should use php .build.php to create this file: Universal Bypass for Chromium-based browsers.zip

https://streamable.com/pnevy

**Comment by timmyRS** [comment]
13.7 has just been released: https://universal-bypass.org/install

**Comment by blackhack** [comment]
Whats going on with the web store version? The drag and drop way works but because it's store in the Temp folder, sometimes for a reason or another it will get deleted and the extension will crap in you...
![image](https://user-images.githubusercontent.com/1264051/76366449-04ca4e00-62f8-11ea-99ea-93c43fceac69.png)

**Comment by timmyRS** [comment]
Well, it is a temporary solution until Google decides... I don't know, something. But in your case, I suspect that you have some software like CCleaner running to purposefully empty your Temp folder regularly.

**Comment by LGLTeam** [comment]
Extract the extension to other location and load from there. It won't get deleted

**Comment by timmyRS** [comment]
Universal Bypass is available in the Chrome store again now: https://chrome.google.com/webstore/detail/universal-bypass/aihomhdbhpnpmcnnbckjjcebjoikpihj
