### ISSUE TITLE
Site problem

### ISSUE THREAD

**Issue by mich3lam** [timmyRS/Universal-Bypass#962]
Haaeretz stop working and keeps refreshing.

https://www.haaretz.co.il/gallery/.premium-MAGAZINE-1.8530141

This is an example of what's happening.

**Comment by timmyRS** [comment]
Not sure if we should try to make this bypass work again, but Universal Bypass isn't really in the business of blocking paywalls.

**Comment by ikancupang** [comment]
@timmyRS maybe we can try adding a Googlebot header to bypass paywalls
```ruby
details.requestHeaders.push({
	name: "User-Agent",
	value: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
})
```

**Comment by timmyRS** [comment]
That does seem to work, nice one!
