### ISSUE TITLE
steamcommunity.com/linkfilter/?url=

### ISSUE THREAD

**Issue by ThunderRahja** [timmyRS/Universal-Bypass#965]
I respectfully request a filter for steamcommunity.com, which displays a warning page before allowing user-provided links to be followed. For example, a URL posted using the text `example.com` creates a link to the page `https://steamcommunity.com/linkfilter/?url=http://example.com`, which requires users to click a button that directs them to `http://example.com`.

I have a rough but working bypass function that will work for most URLs there, but it should be refined to handle all filtered links.
```javascript
hrefBypass(/steamcommunity\.com\/linkfilter\/\?url=/, () => {
    let url = window.location.toString().split("url=")[1]
    safelyNavigate(url)
})
```

**Comment by timmyRS** [comment]
There is a good reason for that page to exist: So that scammers won't fool you into thinking you're still on Steam. I feel if Universal Bypass removed that, it would make it easier for scammers to scam you.

**Comment by ThunderRahja** [comment]
I agree that that page most likely reduces the number of successful scams against the average user. However, as someone who sees the link filter page multiple times a day, I can appreciate a time-saving skip for that page. External links typically have the domain appended after them (e.g. [Click this link!](#) `[www.example.com]`) that also serve as warning that a link directs to an external website, so that even with a bypass, I am aware that I am visiting another website.
