### ISSUE TITLE
Bug crowd bypass on oploverz

### ISSUE THREAD

**Issue by SuperMarioMakerII** [timmyRS/Universal-Bypass#992]
https://www.oploverz.in/one-piece-stampede-sub-indo-wbdl/

**Comment by timmyRS** [comment]
Seems to be working fine.

**Comment by SuperMarioMakerII** [comment]
@timmyRS `https://drive.google.com/open?id=1xnkpqRg1rb--QZP9-VX1BEH9s_-7Z5Lx`

**Comment by timmyRS** [comment]
Don't mind my revert, I introduced this issue in an earlier commit, which I also reverted.
