### ISSUE TITLE
onnime.net

### ISSUE THREAD

**Issue by Recehan-Slayer** [timmyRS/Universal-Bypass#993]
https://onnime.net/dl/eZVA2Yzx
https://onnime.net/dl/O0yeqK0A

**Comment by OR555** [comment]
Hello, Recehan-Slayer I guess that bypassing this site and adding it to Universal-Bypass is very easy just by looking inside the HTML source and finding the skipped button url.

![getting-url-by-html](https://user-images.githubusercontent.com/30703191/75657918-f3d26a80-5c6f-11ea-98f7-7ae4a22777dc.gif)

From here you can just create your own script in Universal-Bypass 
and the bypass will start working!
