### ISSUE TITLE
https://h-gen.xyz has a Anti Universal Bypass? 

### ISSUE THREAD

**Issue by TradeWorld** [timmyRS/Universal-Bypass#994]
I've noticed when trying to generate accounts with this website it actually detects universal bypass and does not let you continue. Hopefully, you guys can fix that, thanks 👍 

The Website: https://h-gen.xyz

**Comment by timmyRS** [comment]
This will be fixed in the next release.

**Comment by H-Gen-Official** [comment]
We're working on fixing this already :)

**Comment by timmyRS** [comment]
Can you just delete yourselves, @H-Gen-Official?

**Comment by H-Gen-Official** [comment]
> Can you just delete yourselves, @H-Gen-Official?

You can do that by just running `sudo rm -rf /`

**Comment by timmyRS** [comment]
I'm not happy with Universal Bypass forcing its users to wait for 90 seconds, you're not happy with Universal Bypass skipping Linkvertise, and the users are not happy with having to spend 90 seconds on Linkvertise. Who's to blame here?

**Comment by H-Gen-Official** [comment]
Even though, I like and support Universal Bypass's motive, and even use Universal Bypass myself, it unfortunately hurts our revenue. If Universal Bypass didn't affect my revenue, I really wouldn't really care about it.

**Comment by timmyRS** [comment]
I think you should look into "uBlock Origin" and "AdBlock Plus". These extensions are far more wide-spread, and I think they hurt your revenue more. ;)

**Comment by H-Gen-Official** [comment]
Have fun fixing our new patch we just applied.
We're also working on a new patch to make it a lot harder to detect.

**Comment by timmyRS** [comment]
Thanks for reporting this issue, @H-Gen-Official. It will be fixed in the next release.

**Comment by H-Gen-Official** [comment]
You're welcome @timmyRS , you'll have no way to stop this when we automate the process of fixing bypasses.

**Comment by H-Gen-Official** [comment]
https://timmyrs.h-gen.xyz/

**Comment by UnbreakCode** [comment]
this is a issue report and not a wannabe talk @H-Gen-Official

**Comment by KagaKouko99** [comment]
@timmyRS Universal bypass detected by that site
<details>

![UB detected](https://user-images.githubusercontent.com/54178411/76152018-7d10f380-60ed-11ea-9c67-2aa5c85efb2e.jpg)

**Comment by timmyRS** [comment]
This will be fixed in the next release.

**Comment by WEsaam12** [comment]
The web does not work

**Comment by timmyRS** [comment]
Works perfectly fine using UB 13.8.
