### ISSUE TITLE
theartistunion.com

### ISSUE THREAD

**Issue by heywolf15** [timmyRS/Universal-Bypass#999]
https://theartistunion.com/tracks/e2a3a2

https://theartistunion.com/tracks/df4933

**Comment by timmyRS** [comment]
What exactly is there to be bypassed?

**Comment by heywolf15** [comment]
Free download need to connect Soundcloud or Spotify and will auto follow, repost, like.
The same like https://www.toneden.io/yungestbae/post/selfish-high-heels
and apparently toneden.io bypass no longer working

**Comment by timmyRS** [comment]
Looks like toneden.io added backend validation to make sure you have actually followed before you can download the file.
